// Generated by Framer (8b16de8)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  ResolveLinks,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useRouter,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import ShopCategoryCard from "https://framerusercontent.com/modules/MbHLNiM0ZTp37R7i9qDt/mg366GjGos0yTeE4YFh4/lix_Ibt32.js";
const ShopCategoryCardFonts = getFonts(ShopCategoryCard);
const cycleOrder = ["ISziLRTdc", "bk3MGP0Xq", "STsCn7Vqm", "G6tu6Omk_"];
const serializationHash = "framer-Z2Om5";
const variantClassNames = {
  bk3MGP0Xq: "framer-v-fnlujg",
  G6tu6Omk_: "framer-v-kvum4e",
  ISziLRTdc: "framer-v-c6kf26",
  STsCn7Vqm: "framer-v-1b5t698",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const NoghC0Wxj = undefined;
const Z7XH83ag8 = undefined;
const dcMNaYebc = undefined;
const EasSLkBR1 = undefined;
const SSb4q7b27 = undefined;
const EZ1B_DxvX = undefined;
const fVcyFlqF_ = undefined;
const setNoghC0Wxj = undefined;
const setZ7XH83ag8 = undefined;
const setSSb4q7b27 = undefined;
const setEZ1B_DxvX = undefined;
const transition1 = {
  damping: 60,
  delay: 0,
  mass: 1,
  stiffness: 500,
  type: "spring",
};
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const numberToPixelString = (value) => {
  if (typeof value !== "number") return value;
  if (!Number.isFinite(value)) return undefined;
  return Math.max(0, value) + "px";
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  Default: "ISziLRTdc",
  Men: "bk3MGP0Xq",
  Phone: "G6tu6Omk_",
  Women: "STsCn7Vqm",
};
const Variants = motion.create(React.Fragment);
const useStateVariable = (externalState, setExternalState) => {
  const [internalState, setInternalState] = React.useState(externalState);
  const [previousExternalState, setPreviousExternalState] =
    React.useState(externalState);
  if (setExternalState) {
    return [externalState, setExternalState];
  }
  if (externalState !== previousExternalState) {
    setInternalState(externalState);
    setPreviousExternalState(externalState);
  }
  return [internalState, setInternalState];
};
const getProps = ({
  height,
  id,
  menSWearImage,
  menSWearSub,
  menSWearTitle,
  padding,
  width,
  womenSWearImage,
  womenSWearSub,
  womenSWearTitle,
  ...props
}) => {
  return {
    ...props,
    dcMNaYebc: menSWearImage ??
      props.dcMNaYebc ?? {
        pixelHeight: 768,
        pixelWidth: 1408,
        src: "https://framerusercontent.com/images/JZY7mU9zmYQnlpDnikHpNTfRiEs.png?width=1408&height=768",
        srcSet:
          "https://framerusercontent.com/images/JZY7mU9zmYQnlpDnikHpNTfRiEs.png?scale-down-to=512&width=1408&height=768 512w,https://framerusercontent.com/images/JZY7mU9zmYQnlpDnikHpNTfRiEs.png?scale-down-to=1024&width=1408&height=768 1024w,https://framerusercontent.com/images/JZY7mU9zmYQnlpDnikHpNTfRiEs.png?width=1408&height=768 1408w",
      },
    EasSLkBR1: padding ?? props.EasSLkBR1 ?? "20px",
    EZ1B_DxvX:
      womenSWearSub ?? props.EZ1B_DxvX ?? "Womenswear for Every Occasion",
    fVcyFlqF_: womenSWearImage ??
      props.fVcyFlqF_ ?? {
        pixelHeight: 1632,
        pixelWidth: 2353,
        src: "https://framerusercontent.com/images/UkiypCfV1c3xemOZlf1LuGrui5o.png?width=2353&height=1632",
        srcSet:
          "https://framerusercontent.com/images/UkiypCfV1c3xemOZlf1LuGrui5o.png?scale-down-to=512&width=2353&height=1632 512w,https://framerusercontent.com/images/UkiypCfV1c3xemOZlf1LuGrui5o.png?scale-down-to=1024&width=2353&height=1632 1024w,https://framerusercontent.com/images/UkiypCfV1c3xemOZlf1LuGrui5o.png?scale-down-to=2048&width=2353&height=1632 2048w,https://framerusercontent.com/images/UkiypCfV1c3xemOZlf1LuGrui5o.png?width=2353&height=1632 2353w",
      },
    NoghC0Wxj: menSWearTitle ?? props.NoghC0Wxj ?? "Men's wear",
    SSb4q7b27: womenSWearTitle ?? props.SSb4q7b27 ?? "Women's wear",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "ISziLRTdc",
    Z7XH83ag8: menSWearSub ?? props.Z7XH83ag8 ?? "Menswear for every occasion",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    dcMNaYebc,
    NoghC0Wxj: externalNoghC0Wxj,
    onNoghC0WxjChange: setExternalNoghC0Wxj,
    Z7XH83ag8: externalZ7XH83ag8,
    onZ7XH83ag8Change: setExternalZ7XH83ag8,
    fVcyFlqF_,
    SSb4q7b27: externalSSb4q7b27,
    onSSb4q7b27Change: setExternalSSb4q7b27,
    EZ1B_DxvX: externalEZ1B_DxvX,
    onEZ1B_DxvXChange: setExternalEZ1B_DxvX,
    EasSLkBR1,
    ...restProps
  } = getProps(props);
  const [NoghC0Wxj, setNoghC0Wxj] = useStateVariable(
    externalNoghC0Wxj,
    setExternalNoghC0Wxj
  );
  const [Z7XH83ag8, setZ7XH83ag8] = useStateVariable(
    externalZ7XH83ag8,
    setExternalZ7XH83ag8
  );
  const [SSb4q7b27, setSSb4q7b27] = useStateVariable(
    externalSSb4q7b27,
    setExternalSSb4q7b27
  );
  const [EZ1B_DxvX, setEZ1B_DxvX] = useStateVariable(
    externalEZ1B_DxvX,
    setExternalEZ1B_DxvX
  );
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "ISziLRTdc",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const d2QuR_VIKbtdydq = activeVariantCallback(async (...args) => {
    setVariant("bk3MGP0Xq");
  });
  const d2QuR_VIKrhj0wk = activeVariantCallback(async (...args) => {
    setVariant("STsCn7Vqm");
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const router = useRouter();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-c6kf26",
            className,
            classNames
          ),
          "data-framer-name": "Default",
          layoutDependency: layoutDependency,
          layoutId: "ISziLRTdc",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              bk3MGP0Xq: { "data-framer-name": "Men" },
              G6tu6Omk_: { "data-framer-name": "Phone" },
              STsCn7Vqm: { "data-framer-name": "Women" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(ResolveLinks, {
              links: [
                {
                  href: { webPageId: "CNxtwd8vu" },
                  implicitPathVariables: undefined,
                },
                {
                  href: { webPageId: "CNxtwd8vu" },
                  implicitPathVariables: undefined,
                },
                {
                  href: { webPageId: "CNxtwd8vu" },
                  implicitPathVariables: undefined,
                },
                {
                  href: { webPageId: "CNxtwd8vu" },
                  implicitPathVariables: undefined,
                },
              ],
              children: (resolvedLinks) =>
                /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                  height: 800,
                  width: `max((${
                    componentViewport?.width || "100vw"
                  } - 15px) / 2, 1px)`,
                  y:
                    (componentViewport?.y || 0) +
                    (0 + ((componentViewport?.height || 640) - 0 - 800) / 2),
                  ...addPropertyOverrides(
                    {
                      bk3MGP0Xq: {
                        width: `calc(${
                          componentViewport?.width || "100vw"
                        } * 0.6)`,
                      },
                      G6tu6Omk_: {
                        height: 500,
                        width: componentViewport?.width || "100vw",
                        y:
                          (componentViewport?.y || 0) +
                          0 +
                          (((componentViewport?.height || 200) - 0 - 1015) / 2 +
                            0 +
                            0),
                      },
                      STsCn7Vqm: {
                        width: `max(${
                          componentViewport?.width || "100vw"
                        } * 0.4 - 15px, 1px)`,
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                  children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                    className: "framer-10wtxsy-container",
                    layoutDependency: layoutDependency,
                    layoutId: "SQmv5OBBt-container",
                    nodeId: "SQmv5OBBt",
                    rendersWithMotion: true,
                    scopeId: "WwVCraiqw",
                    children: /*#__PURE__*/ _jsx(ShopCategoryCard, {
                      aLoeIpSuy: NoghC0Wxj,
                      d2QuR_VIK: d2QuR_VIKbtdydq,
                      E1NhjWguV: numberToPixelString(EasSLkBR1),
                      Edz3ZRmHd: toResponsiveImage(dcMNaYebc),
                      height: "100%",
                      id: "SQmv5OBBt",
                      layoutId: "SQmv5OBBt",
                      onaLoeIpSuyChange: setNoghC0Wxj,
                      onUgy22DNeVChange: setZ7XH83ag8,
                      style: { height: "100%", width: "100%" },
                      Ugy22DNeV: Z7XH83ag8,
                      variant: matchVariant("kdzf2YXCm"),
                      w00fWISlh: resolvedLinks[0],
                      width: "100%",
                      ...addPropertyOverrides(
                        {
                          bk3MGP0Xq: {
                            variant: matchVariant("jMgAsZk7m"),
                            w00fWISlh: resolvedLinks[1],
                          },
                          G6tu6Omk_: {
                            d2QuR_VIK: undefined,
                            variant: matchVariant("sz1UfzhCt"),
                            w00fWISlh: resolvedLinks[3],
                          },
                          STsCn7Vqm: { w00fWISlh: resolvedLinks[2] },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                    }),
                  }),
                }),
            }),
            /*#__PURE__*/ _jsx(ResolveLinks, {
              links: [
                {
                  href: { webPageId: "ihpyuJvKq" },
                  implicitPathVariables: undefined,
                },
                {
                  href: { webPageId: "ihpyuJvKq" },
                  implicitPathVariables: undefined,
                },
                {
                  href: { webPageId: "ihpyuJvKq" },
                  implicitPathVariables: undefined,
                },
                {
                  href: { webPageId: "ihpyuJvKq" },
                  implicitPathVariables: undefined,
                },
              ],
              children: (resolvedLinks1) =>
                /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                  height: 800,
                  width: `max((${
                    componentViewport?.width || "100vw"
                  } - 15px) / 2, 1px)`,
                  y:
                    (componentViewport?.y || 0) +
                    (0 + ((componentViewport?.height || 640) - 0 - 800) / 2),
                  ...addPropertyOverrides(
                    {
                      bk3MGP0Xq: {
                        width: `max(${
                          componentViewport?.width || "100vw"
                        } * 0.4 - 15px, 1px)`,
                      },
                      G6tu6Omk_: {
                        height: 500,
                        width: componentViewport?.width || "100vw",
                        y:
                          (componentViewport?.y || 0) +
                          0 +
                          (((componentViewport?.height || 200) - 0 - 1015) / 2 +
                            500 +
                            15),
                      },
                      STsCn7Vqm: {
                        width: `calc(${
                          componentViewport?.width || "100vw"
                        } * 0.6)`,
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                  children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                    className: "framer-3cfc4u-container",
                    layoutDependency: layoutDependency,
                    layoutId: "y7sIDTRQ0-container",
                    nodeId: "y7sIDTRQ0",
                    rendersWithMotion: true,
                    scopeId: "WwVCraiqw",
                    children: /*#__PURE__*/ _jsx(ShopCategoryCard, {
                      aLoeIpSuy: SSb4q7b27,
                      d2QuR_VIK: d2QuR_VIKrhj0wk,
                      E1NhjWguV: numberToPixelString(EasSLkBR1),
                      Edz3ZRmHd: toResponsiveImage(fVcyFlqF_),
                      height: "100%",
                      id: "y7sIDTRQ0",
                      layoutId: "y7sIDTRQ0",
                      onaLoeIpSuyChange: setSSb4q7b27,
                      onUgy22DNeVChange: setEZ1B_DxvX,
                      style: { height: "100%", width: "100%" },
                      Ugy22DNeV: EZ1B_DxvX,
                      variant: matchVariant("kdzf2YXCm"),
                      w00fWISlh: resolvedLinks1[0],
                      width: "100%",
                      ...addPropertyOverrides(
                        {
                          bk3MGP0Xq: { w00fWISlh: resolvedLinks1[1] },
                          G6tu6Omk_: {
                            d2QuR_VIK: undefined,
                            variant: matchVariant("sz1UfzhCt"),
                            w00fWISlh: resolvedLinks1[3],
                          },
                          STsCn7Vqm: {
                            variant: matchVariant("jMgAsZk7m"),
                            w00fWISlh: resolvedLinks1[2],
                          },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                    }),
                  }),
                }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-Z2Om5.framer-11i4bkx, .framer-Z2Om5 .framer-11i4bkx { display: block; }",
  ".framer-Z2Om5.framer-c6kf26 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 15px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1100px; }",
  ".framer-Z2Om5 .framer-10wtxsy-container, .framer-Z2Om5 .framer-3cfc4u-container { flex: 1 0 0px; height: calc(var(--framer-viewport-height, 100vh) * 0.8); position: relative; width: 1px; }",
  ".framer-Z2Om5.framer-v-fnlujg .framer-10wtxsy-container, .framer-Z2Om5.framer-v-1b5t698 .framer-3cfc4u-container { flex: none; width: 60%; }",
  ".framer-Z2Om5.framer-v-kvum4e.framer-c6kf26 { flex-direction: column; width: 400px; }",
  ".framer-Z2Om5.framer-v-kvum4e .framer-10wtxsy-container, .framer-Z2Om5.framer-v-kvum4e .framer-3cfc4u-container { flex: none; height: calc(var(--framer-viewport-height, 100vh) * 0.5); width: 100%; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 640
 * @framerIntrinsicWidth 1100
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"bk3MGP0Xq":{"layout":["fixed","auto"]},"STsCn7Vqm":{"layout":["fixed","auto"]},"G6tu6Omk_":{"layout":["fixed","auto"]}}}
 * @framerVariables {"dcMNaYebc":"menSWearImage","NoghC0Wxj":"menSWearTitle","Z7XH83ag8":"menSWearSub","fVcyFlqF_":"womenSWearImage","SSb4q7b27":"womenSWearTitle","EZ1B_DxvX":"womenSWearSub","EasSLkBR1":"padding"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerWwVCraiqw = withCSS(Component, css, "framer-Z2Om5");
export default FramerWwVCraiqw;
FramerWwVCraiqw.displayName = "ShopCategoryContainer";
FramerWwVCraiqw.defaultProps = { height: 640, width: 1100 };
addPropertyControls(FramerWwVCraiqw, {
  variant: {
    options: ["ISziLRTdc", "bk3MGP0Xq", "STsCn7Vqm", "G6tu6Omk_"],
    optionTitles: ["Default", "Men", "Women", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  dcMNaYebc: {
    __defaultAssetReference:
      "data:framer/asset-reference,JZY7mU9zmYQnlpDnikHpNTfRiEs.png?originalFilename=image.png&preferredSize=auto",
    title: "Men's Wear Image",
    type: ControlType.ResponsiveImage,
  },
  NoghC0Wxj: {
    defaultValue: "Men's wear",
    displayTextArea: false,
    title: "Men's Wear Title",
    type: ControlType.String,
  },
  onNoghC0WxjChange: { changes: "NoghC0Wxj", type: ControlType.ChangeHandler },
  Z7XH83ag8: {
    defaultValue: "Menswear for every occasion",
    displayTextArea: false,
    title: "Men's Wear Sub",
    type: ControlType.String,
  },
  onZ7XH83ag8Change: { changes: "Z7XH83ag8", type: ControlType.ChangeHandler },
  fVcyFlqF_: {
    __defaultAssetReference:
      "data:framer/asset-reference,UkiypCfV1c3xemOZlf1LuGrui5o.png?originalFilename=kaborkhlq_A_clean_editorial-style_photograph_of_a_stylesh_blond_d7540cf8-9f72-4d4b-b297-b9adf4db1d1f.png&width=2353&height=1632",
    title: "Women's Wear Image",
    type: ControlType.ResponsiveImage,
  },
  SSb4q7b27: {
    defaultValue: "Women's wear",
    displayTextArea: false,
    title: "Women's Wear Title",
    type: ControlType.String,
  },
  onSSb4q7b27Change: { changes: "SSb4q7b27", type: ControlType.ChangeHandler },
  EZ1B_DxvX: {
    defaultValue: "Womenswear for Every Occasion",
    displayTextArea: false,
    title: "Women's Wear Sub",
    type: ControlType.String,
  },
  onEZ1B_DxvXChange: { changes: "EZ1B_DxvX", type: ControlType.ChangeHandler },
  EasSLkBR1: {
    defaultValue: "20px",
    title: "Padding",
    type: ControlType.Padding,
  },
});
addFonts(
  FramerWwVCraiqw,
  [{ explicitInter: true, fonts: [] }, ...ShopCategoryCardFonts],
  { supportsExplicitInterCodegen: true }
);
FramerWwVCraiqw.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([forwardLoader(ShopCategoryCard, {}, context)]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerWwVCraiqw",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerContractVersion: "1",
        framerIntrinsicHeight: "640",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"bk3MGP0Xq":{"layout":["fixed","auto"]},"STsCn7Vqm":{"layout":["fixed","auto"]},"G6tu6Omk_":{"layout":["fixed","auto"]}}}',
        framerIntrinsicWidth: "1100",
        framerVariables:
          '{"dcMNaYebc":"menSWearImage","NoghC0Wxj":"menSWearTitle","Z7XH83ag8":"menSWearSub","fVcyFlqF_":"womenSWearImage","SSb4q7b27":"womenSWearTitle","EZ1B_DxvX":"womenSWearSub","EasSLkBR1":"padding"}',
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerAutoSizeImages: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./WwVCraiqw.map
