// Generated by Framer (8e1ebfe)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addPropertyControls,
  ControlType,
  cx,
  motion,
  useSVGTemplate,
  withCSS,
} from "framer";
import * as React from "react";
import { forwardRef } from "react";
const o7u3jogiS = undefined;
const dwH03SpeX = undefined;
const mask = "var(--framer-icon-mask)";
const Base = /*#__PURE__*/ forwardRef(function (props, ref) {
  return /*#__PURE__*/ _jsx("svg", {
    ...props,
    ref: ref,
    children: props.children,
  });
});
const MotionSVG = motion.create(Base);
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(MotionSVG, {
        ...rest,
        layoutId: layoutId,
        ref: ref,
        children: children,
      })
    : /*#__PURE__*/ _jsx("svg", { ...rest, ref: ref, children: children });
});
const svg =
  '<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 12 0 L 0 12" fill="transparent" height="12px" id="aqARkmqOt" stroke-dasharray="0" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--19p0sve, 1.5)" stroke="var(--1ueuxnb, var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0)))" transform="translate(6 6)" width="12px"/><path d="M 0 0 L 12 12" fill="transparent" height="12px" id="Y9xh9YSc2" stroke-dasharray="0" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--19p0sve, 1.5)" stroke="var(--1ueuxnb, var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0)))" transform="translate(6 6)" width="12px"/></svg>';
const getProps = ({ color, fill, height, id, width, width1, ...props }) => {
  return {
    ...props,
    dwH03SpeX:
      color ??
      props.dwH03SpeX ??
      "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
    h8kC9jrrV: fill ?? props.h8kC9jrrV ?? "rgba(0, 0, 0, 0)",
    o7u3jogiS: width1 ?? props.o7u3jogiS ?? 1.5,
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const {
    style,
    className,
    layoutId,
    variant,
    dwH03SpeX,
    h8kC9jrrV,
    o7u3jogiS,
    ...restProps
  } = getProps(props);
  const href = useSVGTemplate("4224079184", svg);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    className: cx("framer-YpmBx", className),
    layoutId: layoutId,
    ref: ref,
    role: "presentation",
    style: { "--19p0sve": o7u3jogiS, "--1ueuxnb": dwH03SpeX, ...style },
    viewBox: "0 0 24 24",
    children: /*#__PURE__*/ _jsx("use", { href: href }),
  });
});
const css = [
  `.framer-YpmBx { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"dwH03SpeX":"color","h8kC9jrrV":"fill","o7u3jogiS":"width1"}
 * @framerImmutableVariables true
 * @framerVector {"name":"x","color":{"type":"variable","value":"1ueuxnb"},"set":{"localId":"vectorSet/XcHWe4vE5","id":"XcHWe4vE5","moduleId":"4pmxSVQBLYE9vfheas6H"}}
 */ const Icon = withCSS(Component, css, "framer-YpmBx");
Icon.displayName = "x";
export default Icon;
addPropertyControls(Icon, {
  dwH03SpeX: {
    defaultValue:
      'var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0)) /* {"name":"Black"} */',
    hidden: false,
    title: "Color",
    type: ControlType.Color,
  },
  h8kC9jrrV: {
    defaultValue: "rgba(0, 0, 0, 0)",
    hidden: true,
    title: "Fill",
    type: ControlType.Color,
  },
  o7u3jogiS: {
    defaultValue: 1.5,
    hidden: false,
    min: 0,
    title: "Width",
    type: ControlType.Number,
  },
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerSupportedLayoutWidth: "any-prefer-fixed",
        framerSupportedLayoutHeight: "any-prefer-fixed",
        framerVector:
          '{"name":"x","color":{"type":"variable","value":"1ueuxnb"},"set":{"localId":"vectorSet/XcHWe4vE5","id":"XcHWe4vE5","moduleId":"4pmxSVQBLYE9vfheas6H"}}',
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "24",
        framerVariables:
          '{"dwH03SpeX":"color","h8kC9jrrV":"fill","o7u3jogiS":"width1"}',
        framerIntrinsicHeight: "24",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
