// Generated by Framer (ff92f61)
import { jsx as _jsx, Fragment as _Fragment } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ChildrenCanSuspend,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  PathVariablesContext,
  ResolveLinks,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useQueryData,
  useRouter,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Categories from "https://framerusercontent.com/modules/Y3RbBCDE2ddoQx43Ly7A/hbhiwig2TFp4fa2PCNFN/ZFPX8XxiR.js";
import InlineLink from "https://framerusercontent.com/modules/M9VmBwq8VB4cCMeKVq7i/UkjWfFvd6xL5tCL0T9au/pRbvwIdk9.js";
const InlineLinkFonts = getFonts(InlineLink);
const cycleOrder = ["BHYk7BWO9", "cgqWksb7P"];
const serializationHash = "framer-lnC8Y";
const variantClassNames = {
  BHYk7BWO9: "framer-v-rk71jm",
  cgqWksb7P: "framer-v-wrthqb",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const nrKGcDENuBHYk7BWO9 = undefined;
const FP3hEwQ6mBHYk7BWO9 = undefined;
const idBHYk7BWO9 = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const query = (prequery) =>
  prequery({
    from: { alias: "BHYk7BWO9", data: Categories, type: "Collection" },
    limit: { type: "LiteralValue", value: 6 },
    select: [
      { collection: "BHYk7BWO9", name: "nrKGcDENu", type: "Identifier" },
      { collection: "BHYk7BWO9", name: "FP3hEwQ6m", type: "Identifier" },
      { collection: "BHYk7BWO9", name: "id", type: "Identifier" },
    ],
    where: {
      left: {
        operator: "not",
        type: "UnaryOperation",
        value: {
          left: {
            collection: "BHYk7BWO9",
            name: "FP3hEwQ6m",
            type: "Identifier",
          },
          operator: "==",
          right: { type: "LiteralValue", value: "All" },
          type: "BinaryOperation",
        },
      },
      operator: "and",
      right: {
        operator: "not",
        type: "UnaryOperation",
        value: {
          left: {
            collection: "BHYk7BWO9",
            name: "OHxAJl7Ml",
            type: "Identifier",
          },
          operator: "==",
          right: { type: "LiteralValue", value: "q2JhScNfN" },
          type: "BinaryOperation",
        },
      },
      type: "BinaryOperation",
    },
  });
const query1 = () => ({
  from: { alias: "BHYk7BWO9", data: Categories, type: "Collection" },
  limit: { type: "LiteralValue", value: 6 },
  select: [
    { collection: "BHYk7BWO9", name: "nrKGcDENu", type: "Identifier" },
    { collection: "BHYk7BWO9", name: "FP3hEwQ6m", type: "Identifier" },
    { collection: "BHYk7BWO9", name: "id", type: "Identifier" },
  ],
  where: {
    left: {
      operator: "not",
      type: "UnaryOperation",
      value: {
        left: {
          collection: "BHYk7BWO9",
          name: "FP3hEwQ6m",
          type: "Identifier",
        },
        operator: "==",
        right: { type: "LiteralValue", value: "All" },
        type: "BinaryOperation",
      },
    },
    operator: "and",
    right: {
      operator: "not",
      type: "UnaryOperation",
      value: {
        left: {
          collection: "BHYk7BWO9",
          name: "OHxAJl7Ml",
          type: "Identifier",
        },
        operator: "==",
        right: { type: "LiteralValue", value: "q2JhScNfN" },
        type: "BinaryOperation",
      },
    },
    type: "BinaryOperation",
  },
});
const query2 = (prequery) =>
  prequery({
    from: { alias: "BHYk7BWO9", data: Categories, type: "Collection" },
    limit: { type: "LiteralValue", value: 6 },
    select: [
      { collection: "BHYk7BWO9", name: "nrKGcDENu", type: "Identifier" },
      { collection: "BHYk7BWO9", name: "FP3hEwQ6m", type: "Identifier" },
      { collection: "BHYk7BWO9", name: "id", type: "Identifier" },
    ],
    where: {
      left: {
        operator: "not",
        type: "UnaryOperation",
        value: {
          left: {
            collection: "BHYk7BWO9",
            name: "FP3hEwQ6m",
            type: "Identifier",
          },
          operator: "==",
          right: { type: "LiteralValue", value: "All" },
          type: "BinaryOperation",
        },
      },
      operator: "and",
      right: {
        operator: "not",
        type: "UnaryOperation",
        value: {
          left: {
            collection: "BHYk7BWO9",
            name: "OHxAJl7Ml",
            type: "Identifier",
          },
          operator: "==",
          right: { type: "LiteralValue", value: "P0GWYFkRN" },
          type: "BinaryOperation",
        },
      },
      type: "BinaryOperation",
    },
  });
const query3 = () => ({
  from: { alias: "BHYk7BWO9", data: Categories, type: "Collection" },
  limit: { type: "LiteralValue", value: 6 },
  select: [
    { collection: "BHYk7BWO9", name: "nrKGcDENu", type: "Identifier" },
    { collection: "BHYk7BWO9", name: "FP3hEwQ6m", type: "Identifier" },
    { collection: "BHYk7BWO9", name: "id", type: "Identifier" },
  ],
  where: {
    left: {
      operator: "not",
      type: "UnaryOperation",
      value: {
        left: {
          collection: "BHYk7BWO9",
          name: "FP3hEwQ6m",
          type: "Identifier",
        },
        operator: "==",
        right: { type: "LiteralValue", value: "All" },
        type: "BinaryOperation",
      },
    },
    operator: "and",
    right: {
      operator: "not",
      type: "UnaryOperation",
      value: {
        left: {
          collection: "BHYk7BWO9",
          name: "OHxAJl7Ml",
          type: "Identifier",
        },
        operator: "==",
        right: { type: "LiteralValue", value: "P0GWYFkRN" },
        type: "BinaryOperation",
      },
    },
    type: "BinaryOperation",
  },
});
const QueryData = ({ query, pageSize, children }) => {
  const data = useQueryData(query);
  return children(data);
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Men: "BHYk7BWO9", Women: "cgqWksb7P" };
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "BHYk7BWO9",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "BHYk7BWO9",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const router = useRouter();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-rk71jm",
            className,
            classNames
          ),
          "data-framer-name": "Men",
          layoutDependency: layoutDependency,
          layoutId: "BHYk7BWO9",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { cgqWksb7P: { "data-framer-name": "Women" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsx(ChildrenCanSuspend, {
            children: /*#__PURE__*/ _jsx(QueryData, {
              query: query1(),
              ...addPropertyOverrides(
                { cgqWksb7P: { query: query3() } },
                baseVariant,
                gestureVariant
              ),
              children: (collection, paginationInfo, loadMore) => {
                return /*#__PURE__*/ _jsx(_Fragment, {
                  children: collection?.map(
                    (
                      {
                        FP3hEwQ6m: FP3hEwQ6mBHYk7BWO9,
                        id: idBHYk7BWO9,
                        nrKGcDENu: nrKGcDENuBHYk7BWO9,
                      },
                      index
                    ) => {
                      nrKGcDENuBHYk7BWO9 ??= "";
                      FP3hEwQ6mBHYk7BWO9 ??= "";
                      return /*#__PURE__*/ _jsx(
                        LayoutGroup,
                        {
                          id: `BHYk7BWO9-${idBHYk7BWO9}`,
                          children: /*#__PURE__*/ _jsx(
                            PathVariablesContext.Provider,
                            {
                              value: { nrKGcDENu: nrKGcDENuBHYk7BWO9 },
                              children: /*#__PURE__*/ _jsx(motion.div, {
                                className: "framer-1q5erf8",
                                layoutDependency: layoutDependency,
                                layoutId: "NYrMJsByx",
                                children: /*#__PURE__*/ _jsx(ResolveLinks, {
                                  links: [
                                    {
                                      href: {
                                        pathVariables: {
                                          nrKGcDENu: nrKGcDENuBHYk7BWO9,
                                        },
                                        webPageId: "WvEH3mXtq",
                                      },
                                      implicitPathVariables: undefined,
                                    },
                                    {
                                      href: {
                                        pathVariables: {
                                          nrKGcDENu: nrKGcDENuBHYk7BWO9,
                                        },
                                        webPageId: "PvmaXeeJb",
                                      },
                                      implicitPathVariables: undefined,
                                    },
                                  ],
                                  children: (resolvedLinks) =>
                                    /*#__PURE__*/ _jsx(
                                      ComponentViewportProvider,
                                      {
                                        height: 23,
                                        y:
                                          (componentViewport?.y || 0) +
                                          0 +
                                          (((componentViewport?.height || 124) -
                                            0 -
                                            23) /
                                            2 +
                                            0 +
                                            0) +
                                          0,
                                        ...addPropertyOverrides(
                                          {
                                            cgqWksb7P: {
                                              y:
                                                (componentViewport?.y || 0) +
                                                0 +
                                                (((componentViewport?.height ||
                                                  157) -
                                                  0 -
                                                  23) /
                                                  2 +
                                                  0 +
                                                  0) +
                                                0,
                                            },
                                          },
                                          baseVariant,
                                          gestureVariant
                                        ),
                                        children: /*#__PURE__*/ _jsx(
                                          SmartComponentScopedContainer,
                                          {
                                            className:
                                              "framer-11geu1d-container",
                                            layoutDependency: layoutDependency,
                                            layoutId: "yLTzbl_lu-container",
                                            nodeId: "yLTzbl_lu",
                                            rendersWithMotion: true,
                                            scopeId: "fqixNbdEi",
                                            children: /*#__PURE__*/ _jsx(
                                              InlineLink,
                                              {
                                                bpLCIIzV1: "rgb(0, 0, 0)",
                                                height: "100%",
                                                id: "yLTzbl_lu",
                                                IVNh0TbCL: "rgb(0, 0, 0)",
                                                layoutId: "yLTzbl_lu",
                                                NOVGXPYPw: 16,
                                                Q5Serm7cH: resolvedLinks[0],
                                                sjXwstpq1: FP3hEwQ6mBHYk7BWO9,
                                                width: "100%",
                                                ZnNj69UmK: "rgb(0, 0, 0)",
                                                ...addPropertyOverrides(
                                                  {
                                                    cgqWksb7P: {
                                                      Q5Serm7cH:
                                                        resolvedLinks[1],
                                                    },
                                                  },
                                                  baseVariant,
                                                  gestureVariant
                                                ),
                                              }
                                            ),
                                          }
                                        ),
                                      }
                                    ),
                                }),
                              }),
                            }
                          ),
                        },
                        idBHYk7BWO9
                      );
                    }
                  ),
                });
              },
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-lnC8Y.framer-10il18u, .framer-lnC8Y .framer-10il18u { display: block; }",
  ".framer-lnC8Y.framer-rk71jm { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: 0px; position: relative; width: min-content; }",
  ".framer-lnC8Y .framer-1q5erf8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: min-content; }",
  ".framer-lnC8Y .framer-11geu1d-container { flex: none; height: auto; position: relative; width: auto; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 124
 * @framerIntrinsicWidth 76
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"cgqWksb7P":{"layout":["auto","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerfqixNbdEi = withCSS(Component, css, "framer-lnC8Y");
export default FramerfqixNbdEi;
FramerfqixNbdEi.displayName = "Categories";
FramerfqixNbdEi.defaultProps = { height: 124, width: 76 };
addPropertyControls(FramerfqixNbdEi, {
  variant: {
    options: ["BHYk7BWO9", "cgqWksb7P"],
    optionTitles: ["Men", "Women"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FramerfqixNbdEi,
  [{ explicitInter: true, fonts: [] }, ...InlineLinkFonts],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerfqixNbdEi",
      slots: [],
      annotations: {
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicWidth: "76",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"cgqWksb7P":{"layout":["auto","auto"]}}}',
        framerColorSyntax: "true",
        framerAutoSizeImages: "true",
        framerIntrinsicHeight: "124",
        framerContractVersion: "1",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
