// Generated by Framer (f4aa214)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  SmartComponentScopedContainer,
  SVG,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import InlineLink from "https://framerusercontent.com/modules/M9VmBwq8VB4cCMeKVq7i/UkjWfFvd6xL5tCL0T9au/pRbvwIdk9.js";
const InlineLinkFonts = getFonts(InlineLink);
const cycleOrder = ["j8ab7mW9G", "EtugmZ2a6"];
const serializationHash = "framer-RbfCD";
const variantClassNames = {
  EtugmZ2a6: "framer-v-k86bx2",
  j8ab7mW9G: "framer-v-8mthkw",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const DpN08GNyK = undefined;
const n8iQmHEnI = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = { Closed: "j8ab7mW9G", Open: "EtugmZ2a6" };
const Variants = motion.create(React.Fragment);
const getProps = ({ click, height, id, shopLink, width, ...props }) => {
  return {
    ...props,
    DpN08GNyK: shopLink ?? props.DpN08GNyK,
    n8iQmHEnI: click ?? props.n8iQmHEnI,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "j8ab7mW9G",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    n8iQmHEnI,
    DpN08GNyK,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "j8ab7mW9G",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const hMrXWD09x6d2jb = activeVariantCallback(async (...args) => {
    if (n8iQmHEnI) {
      const res = await n8iQmHEnI(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-8mthkw",
            className,
            classNames
          ),
          "data-framer-name": "Closed",
          layoutDependency: layoutDependency,
          layoutId: "j8ab7mW9G",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { EtugmZ2a6: { "data-framer-name": "Open" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 23,
              y:
                (componentViewport?.y || 0) +
                (0 + ((componentViewport?.height || 23) - 0 - 23) / 2),
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-urvv16-container",
                layoutDependency: layoutDependency,
                layoutId: "h6FU3JY2F-container",
                nodeId: "h6FU3JY2F",
                rendersWithMotion: true,
                scopeId: "NiqjNQkG7",
                children: /*#__PURE__*/ _jsx(InlineLink, {
                  bpLCIIzV1: "rgb(0, 0, 0)",
                  height: "100%",
                  hMrXWD09x: hMrXWD09x6d2jb,
                  id: "h6FU3JY2F",
                  IVNh0TbCL: "rgb(0, 0, 0)",
                  layoutId: "h6FU3JY2F",
                  NOVGXPYPw: 16,
                  Q5Serm7cH: DpN08GNyK,
                  sjXwstpq1: "Shop",
                  width: "100%",
                  ZnNj69UmK: "rgb(0, 0, 0)",
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(SVG, {
              className: "framer-1assmrt",
              layoutDependency: layoutDependency,
              layoutId: "R4IFFeWFr",
              requiresOverflowVisible: false,
              svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 9.803 5.348" overflow="visible"><path d="M 9.673 0.761 L 5.217 5.217 C 5.133 5.301 5.02 5.348 4.902 5.348 C 4.783 5.348 4.67 5.301 4.586 5.217 L 0.131 0.761 C -0.044 0.587 -0.044 0.305 0.131 0.131 C 0.305 -0.044 0.587 -0.044 0.761 0.131 L 4.902 4.272 L 9.042 0.131 C 9.216 -0.044 9.499 -0.044 9.673 0.131 C 9.847 0.305 9.847 0.587 9.673 0.761 Z" fill="rgb(0,0,0)"></path></svg>',
              variants: { EtugmZ2a6: { rotate: -90 } },
              withExternalLayout: true,
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-RbfCD.framer-7hxumb, .framer-RbfCD .framer-7hxumb { display: block; }",
  ".framer-RbfCD.framer-8mthkw { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-RbfCD .framer-urvv16-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-RbfCD .framer-1assmrt { height: 6px; position: relative; width: 10px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 23
 * @framerIntrinsicWidth 58
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"EtugmZ2a6":{"layout":["auto","auto"]}}}
 * @framerVariables {"n8iQmHEnI":"click","DpN08GNyK":"shopLink"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerNiqjNQkG7 = withCSS(Component, css, "framer-RbfCD");
export default FramerNiqjNQkG7;
FramerNiqjNQkG7.displayName = "Shop Link Chevron";
FramerNiqjNQkG7.defaultProps = { height: 23, width: 58 };
addPropertyControls(FramerNiqjNQkG7, {
  variant: {
    options: ["j8ab7mW9G", "EtugmZ2a6"],
    optionTitles: ["Closed", "Open"],
    title: "Variant",
    type: ControlType.Enum,
  },
  n8iQmHEnI: { title: "Click", type: ControlType.EventHandler },
  DpN08GNyK: { title: "Shop Link", type: ControlType.Link },
});
addFonts(
  FramerNiqjNQkG7,
  [{ explicitInter: true, fonts: [] }, ...InlineLinkFonts],
  { supportsExplicitInterCodegen: true }
);
FramerNiqjNQkG7.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([forwardLoader(InlineLink, {}, context)]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerNiqjNQkG7",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"EtugmZ2a6":{"layout":["auto","auto"]}}}',
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "58",
        framerIntrinsicHeight: "23",
        framerColorSyntax: "true",
        framerVariables: '{"n8iQmHEnI":"click","DpN08GNyK":"shopLink"}',
        framerDisplayContentsDiv: "false",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./NiqjNQkG7.map
