// Generated by Framer (747ab96)
import { jsx as _jsx } from "react/jsx-runtime";
import { cx, motion, withCSS } from "framer";
import * as React from "react";
import { forwardRef } from "react";
const mask = "var(--framer-icon-mask)";
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(motion.img, { ...rest, layoutId: layoutId, ref: ref })
    : /*#__PURE__*/ _jsx("img", { ...rest, ref: ref });
});
const getProps = ({ height, id, width, ...props }) => {
  return { ...props };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    alt: "",
    className: cx("framer-16DU2", className),
    layoutId: layoutId,
    ref: ref,
    src: 'data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 38 24" xmlns="http://www.w3.org/2000/svg"><g opacity="0.07"><path d="M 35 0 L 3 0 C 1.3 0 0 1.3 0 3 L 0 21 C 0 22.7 1.4 24 3 24 L 35 24 C 36.7 24 38 22.7 38 21 L 38 3 C 38 1.3 36.6 0 35 0 Z" fill="rgb(0, 0, 0)" height="24px" id="jlTMZnL1S" width="38px"/></g><path d="M 34 0 C 35.1 0 36 0.9 36 2 L 36 20 C 36 21.1 35.1 22 34 22 L 2 22 C 0.9 22 0 21.1 0 20 L 0 2 C 0 0.9 0.9 0 2 0 L 34 0" fill="rgb(255, 255, 255)" height="22px" id="KXDX_56J6" transform="translate(1 1)" width="36px"/><path d="M 0 7 C 0 3.134 3.134 0 7 0 C 10.866 0 14 3.134 14 7 C 14 10.866 10.866 14 7 14 C 3.134 14 0 10.866 0 7 Z" fill="rgb(235, 0, 27)" height="14px" id="LGifILjXv" transform="translate(8 5)" width="14px"/><path d="M 0 7 C 0 3.134 3.134 0 7 0 C 10.866 0 14 3.134 14 7 C 14 10.866 10.866 14 7 14 C 3.134 14 0 10.866 0 7 Z" fill="rgb(247, 158, 27)" height="14px" id="I2CqpYss1" transform="translate(16 5)" width="14px"/><path d="M 6 5.7 C 6 3.3 4.8 1.2 3 0 C 1.2 1.3 0 3.4 0 5.7 C 0 8 1.2 10.2 3 11.4 C 4.8 10.2 6 8.1 6 5.7 Z" fill="rgb(255, 95, 0)" height="11.399999999999999px" id="gM0BW9so8" transform="translate(16 6.3)" width="6px"/></svg>',
    style: { ...style },
  });
});
const css = [
  `.framer-16DU2 { -webkit-mask: ${mask}; aspect-ratio: 1.5833333333333333; display: block; mask: ${mask}; user-select: none; width: 38px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 38
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerImmutableVariables true
 * @framerVector {"name":"mc","set":{"localId":"vectorSet/EU0Y7lcpY","id":"EU0Y7lcpY","moduleId":"Vx2HlScoCf6t65s2Lmbs"}}
 */ const Icon = withCSS(Component, css, "framer-16DU2");
Icon.displayName = "mc";
export default Icon;
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerVector:
          '{"name":"mc","set":{"localId":"vectorSet/EU0Y7lcpY","id":"EU0Y7lcpY","moduleId":"Vx2HlScoCf6t65s2Lmbs"}}',
        framerIntrinsicWidth: "38",
        framerSupportedLayoutWidth: "any-prefer-fixed",
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "24",
        framerContractVersion: "1",
        framerSupportedLayoutHeight: "any-prefer-fixed",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
