// Generated by Framer (29c58de)
import {
  addPropertyControls as e,
  ControlType as t,
  QueryEngine as l,
} from "framer";
import {
  DatabaseCollection as r,
  DatabaseDictionaryIndex as a,
} from "./edfsEwdcW-0.js";
import { getRichTextJsonResolver as i } from "./edfsEwdcW-1.js";
let o = {
    createdAt: { isNullable: !0, type: t.Date },
    G2Q9rrLi4: { isNullable: !0, type: t.ResponsiveImage },
    GjRKzFr00: { isNullable: !0, type: t.Enum },
    id: { isNullable: !1, type: t.String },
    nextItemId: { isNullable: !0, type: t.String },
    previousItemId: { isNullable: !0, type: t.String },
    Tye02Iiu2: { isNullable: !0, type: t.String },
    updatedAt: { isNullable: !0, type: t.Date },
    xXJIgAYfG: { isNullable: !0, type: t.String },
  },
  n = ["id"],
  m = { type: 1 },
  c = ["previousItemId"],
  d = ["nextItemId"],
  f = ["id", "xXJIgAYfG"],
  s = ["xXJIgAYfG", "id"],
  u = ["Tye02Iiu2"],
  p = { type: 0 },
  y = ["xXJIgAYfG"],
  w = ["G2Q9rrLi4"],
  g = ["GjRKzFr00"],
  I = [],
  h = (e) => {
    let t = I[e];
    if (t) return t().then((e) => e.default);
  },
  x = {},
  S = i(x),
  R = new l(),
  N = {
    collectionByLocaleId: {
      default: new r({
        chunks: [
          new URL(
            "./edfsEwdcW-chunk-default-0.framercms",
            "https://framerusercontent.com/modules/yeuWn7ZuERqDeAf0QqCg/MvOqURdsiCIPTK6a22Qc/edfsEwdcW.js"
          ).href.replace("/modules/", "/cms/"),
        ],
        id: "55ac4bc5-4e7b-46a3-b7a0-6a1f0a7c8375default",
        indexes: [
          new a({
            collation: m,
            collectionSchema: o,
            fieldNames: n,
            range: { from: 0, to: 265 },
            url: new URL(
              "./edfsEwdcW-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/yeuWn7ZuERqDeAf0QqCg/MvOqURdsiCIPTK6a22Qc/edfsEwdcW.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new a({
            collation: m,
            collectionSchema: o,
            fieldNames: c,
            range: { from: 265, to: 529 },
            url: new URL(
              "./edfsEwdcW-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/yeuWn7ZuERqDeAf0QqCg/MvOqURdsiCIPTK6a22Qc/edfsEwdcW.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new a({
            collation: m,
            collectionSchema: o,
            fieldNames: d,
            range: { from: 529, to: 789 },
            url: new URL(
              "./edfsEwdcW-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/yeuWn7ZuERqDeAf0QqCg/MvOqURdsiCIPTK6a22Qc/edfsEwdcW.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new a({
            collation: m,
            collectionSchema: o,
            fieldNames: f,
            range: { from: 789, to: 1159 },
            url: new URL(
              "./edfsEwdcW-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/yeuWn7ZuERqDeAf0QqCg/MvOqURdsiCIPTK6a22Qc/edfsEwdcW.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new a({
            collation: m,
            collectionSchema: o,
            fieldNames: s,
            range: { from: 1159, to: 1529 },
            url: new URL(
              "./edfsEwdcW-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/yeuWn7ZuERqDeAf0QqCg/MvOqURdsiCIPTK6a22Qc/edfsEwdcW.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new a({
            collation: p,
            collectionSchema: o,
            fieldNames: u,
            range: { from: 1529, to: 1763 },
            url: new URL(
              "./edfsEwdcW-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/yeuWn7ZuERqDeAf0QqCg/MvOqURdsiCIPTK6a22Qc/edfsEwdcW.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new a({
            collation: p,
            collectionSchema: o,
            fieldNames: y,
            range: { from: 1763, to: 1987 },
            url: new URL(
              "./edfsEwdcW-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/yeuWn7ZuERqDeAf0QqCg/MvOqURdsiCIPTK6a22Qc/edfsEwdcW.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new a({
            collation: p,
            collectionSchema: o,
            fieldNames: w,
            range: { from: 1987, to: 6241 },
            url: new URL(
              "./edfsEwdcW-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/yeuWn7ZuERqDeAf0QqCg/MvOqURdsiCIPTK6a22Qc/edfsEwdcW.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new a({
            collation: p,
            collectionSchema: o,
            fieldNames: g,
            range: { from: 6241, to: 6513 },
            url: new URL(
              "./edfsEwdcW-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/yeuWn7ZuERqDeAf0QqCg/MvOqURdsiCIPTK6a22Qc/edfsEwdcW.js"
            ).href.replace("/modules/", "/cms/"),
          }),
        ],
        resolveRichText: S,
        resolveVectorSetItem: h,
        schema: o,
      }),
    },
    displayName: "Community",
    id: "55ac4bc5-4e7b-46a3-b7a0-6a1f0a7c8375",
  };
export default N;
e(N, {
  Tye02Iiu2: {
    defaultValue: "",
    preventLocalization: !0,
    title: "Profile",
    type: t.String,
  },
  xXJIgAYfG: { preventLocalization: !1, title: "Slug", type: t.String },
  G2Q9rrLi4: {
    __defaultAssetReference:
      "data:framer/asset-reference,4VTeFe0CvjDDqn2XgRLlh7g3ADo.jpg?originalFilename=3729115dd1248b13aeebc2d254436cfc.jpg&width=1080&height=1349",
    title: "Image",
    type: t.ResponsiveImage,
  },
  GjRKzFr00: {
    defaultValue: "SSFEDnX92",
    options: ["SSFEDnX92", "MxvUJrqVQ"],
    optionTitles: ["Men", "Women"],
    title: "Shop",
    type: t.Enum,
  },
  createdAt: { title: "Created", type: t.Date },
  updatedAt: { title: "Updated", type: t.Date },
  previousItemId: {
    dataIdentifier: "local-module:collection/edfsEwdcW:default",
    title: "Previous",
    type: t.CollectionReference,
  },
  nextItemId: {
    dataIdentifier: "local-module:collection/edfsEwdcW:default",
    title: "Next",
    type: t.CollectionReference,
  },
});
export const GjRKzFr00ToDisplayName = (e, t) => {
  switch ((t?.fallback, e)) {
    case "SSFEDnX92":
      return "Men";
    case "MxvUJrqVQ":
      return "Women";
    default:
      return "";
  }
};
export const enumToDisplayNameFunctions = { GjRKzFr00: GjRKzFr00ToDisplayName };
export const utils = {
  async getSlugByRecordId(e, t) {
    let [l] = await R.query(
      {
        from: { data: N, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "xXJIgAYfG", type: "Identifier" }],
        where: {
          left: { name: "id", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      t
    );
    return l?.xXJIgAYfG;
  },
  async getRecordIdBySlug(e, t) {
    let [l] = await R.query(
      {
        from: { data: N, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "id", type: "Identifier" }],
        where: {
          left: { name: "xXJIgAYfG", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      t
    );
    return l?.id;
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "data",
      name: "data",
      annotations: {
        framerEnumToDisplayNameUtils: "2",
        framerCollectionUtils: "1",
        framerCollectionId: "edfsEwdcW",
        framerContractVersion: "1",
        framerSlug: "xXJIgAYfG",
        framerData: "true",
        framerRecordIdKey: "id",
        framerColorSyntax: "false",
        framerAutoSizeImages: "true",
      },
    },
    utils: { type: "variable", annotations: { framerContractVersion: "1" } },
    enumToDisplayNameFunctions: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    GjRKzFr00ToDisplayName: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
