// Generated by Framer (cc3b8f8)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  Image,
  Link,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = [
  "i_TI_yYeq",
  "HmE2T5TEJ",
  "FNRWd0oaj",
  "xlpdMp8Vc",
  "xsejMuFlC",
];
const serializationHash = "framer-Rf4rq";
const variantClassNames = {
  FNRWd0oaj: "framer-v-1wq4xe4",
  HmE2T5TEJ: "framer-v-8syhec",
  i_TI_yYeq: "framer-v-1hzj4gu",
  xlpdMp8Vc: "framer-v-md87yf",
  xsejMuFlC: "framer-v-4v1aw7",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const UdwOBeoEW = undefined;
const L50124giC = undefined;
const TCXN5zxa5 = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  ImgSwap: "i_TI_yYeq",
  ImgSwapHover: "HmE2T5TEJ",
  ImgZoom: "FNRWd0oaj",
  ImgZoomHover: "xlpdMp8Vc",
  phone: "xsejMuFlC",
};
const getProps = ({ height, id, image1, image2, link, width, ...props }) => {
  return {
    ...props,
    L50124giC: image2 ?? props.L50124giC,
    TCXN5zxa5: image1 ?? props.TCXN5zxa5,
    UdwOBeoEW: link ?? props.UdwOBeoEW,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "i_TI_yYeq",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    TCXN5zxa5,
    L50124giC,
    UdwOBeoEW,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "i_TI_yYeq",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onMouseEnter112vqzw = activeVariantCallback(async (...args) => {
    setVariant("HmE2T5TEJ");
  });
  const onMouseLeavek0ff4q = activeVariantCallback(async (...args) => {
    setVariant("i_TI_yYeq");
  });
  const onMouseEnterm7qrtc = activeVariantCallback(async (...args) => {
    setVariant("xlpdMp8Vc");
  });
  const onMouseLeave1sn7fi9 = activeVariantCallback(async (...args) => {
    setVariant("FNRWd0oaj");
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (["FNRWd0oaj", "xlpdMp8Vc"].includes(baseVariant)) return false;
    return true;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1hzj4gu",
            className,
            classNames
          ),
          "data-framer-name": "ImgSwap",
          layoutDependency: layoutDependency,
          layoutId: "i_TI_yYeq",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              FNRWd0oaj: { "data-framer-name": "ImgZoom" },
              HmE2T5TEJ: { "data-framer-name": "ImgSwapHover" },
              xlpdMp8Vc: { "data-framer-name": "ImgZoomHover" },
              xsejMuFlC: { "data-framer-name": "phone" },
            },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsx(Link, {
            href: UdwOBeoEW,
            motionChild: true,
            nodeId: "BcZ5G03gL",
            openInNewTab: false,
            scopeId: "LKHrqm3yh",
            children: /*#__PURE__*/ _jsx(motion.a, {
              className: "framer-wvgpw6 framer-1ig7adv",
              "data-framer-name": "product",
              "data-highlight": true,
              layoutDependency: layoutDependency,
              layoutId: "BcZ5G03gL",
              onMouseEnter: onMouseEnter112vqzw,
              onMouseLeave: onMouseLeavek0ff4q,
              ...addPropertyOverrides(
                {
                  FNRWd0oaj: {
                    onMouseEnter: onMouseEnterm7qrtc,
                    onMouseLeave: onMouseLeave1sn7fi9,
                  },
                  xlpdMp8Vc: {
                    onMouseEnter: onMouseEnterm7qrtc,
                    onMouseLeave: onMouseLeave1sn7fi9,
                  },
                  xsejMuFlC: {
                    "data-highlight": undefined,
                    onMouseEnter: undefined,
                    onMouseLeave: undefined,
                  },
                },
                baseVariant,
                gestureVariant
              ),
              children: /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-1t9oglk",
                "data-framer-name": "img",
                layoutDependency: layoutDependency,
                layoutId: "Jda6frGQ2",
                style: {
                  backgroundColor:
                    "var(--token-977611e6-b9d8-4d09-809b-8b874fb3d33d, rgb(235, 235, 230))",
                  borderBottomLeftRadius: 8,
                  borderBottomRightRadius: 8,
                  borderTopLeftRadius: 8,
                  borderTopRightRadius: 8,
                },
                children: [
                  /*#__PURE__*/ _jsx(Image, {
                    background: {
                      alt: "",
                      fit: "fill",
                      sizes: componentViewport?.width || "100vw",
                      ...toResponsiveImage(L50124giC),
                      ...{ positionX: "center", positionY: "top" },
                    },
                    className: "framer-106zry6",
                    "data-framer-name": "img-hover",
                    layoutDependency: layoutDependency,
                    layoutId: "IWuQuPHIQ",
                    style: { opacity: 0 },
                  }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(Image, {
                      background: {
                        alt: "",
                        fit: "fill",
                        sizes: componentViewport?.width || "100vw",
                        ...toResponsiveImage(L50124giC),
                        ...{ positionX: "center", positionY: "top" },
                      },
                      className: "framer-r6bla4",
                      "data-framer-name": "img-secondary",
                      layoutDependency: layoutDependency,
                      layoutId: "VM9q2Hk_z",
                      style: { opacity: 0 },
                      variants: { HmE2T5TEJ: { opacity: 1 } },
                    }),
                  /*#__PURE__*/ _jsx(Image, {
                    background: {
                      alt: "",
                      fit: "fill",
                      sizes: componentViewport?.width || "100vw",
                      ...toResponsiveImage(TCXN5zxa5),
                      ...{ positionX: "center", positionY: "top" },
                    },
                    className: "framer-1kthfw6",
                    "data-framer-name": "img-primary",
                    layoutDependency: layoutDependency,
                    layoutId: "ytjyJlASD",
                    style: { opacity: 1 },
                    variants: {
                      FNRWd0oaj: { opacity: 1 },
                      HmE2T5TEJ: { opacity: 0 },
                      xlpdMp8Vc: { opacity: 1 },
                      xsejMuFlC: { opacity: 1 },
                    },
                    ...addPropertyOverrides(
                      {
                        xlpdMp8Vc: {
                          background: {
                            alt: "",
                            fit: "fill",
                            sizes: `calc(${
                              componentViewport?.width || "100vw"
                            } * 1.1)`,
                            ...toResponsiveImage(TCXN5zxa5),
                            ...{ positionX: "center", positionY: "top" },
                          },
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                ],
              }),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-Rf4rq.framer-1ig7adv, .framer-Rf4rq .framer-1ig7adv { display: block; }",
  ".framer-Rf4rq.framer-1hzj4gu { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: wrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 96px; }",
  ".framer-Rf4rq .framer-wvgpw6 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 1px; }",
  ".framer-Rf4rq .framer-1t9oglk { aspect-ratio: 0.8 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 250px); overflow: hidden; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
  ".framer-Rf4rq .framer-106zry6 { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; will-change: var(--framer-will-change-filter-override, filter); z-index: 1; }",
  ".framer-Rf4rq .framer-r6bla4 { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; position: absolute; top: 0px; width: 100%; will-change: var(--framer-will-change-filter-override, filter); z-index: 2; }",
  ".framer-Rf4rq .framer-1kthfw6 { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; will-change: var(--framer-will-change-filter-override, filter); z-index: 2; }",
  ".framer-Rf4rq.framer-v-md87yf .framer-1kthfw6 { height: 110%; left: calc(50.00000000000002% - 110.00000000000001% / 2); top: calc(50.00000000000002% - 110.00000000000001% / 2); width: 110%; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 120
 * @framerIntrinsicWidth 96
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"HmE2T5TEJ":{"layout":["fixed","auto"]},"FNRWd0oaj":{"layout":["fixed","auto"]},"xlpdMp8Vc":{"layout":["fixed","auto"]},"xsejMuFlC":{"layout":["fixed","auto"]}}}
 * @framerVariables {"TCXN5zxa5":"image1","L50124giC":"image2","UdwOBeoEW":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerLKHrqm3yh = withCSS(Component, css, "framer-Rf4rq");
export default FramerLKHrqm3yh;
FramerLKHrqm3yh.displayName = "CartProductCard";
FramerLKHrqm3yh.defaultProps = { height: 120, width: 96 };
addPropertyControls(FramerLKHrqm3yh, {
  variant: {
    options: ["i_TI_yYeq", "HmE2T5TEJ", "FNRWd0oaj", "xlpdMp8Vc", "xsejMuFlC"],
    optionTitles: [
      "ImgSwap",
      "ImgSwapHover",
      "ImgZoom",
      "ImgZoomHover",
      "phone",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
  TCXN5zxa5: { title: "Image 1", type: ControlType.ResponsiveImage },
  L50124giC: { title: "Image 2", type: ControlType.ResponsiveImage },
  UdwOBeoEW: { title: "Link", type: ControlType.Link },
});
addFonts(FramerLKHrqm3yh, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerLKHrqm3yh",
      slots: [],
      annotations: {
        framerVariables:
          '{"TCXN5zxa5":"image1","L50124giC":"image2","UdwOBeoEW":"link"}',
        framerImmutableVariables: "true",
        framerContractVersion: "1",
        framerIntrinsicWidth: "96",
        framerAutoSizeImages: "true",
        framerColorSyntax: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"HmE2T5TEJ":{"layout":["fixed","auto"]},"FNRWd0oaj":{"layout":["fixed","auto"]},"xlpdMp8Vc":{"layout":["fixed","auto"]},"xsejMuFlC":{"layout":["fixed","auto"]}}}',
        framerIntrinsicHeight: "120",
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./LKHrqm3yh.map
