// Generated by Framer (f4aa214)
import {
  jsx as _jsx,
  jsxs as _jsxs,
  Fragment as _Fragment,
} from "react/jsx-runtime";
import {
  addFonts,
  ChildrenCanSuspend,
  ComponentViewportProvider,
  Container,
  cx,
  forwardLoader,
  GeneratedComponentContext,
  getFonts,
  getFontsFromSharedStyle,
  PathVariablesContext,
  PropertyOverrides,
  queryCache,
  ResolveLinks,
  RichText,
  TickerItem,
  useComponentViewport,
  useCustomCursors,
  useHydratedBreakpointVariants,
  useIsOnFramerCanvas,
  useLocaleInfo,
  useMetadata,
  useQueryData,
  useRouteElementId,
  useRouter,
  withCSS,
  withFlowFX,
  withFX,
  withTickerFX,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import CommunityCalloutCard from "#framer/local/canvasComponent/aWbvvkh40/aWbvvkh40.js";
import ProductCard from "#framer/local/canvasComponent/I8MkpPi9k/I8MkpPi9k.js";
import About from "#framer/local/canvasComponent/lgKWiyqh1/lgKWiyqh1.js";
import InlineLink from "#framer/local/canvasComponent/pRbvwIdk9/pRbvwIdk9.js";
import HeroSection from "#framer/local/canvasComponent/TIZD3Dmua/TIZD3Dmua.js";
import ShopCategoryContainer from "#framer/local/canvasComponent/WwVCraiqw/WwVCraiqw.js";
import CategoryCard from "#framer/local/canvasComponent/xlqNBHkfa/xlqNBHkfa.js";
import Community from "#framer/local/collection/edfsEwdcW/edfsEwdcW.js";
import FramerCommerce from "#framer/local/collection/Gk472MYtJ/Gk472MYtJ.js";
import * as sharedStyle from "#framer/local/css/fvwhVXh4s/fvwhVXh4s.js";
import * as sharedStyle1 from "#framer/local/css/ickuMUi8E/ickuMUi8E.js";
import metadataProvider from "#framer/local/webPageMetadata/OxIsxzOms/OxIsxzOms.js";
const HeroSectionFonts = getFonts(HeroSection);
const AboutFonts = getFonts(About);
const ShopCategoryContainerFonts = getFonts(ShopCategoryContainer);
const InlineLinkFonts = getFonts(InlineLink);
const ProductCardFonts = getFonts(ProductCard);
const CategoryCardFonts = getFonts(CategoryCard);
const ContainerWithFX = withFX(Container);
const MotionDivWithTickerFX = withTickerFX(motion.div);
const CommunityCalloutCardFonts = getFonts(CommunityCalloutCard);
const MotionDivWithFlowFX = withFlowFX(motion.div);
const breakpoints = {
  P2i7N7OFA: "(min-width: 1200px)",
  QRYvcRjNm: "(max-width: 809.98px)",
  tI2pZQrBZ: "(min-width: 810px) and (max-width: 1199.98px)",
};
const isBrowser = () => typeof document !== "undefined";
export const queryParamNames = [];
const serializationHash = "framer-fdiDZ";
const variantClassNames = {
  P2i7N7OFA: "framer-v-ptlv6u",
  QRYvcRjNm: "framer-v-qco1y4",
  tI2pZQrBZ: "framer-v-50k0no",
};
const RMwVI8LUMr_Qhc4yP8 = undefined;
const UKXz5hUjDr_Qhc4yP8 = undefined;
const tZaiMnhUsr_Qhc4yP8 = undefined;
const NPclJ_YtQr_Qhc4yP8 = undefined;
const mcwXYk3GKr_Qhc4yP8 = undefined;
const XnegVJs7wr_Qhc4yP8 = undefined;
const AHNguEn6Hr_Qhc4yP8 = undefined;
const oWUHQkhzXr_Qhc4yP8 = undefined;
const jQHMHfZ0Gr_Qhc4yP8 = undefined;
const hNvG3yjWhr_Qhc4yP8 = undefined;
const wqm7rDVcPr_Qhc4yP8 = undefined;
const ixptKemFcr_Qhc4yP8 = undefined;
const idr_Qhc4yP8 = undefined;
const RMwVI8LUMx_rqD9ujC = undefined;
const UKXz5hUjDx_rqD9ujC = undefined;
const tZaiMnhUsx_rqD9ujC = undefined;
const NPclJ_YtQx_rqD9ujC = undefined;
const mcwXYk3GKx_rqD9ujC = undefined;
const XnegVJs7wx_rqD9ujC = undefined;
const AHNguEn6Hx_rqD9ujC = undefined;
const oWUHQkhzXx_rqD9ujC = undefined;
const jQHMHfZ0Gx_rqD9ujC = undefined;
const hNvG3yjWhx_rqD9ujC = undefined;
const wqm7rDVcPx_rqD9ujC = undefined;
const ixptKemFcx_rqD9ujC = undefined;
const idx_rqD9ujC = undefined;
const G2Q9rrLi4VNwBRIc4W = undefined;
const Tye02Iiu2VNwBRIc4W = undefined;
const xXJIgAYfGVNwBRIc4W = undefined;
const idVNwBRIc4W = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.3, type: "spring" };
const getRootLayoutProp = (
  hasLayoutTemplate,
  hasInheritedFlowEffect,
  fallback
) => {
  if (!hasLayoutTemplate) return fallback;
  return hasInheritedFlowEffect ? "position" : fallback;
};
const addImageAlt = (image, alt) => {
  if (!image || typeof image !== "object") {
    return;
  }
  return { ...image, alt };
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const query = () => ({
  from: { alias: "r_Qhc4yP8", data: FramerCommerce, type: "Collection" },
  limit: { type: "LiteralValue", value: 4 },
  orderBy: [{ collection: "r_Qhc4yP8", name: "RMwVI8LUM", type: "Identifier" }],
  select: [
    { collection: "r_Qhc4yP8", name: "RMwVI8LUM", type: "Identifier" },
    { collection: "r_Qhc4yP8", name: "UKXz5hUjD", type: "Identifier" },
    { collection: "r_Qhc4yP8", name: "tZaiMnhUs", type: "Identifier" },
    { collection: "r_Qhc4yP8", name: "NPclJ_YtQ", type: "Identifier" },
    { collection: "r_Qhc4yP8", name: "mcwXYk3GK", type: "Identifier" },
    { collection: "r_Qhc4yP8", name: "XnegVJs7w", type: "Identifier" },
    { collection: "r_Qhc4yP8", name: "AHNguEn6H", type: "Identifier" },
    { collection: "r_Qhc4yP8", name: "oWUHQkhzX", type: "Identifier" },
    { collection: "r_Qhc4yP8", name: "jQHMHfZ0G", type: "Identifier" },
    { collection: "r_Qhc4yP8", name: "hNvG3yjWh", type: "Identifier" },
    { collection: "r_Qhc4yP8", name: "wqm7rDVcP", type: "Identifier" },
    { collection: "r_Qhc4yP8", name: "ixptKemFc", type: "Identifier" },
    { collection: "r_Qhc4yP8", name: "id", type: "Identifier" },
  ],
});
const QueryData = ({ query, pageSize, children }) => {
  const data = useQueryData(query);
  return children(data);
};
const query1 = () => ({
  from: { alias: "x_rqD9ujC", data: FramerCommerce, type: "Collection" },
  limit: { type: "LiteralValue", value: 4 },
  orderBy: [
    {
      collection: "x_rqD9ujC",
      direction: "desc",
      name: "RMwVI8LUM",
      type: "Identifier",
    },
  ],
  select: [
    { collection: "x_rqD9ujC", name: "RMwVI8LUM", type: "Identifier" },
    { collection: "x_rqD9ujC", name: "UKXz5hUjD", type: "Identifier" },
    { collection: "x_rqD9ujC", name: "tZaiMnhUs", type: "Identifier" },
    { collection: "x_rqD9ujC", name: "NPclJ_YtQ", type: "Identifier" },
    { collection: "x_rqD9ujC", name: "mcwXYk3GK", type: "Identifier" },
    { collection: "x_rqD9ujC", name: "XnegVJs7w", type: "Identifier" },
    { collection: "x_rqD9ujC", name: "AHNguEn6H", type: "Identifier" },
    { collection: "x_rqD9ujC", name: "oWUHQkhzX", type: "Identifier" },
    { collection: "x_rqD9ujC", name: "jQHMHfZ0G", type: "Identifier" },
    { collection: "x_rqD9ujC", name: "hNvG3yjWh", type: "Identifier" },
    { collection: "x_rqD9ujC", name: "wqm7rDVcP", type: "Identifier" },
    { collection: "x_rqD9ujC", name: "ixptKemFc", type: "Identifier" },
    { collection: "x_rqD9ujC", name: "id", type: "Identifier" },
  ],
});
const animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 0.9,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const transition2 = {
  delay: 0.1,
  duration: 0.4,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const stagger = (transition, value) => ({
  ...transition,
  delay: (transition.delay ?? 0) + value,
});
const query2 = () => ({
  from: { alias: "VNwBRIc4W", data: Community, type: "Collection" },
  limit: { type: "LiteralValue", value: 10 },
  orderBy: [
    {
      collection: "VNwBRIc4W",
      direction: "desc",
      name: "Tye02Iiu2",
      type: "Identifier",
    },
  ],
  select: [
    { collection: "VNwBRIc4W", name: "G2Q9rrLi4", type: "Identifier" },
    { collection: "VNwBRIc4W", name: "Tye02Iiu2", type: "Identifier" },
    { collection: "VNwBRIc4W", name: "xXJIgAYfG", type: "Identifier" },
    { collection: "VNwBRIc4W", name: "id", type: "Identifier" },
  ],
});
const animation1 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const transition3 = { bounce: 0.4, delay: 0.2, duration: 0.8, type: "spring" };
const humanReadableVariantMap = {
  Desktop: "P2i7N7OFA",
  Phone: "QRYvcRjNm",
  Tablet: "tI2pZQrBZ",
};
const HTMLStyle = ({ value }) => {
  const onCanvas = useIsOnFramerCanvas();
  if (onCanvas) return null;
  return /*#__PURE__*/ _jsx("style", {
    dangerouslySetInnerHTML: { __html: value },
    "data-framer-html-style": "",
  });
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "P2i7N7OFA",
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const metadata = React.useMemo(
    () => metadataProvider({}, activeLocale),
    [activeLocale]
  );
  useMetadata(metadata);
  const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(
    variant,
    breakpoints,
    false
  );
  const gestureVariant = undefined;
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const hasLayoutTemplate = React.useContext(
    GeneratedComponentContext
  )?.isLayoutTemplate;
  const hasInheritedFlowEffect = Boolean(
    React.useContext(MotionConfigContext)?.transition?.layout
  );
  const motionLayout = getRootLayoutProp(
    hasLayoutTemplate,
    hasInheritedFlowEffect,
    "position"
  );
  const router = useRouter();
  const elementId = useRouteElementId("mM7IKKtNV");
  const ref1 = React.useRef(null);
  useCustomCursors({});
  return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
    value: {
      activeVariantId: baseVariant,
      humanReadableVariantMap,
      primaryVariantId: "P2i7N7OFA",
      variantClassNames,
    },
    children: /*#__PURE__*/ _jsxs(LayoutGroup, {
      id: layoutId ?? defaultLayoutId,
      children: [
        /*#__PURE__*/ _jsx(HTMLStyle, {
          value:
            "html body { background: var(--token-a1d66695-261b-4112-b609-9b6c0fb55851, rgb(255, 255, 255)); }",
        }),
        /*#__PURE__*/ _jsxs(MotionDivWithFlowFX, {
          ...restProps,
          className: cx(scopingClassNames, "framer-ptlv6u", className),
          flowEffectEnabled: true,
          flowEffectTransition: transition1,
          isNestedFlowEffect: false,
          ref: refBinding,
          style: { ...style },
          children: [
            /*#__PURE__*/ _jsx(motion.section, {
              className: "framer-n8yxu9",
              "data-framer-name": "Hero",
              layout: motionLayout,
              children: /*#__PURE__*/ _jsx(ResolveLinks, {
                links: [
                  {
                    href: {
                      pathVariables: { nrKGcDENu: "all" },
                      unresolvedPathSlugs: {
                        nrKGcDENu: {
                          collectionId: "ZFPX8XxiR",
                          collectionItemId: "Ybq0oXQi0",
                        },
                      },
                      webPageId: "WvEH3mXtq",
                    },
                    implicitPathVariables: undefined,
                  },
                  {
                    href: {
                      pathVariables: { nrKGcDENu: "all" },
                      unresolvedPathSlugs: {
                        nrKGcDENu: {
                          collectionId: "ZFPX8XxiR",
                          collectionItemId: "Ybq0oXQi0",
                        },
                      },
                      webPageId: "WvEH3mXtq",
                    },
                    implicitPathVariables: undefined,
                  },
                  {
                    href: {
                      pathVariables: { nrKGcDENu: "all" },
                      unresolvedPathSlugs: {
                        nrKGcDENu: {
                          collectionId: "ZFPX8XxiR",
                          collectionItemId: "Ybq0oXQi0",
                        },
                      },
                      webPageId: "WvEH3mXtq",
                    },
                    implicitPathVariables: undefined,
                  },
                ],
                children: (resolvedLinks) =>
                  /*#__PURE__*/ _jsx(PropertyOverrides, {
                    breakpoint: baseVariant,
                    overrides: {
                      QRYvcRjNm: {
                        width: `min(max(${
                          componentViewport?.width || "100vw"
                        } - 20px, 1px), 1500px)`,
                        y: (componentViewport?.y || 0) + 0 + 0 + 0,
                      },
                    },
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 880,
                      width: `min(max(${
                        componentViewport?.width || "100vw"
                      } - 40px, 1px), 1500px)`,
                      children: /*#__PURE__*/ _jsx(Container, {
                        className: "framer-1fo8yy8-container",
                        nodeId: "oplrQ0Ly7",
                        scopeId: "OxIsxzOms",
                        children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                          breakpoint: baseVariant,
                          overrides: {
                            QRYvcRjNm: {
                              aV5leFCgU: addImageAlt(
                                {
                                  pixelHeight: 3920,
                                  pixelWidth: 7680,
                                  positionX: "87.9%",
                                  positionY: "52.2%",
                                  src: "https://framerusercontent.com/images/iQAL5UIxExPNLNZ0iduaGediZGE.jpg?width=7680&height=3920",
                                  srcSet:
                                    "https://framerusercontent.com/images/iQAL5UIxExPNLNZ0iduaGediZGE.jpg?scale-down-to=512&width=7680&height=3920 512w,https://framerusercontent.com/images/iQAL5UIxExPNLNZ0iduaGediZGE.jpg?scale-down-to=1024&width=7680&height=3920 1024w,https://framerusercontent.com/images/iQAL5UIxExPNLNZ0iduaGediZGE.jpg?scale-down-to=2048&width=7680&height=3920 2048w,https://framerusercontent.com/images/iQAL5UIxExPNLNZ0iduaGediZGE.jpg?scale-down-to=4096&width=7680&height=3920 4096w,https://framerusercontent.com/images/iQAL5UIxExPNLNZ0iduaGediZGE.jpg?width=7680&height=3920 7680w",
                                },
                                ""
                              ),
                              oYVtmVQc7: resolvedLinks[2],
                              variant: matchVariant("FCg7tKWB8"),
                            },
                            tI2pZQrBZ: {
                              oYVtmVQc7: resolvedLinks[1],
                              variant: matchVariant("LXWMKDaWo"),
                            },
                          },
                          children: /*#__PURE__*/ _jsx(HeroSection, {
                            aV5leFCgU: addImageAlt(
                              {
                                pixelHeight: 1045,
                                pixelWidth: 2048,
                                src: "https://framerusercontent.com/images/6ntzLRSIKH0AxaUbKo0QI0SIM.webp?width=2048&height=1045",
                                srcSet:
                                  "https://framerusercontent.com/images/6ntzLRSIKH0AxaUbKo0QI0SIM.webp?scale-down-to=512&width=2048&height=1045 512w,https://framerusercontent.com/images/6ntzLRSIKH0AxaUbKo0QI0SIM.webp?scale-down-to=1024&width=2048&height=1045 1024w,https://framerusercontent.com/images/6ntzLRSIKH0AxaUbKo0QI0SIM.webp?width=2048&height=1045 2048w",
                              },
                              "Male model in a gray hoodie, posing casually."
                            ),
                            chsYNoXa1: true,
                            CL3qbw_yA: "esOdew2Ux",
                            DSpIx2khZ: "Wear Better for Less",
                            goZSwjip6: "Wear with elegance built for the bold",
                            height: "100%",
                            id: "oplrQ0Ly7",
                            layoutId: "oplrQ0Ly7",
                            oYVtmVQc7: resolvedLinks[0],
                            rahElhIZb: "Shop now",
                            style: {
                              height: "100%",
                              maxWidth: "100%",
                              width: "100%",
                            },
                            tbwQDnYS3: true,
                            variant: matchVariant("n3_s9er9E"),
                            width: "100%",
                          }),
                        }),
                      }),
                    }),
                  }),
              }),
            }),
            /*#__PURE__*/ _jsx(motion.section, {
              className: "framer-w5acme",
              "data-framer-name": "About",
              id: elementId,
              layout: motionLayout,
              ref: ref1,
              children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                breakpoint: baseVariant,
                overrides: {
                  QRYvcRjNm: {
                    width: `min(${
                      componentViewport?.width || "100vw"
                    } - 40px, 1450px)`,
                    y: (componentViewport?.y || 0) + 0 + 900 + 100 + 0,
                  },
                },
                children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                  height: 420,
                  width: `min(${
                    componentViewport?.width || "100vw"
                  } - 80px, 1450px)`,
                  children: /*#__PURE__*/ _jsx(Container, {
                    className: "framer-1jut7bm-container",
                    nodeId: "qPeCag8vb",
                    scopeId: "OxIsxzOms",
                    children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                      breakpoint: baseVariant,
                      overrides: {
                        QRYvcRjNm: { variant: matchVariant("dscYFW3p_") },
                        tI2pZQrBZ: { variant: matchVariant("w8skYU3vx") },
                      },
                      children: /*#__PURE__*/ _jsx(About, {
                        height: "100%",
                        hsqaMsgZO:
                          "Every collection bridges tradition and the present — designed with precision, worn with confidence, and made to endure.",
                        id: "qPeCag8vb",
                        layoutId: "qPeCag8vb",
                        lvakD9vKH:
                          "Rooted in Moroccan heritage, refined for the modern world. Wear is where bold expression meets effortless sophistication.",
                        style: { maxWidth: "100%", width: "100%" },
                        variant: matchVariant("slbSQ8f94"),
                        width: "100%",
                      }),
                    }),
                  }),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(motion.section, {
              className: "framer-g16qmn",
              "data-framer-name": "Shops",
              layout: motionLayout,
              children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                breakpoint: baseVariant,
                overrides: {
                  QRYvcRjNm: {
                    width: `min(${
                      componentViewport?.width || "100vw"
                    } - 40px, 1450px)`,
                    y: (componentViewport?.y || 0) + 0 + 1520 + 100 + 0,
                  },
                },
                children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                  height: 640,
                  width: `min(${
                    componentViewport?.width || "100vw"
                  } - 80px, 1450px)`,
                  children: /*#__PURE__*/ _jsx(Container, {
                    className: "framer-1hemcsa-container",
                    nodeId: "f7i8oVSIe",
                    scopeId: "OxIsxzOms",
                    children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                      breakpoint: baseVariant,
                      overrides: {
                        QRYvcRjNm: {
                          EasSLkBR1: "16px",
                          variant: matchVariant("G6tu6Omk_"),
                        },
                        tI2pZQrBZ: { variant: matchVariant("G6tu6Omk_") },
                      },
                      children: /*#__PURE__*/ _jsx(ShopCategoryContainer, {
                        EasSLkBR1: "20px",
                        EZ1B_DxvX: "Womenswear for Every Occasion",
                        height: "100%",
                        id: "f7i8oVSIe",
                        layoutId: "f7i8oVSIe",
                        NoghC0Wxj: "Men's Wear",
                        SSb4q7b27: "Women's Wear",
                        style: { maxWidth: "100%", width: "100%" },
                        variant: matchVariant("bk3MGP0Xq"),
                        width: "100%",
                        Z7XH83ag8: "Menswear for Every Occasion",
                      }),
                    }),
                  }),
                }),
              }),
            }),
            /*#__PURE__*/ _jsxs(motion.section, {
              className: "framer-1lsuayo",
              "data-framer-name": "Trending Product",
              layout: motionLayout,
              children: [
                /*#__PURE__*/ _jsxs("div", {
                  className: "framer-op0qbh",
                  "data-framer-name": "Heading",
                  children: [
                    /*#__PURE__*/ _jsx("div", {
                      className: "framer-1ga7ah2",
                      "data-framer-name": "Title",
                      children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx("h4", {
                            className: "framer-styles-preset-1j4z099",
                            "data-styles-preset": "fvwhVXh4s",
                            dir: "auto",
                            style: {
                              "--framer-text-color":
                                "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                            },
                            children: "Trending",
                          }),
                        }),
                        className: "framer-19wxz1w",
                        fonts: ["Inter"],
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                    }),
                    /*#__PURE__*/ _jsx(ResolveLinks, {
                      links: [
                        {
                          href: {
                            pathVariables: { nrKGcDENu: "all" },
                            unresolvedPathSlugs: {
                              nrKGcDENu: {
                                collectionId: "ZFPX8XxiR",
                                collectionItemId: "Ybq0oXQi0",
                              },
                            },
                            webPageId: "WvEH3mXtq",
                          },
                          implicitPathVariables: undefined,
                        },
                        {
                          href: {
                            pathVariables: { nrKGcDENu: "all" },
                            unresolvedPathSlugs: {
                              nrKGcDENu: {
                                collectionId: "ZFPX8XxiR",
                                collectionItemId: "Ybq0oXQi0",
                              },
                            },
                            webPageId: "WvEH3mXtq",
                          },
                          implicitPathVariables: undefined,
                        },
                        {
                          href: {
                            pathVariables: { nrKGcDENu: "all" },
                            unresolvedPathSlugs: {
                              nrKGcDENu: {
                                collectionId: "ZFPX8XxiR",
                                collectionItemId: "Ybq0oXQi0",
                              },
                            },
                            webPageId: "WvEH3mXtq",
                          },
                          implicitPathVariables: undefined,
                        },
                      ],
                      children: (resolvedLinks1) =>
                        /*#__PURE__*/ _jsx(PropertyOverrides, {
                          breakpoint: baseVariant,
                          overrides: {
                            QRYvcRjNm: {
                              y:
                                (componentViewport?.y || 0) +
                                0 +
                                2360 +
                                100 +
                                0 +
                                3.9,
                            },
                          },
                          children: /*#__PURE__*/ _jsx(
                            ComponentViewportProvider,
                            {
                              height: 23,
                              children: /*#__PURE__*/ _jsx(Container, {
                                className: "framer-ux68ei-container",
                                nodeId: "ido2cGwmC",
                                scopeId: "OxIsxzOms",
                                children: /*#__PURE__*/ _jsx(
                                  PropertyOverrides,
                                  {
                                    breakpoint: baseVariant,
                                    overrides: {
                                      QRYvcRjNm: {
                                        Q5Serm7cH: resolvedLinks1[2],
                                      },
                                      tI2pZQrBZ: {
                                        Q5Serm7cH: resolvedLinks1[1],
                                      },
                                    },
                                    children: /*#__PURE__*/ _jsx(InlineLink, {
                                      bpLCIIzV1:
                                        "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                      height: "100%",
                                      id: "ido2cGwmC",
                                      IVNh0TbCL:
                                        "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                      layoutId: "ido2cGwmC",
                                      NOVGXPYPw: 16,
                                      Q5Serm7cH: resolvedLinks1[0],
                                      sjXwstpq1: "See All",
                                      width: "100%",
                                      ZnNj69UmK:
                                        "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                    }),
                                  }
                                ),
                              }),
                            }
                          ),
                        }),
                    }),
                  ],
                }),
                /*#__PURE__*/ _jsx("div", {
                  className: "framer-1nkquaw",
                  children: /*#__PURE__*/ _jsx(ChildrenCanSuspend, {
                    children: /*#__PURE__*/ _jsx(QueryData, {
                      query: query(),
                      children: (collection, paginationInfo, loadMore) => {
                        return /*#__PURE__*/ _jsx(_Fragment, {
                          children: collection?.map(
                            (
                              {
                                AHNguEn6H: AHNguEn6Hr_Qhc4yP8,
                                hNvG3yjWh: hNvG3yjWhr_Qhc4yP8,
                                id: idr_Qhc4yP8,
                                ixptKemFc: ixptKemFcr_Qhc4yP8,
                                jQHMHfZ0G: jQHMHfZ0Gr_Qhc4yP8,
                                mcwXYk3GK: mcwXYk3GKr_Qhc4yP8,
                                NPclJ_YtQ: NPclJ_YtQr_Qhc4yP8,
                                oWUHQkhzX: oWUHQkhzXr_Qhc4yP8,
                                RMwVI8LUM: RMwVI8LUMr_Qhc4yP8,
                                tZaiMnhUs: tZaiMnhUsr_Qhc4yP8,
                                UKXz5hUjD: UKXz5hUjDr_Qhc4yP8,
                                wqm7rDVcP: wqm7rDVcPr_Qhc4yP8,
                                XnegVJs7w: XnegVJs7wr_Qhc4yP8,
                              },
                              index
                            ) => {
                              RMwVI8LUMr_Qhc4yP8 ??= "";
                              UKXz5hUjDr_Qhc4yP8 ??= "";
                              tZaiMnhUsr_Qhc4yP8 ??= "";
                              NPclJ_YtQr_Qhc4yP8 ??= "";
                              mcwXYk3GKr_Qhc4yP8 ??= "";
                              XnegVJs7wr_Qhc4yP8 ??= "";
                              return /*#__PURE__*/ _jsx(
                                LayoutGroup,
                                {
                                  id: `r_Qhc4yP8-${idr_Qhc4yP8}`,
                                  children: /*#__PURE__*/ _jsx(
                                    PathVariablesContext.Provider,
                                    {
                                      value: { NPclJ_YtQ: NPclJ_YtQr_Qhc4yP8 },
                                      children: /*#__PURE__*/ _jsx(
                                        ResolveLinks,
                                        {
                                          links: [
                                            {
                                              href: {
                                                pathVariables: {
                                                  NPclJ_YtQ: NPclJ_YtQr_Qhc4yP8,
                                                },
                                                webPageId: "nw9I3LuHj",
                                              },
                                              implicitPathVariables: undefined,
                                            },
                                            {
                                              href: {
                                                pathVariables: {
                                                  NPclJ_YtQ: NPclJ_YtQr_Qhc4yP8,
                                                },
                                                webPageId: "nw9I3LuHj",
                                              },
                                              implicitPathVariables: undefined,
                                            },
                                            {
                                              href: {
                                                pathVariables: {
                                                  NPclJ_YtQ: NPclJ_YtQr_Qhc4yP8,
                                                },
                                                webPageId: "nw9I3LuHj",
                                              },
                                              implicitPathVariables: undefined,
                                            },
                                          ],
                                          children: (resolvedLinks2) =>
                                            /*#__PURE__*/ _jsx(
                                              PropertyOverrides,
                                              {
                                                breakpoint: baseVariant,
                                                overrides: {
                                                  QRYvcRjNm: {
                                                    width: `max(min(${
                                                      componentViewport?.width ||
                                                      "100vw"
                                                    } - 40px, 1450px), 50px)`,
                                                    y:
                                                      (componentViewport?.y ||
                                                        0) +
                                                      0 +
                                                      2360 +
                                                      100 +
                                                      50.8 +
                                                      0 +
                                                      0,
                                                  },
                                                  tI2pZQrBZ: {
                                                    width: `max((min(${
                                                      componentViewport?.width ||
                                                      "100vw"
                                                    } - 80px, 1450px) - 20px) / 2, 50px)`,
                                                  },
                                                },
                                                children: /*#__PURE__*/ _jsx(
                                                  ComponentViewportProvider,
                                                  {
                                                    height: 517,
                                                    width: `max((min(${
                                                      componentViewport?.width ||
                                                      "100vw"
                                                    } - 80px, 1450px) - 60px) / 4, 50px)`,
                                                    children:
                                                      /*#__PURE__*/ _jsx(
                                                        Container,
                                                        {
                                                          className:
                                                            "framer-1eml8hm-container",
                                                          nodeId: "o2s2U2B31",
                                                          scopeId: "OxIsxzOms",
                                                          children:
                                                            /*#__PURE__*/ _jsx(
                                                              PropertyOverrides,
                                                              {
                                                                breakpoint:
                                                                  baseVariant,
                                                                overrides: {
                                                                  QRYvcRjNm: {
                                                                    BXgjxlp3M:
                                                                      resolvedLinks2[2],
                                                                  },
                                                                  tI2pZQrBZ: {
                                                                    BXgjxlp3M:
                                                                      resolvedLinks2[1],
                                                                  },
                                                                },
                                                                children:
                                                                  /*#__PURE__*/ _jsx(
                                                                    ProductCard,
                                                                    {
                                                                      BXgjxlp3M:
                                                                        resolvedLinks2[0],
                                                                      gTWMT7Vgz:
                                                                        UKXz5hUjDr_Qhc4yP8,
                                                                      height:
                                                                        "100%",
                                                                      hgC8KdleM:
                                                                        toResponsiveImage(
                                                                          jQHMHfZ0Gr_Qhc4yP8
                                                                        ),
                                                                      id: "o2s2U2B31",
                                                                      jFoxFoM4Y:
                                                                        toResponsiveImage(
                                                                          oWUHQkhzXr_Qhc4yP8
                                                                        ),
                                                                      layoutId:
                                                                        "o2s2U2B31",
                                                                      lDpW9LY5B:
                                                                        toResponsiveImage(
                                                                          ixptKemFcr_Qhc4yP8
                                                                        ),
                                                                      N0ynq_IBX:
                                                                        mcwXYk3GKr_Qhc4yP8,
                                                                      R7L1H4yqU:
                                                                        RMwVI8LUMr_Qhc4yP8,
                                                                      rrTw5Jd67:
                                                                        toResponsiveImage(
                                                                          AHNguEn6Hr_Qhc4yP8
                                                                        ),
                                                                      style: {
                                                                        width:
                                                                          "100%",
                                                                      },
                                                                      tfxbhoAu2:
                                                                        XnegVJs7wr_Qhc4yP8,
                                                                      variant:
                                                                        matchVariant(
                                                                          "b6fLwb5lh"
                                                                        ),
                                                                      VmtCwzSNA:
                                                                        tZaiMnhUsr_Qhc4yP8,
                                                                      width:
                                                                        "100%",
                                                                      yy_SdmMdI:
                                                                        toResponsiveImage(
                                                                          wqm7rDVcPr_Qhc4yP8
                                                                        ),
                                                                      ZRfBUL4UG:
                                                                        toResponsiveImage(
                                                                          hNvG3yjWhr_Qhc4yP8
                                                                        ),
                                                                    }
                                                                  ),
                                                              }
                                                            ),
                                                        }
                                                      ),
                                                  }
                                                ),
                                              }
                                            ),
                                        }
                                      ),
                                    }
                                  ),
                                },
                                idr_Qhc4yP8
                              );
                            }
                          ),
                        });
                      },
                    }),
                  }),
                }),
              ],
            }),
            /*#__PURE__*/ _jsx(motion.section, {
              className: "framer-ldexu0",
              "data-framer-name": "Pivot",
              layout: motionLayout,
              children: /*#__PURE__*/ _jsx(ResolveLinks, {
                links: [
                  {
                    href: {
                      pathVariables: { nrKGcDENu: "all" },
                      unresolvedPathSlugs: {
                        nrKGcDENu: {
                          collectionId: "ZFPX8XxiR",
                          collectionItemId: "Ybq0oXQi0",
                        },
                      },
                      webPageId: "WvEH3mXtq",
                    },
                    implicitPathVariables: undefined,
                  },
                  {
                    href: {
                      pathVariables: { nrKGcDENu: "all" },
                      unresolvedPathSlugs: {
                        nrKGcDENu: {
                          collectionId: "ZFPX8XxiR",
                          collectionItemId: "Ybq0oXQi0",
                        },
                      },
                      webPageId: "WvEH3mXtq",
                    },
                    implicitPathVariables: undefined,
                  },
                  {
                    href: {
                      pathVariables: { nrKGcDENu: "all" },
                      unresolvedPathSlugs: {
                        nrKGcDENu: {
                          collectionId: "ZFPX8XxiR",
                          collectionItemId: "Ybq0oXQi0",
                        },
                      },
                      webPageId: "WvEH3mXtq",
                    },
                    implicitPathVariables: undefined,
                  },
                ],
                children: (resolvedLinks3) =>
                  /*#__PURE__*/ _jsx(PropertyOverrides, {
                    breakpoint: baseVariant,
                    overrides: {
                      QRYvcRjNm: {
                        width: `min(${
                          componentViewport?.width || "100vw"
                        } - 40px, 1450px)`,
                        y: (componentViewport?.y || 0) + 0 + 4798.8 + 100 + 0,
                      },
                    },
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 850,
                      width: `min(${
                        componentViewport?.width || "100vw"
                      } - 80px, 1450px)`,
                      children: /*#__PURE__*/ _jsx(Container, {
                        className: "framer-1l1im2f-container",
                        nodeId: "WCKVZBhhe",
                        scopeId: "OxIsxzOms",
                        children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                          breakpoint: baseVariant,
                          overrides: {
                            QRYvcRjNm: {
                              aV5leFCgU: addImageAlt(
                                {
                                  pixelHeight: 3920,
                                  pixelWidth: 7680,
                                  positionX: "87.9%",
                                  positionY: "52.2%",
                                  src: "https://framerusercontent.com/images/iQAL5UIxExPNLNZ0iduaGediZGE.jpg?width=7680&height=3920",
                                  srcSet:
                                    "https://framerusercontent.com/images/iQAL5UIxExPNLNZ0iduaGediZGE.jpg?scale-down-to=512&width=7680&height=3920 512w,https://framerusercontent.com/images/iQAL5UIxExPNLNZ0iduaGediZGE.jpg?scale-down-to=1024&width=7680&height=3920 1024w,https://framerusercontent.com/images/iQAL5UIxExPNLNZ0iduaGediZGE.jpg?scale-down-to=2048&width=7680&height=3920 2048w,https://framerusercontent.com/images/iQAL5UIxExPNLNZ0iduaGediZGE.jpg?scale-down-to=4096&width=7680&height=3920 4096w,https://framerusercontent.com/images/iQAL5UIxExPNLNZ0iduaGediZGE.jpg?width=7680&height=3920 7680w",
                                },
                                ""
                              ),
                              oYVtmVQc7: resolvedLinks3[2],
                              variant: matchVariant("FCg7tKWB8"),
                            },
                            tI2pZQrBZ: {
                              oYVtmVQc7: resolvedLinks3[1],
                              variant: matchVariant("LXWMKDaWo"),
                            },
                          },
                          children: /*#__PURE__*/ _jsx(HeroSection, {
                            aV5leFCgU: addImageAlt(
                              {
                                pixelHeight: 3200,
                                pixelWidth: 6272,
                                src: "https://framerusercontent.com/images/CrVFK4QzuTSV1qcv6kFkYtJw.jpg?width=6272&height=3200",
                                srcSet:
                                  "https://framerusercontent.com/images/CrVFK4QzuTSV1qcv6kFkYtJw.jpg?scale-down-to=512&width=6272&height=3200 512w,https://framerusercontent.com/images/CrVFK4QzuTSV1qcv6kFkYtJw.jpg?scale-down-to=1024&width=6272&height=3200 1024w,https://framerusercontent.com/images/CrVFK4QzuTSV1qcv6kFkYtJw.jpg?scale-down-to=2048&width=6272&height=3200 2048w,https://framerusercontent.com/images/CrVFK4QzuTSV1qcv6kFkYtJw.jpg?scale-down-to=4096&width=6272&height=3200 4096w,https://framerusercontent.com/images/CrVFK4QzuTSV1qcv6kFkYtJw.jpg?width=6272&height=3200 6272w",
                              },
                              "Male model in a gray hoodie, posing casually."
                            ),
                            chsYNoXa1: false,
                            CL3qbw_yA: "esOdew2Ux",
                            DSpIx2khZ: "Effortless, affordable",
                            goZSwjip6: "Timeless pieces with a fearless soul",
                            height: "100%",
                            id: "WCKVZBhhe",
                            layoutId: "WCKVZBhhe",
                            oYVtmVQc7: resolvedLinks3[0],
                            rahElhIZb: "Shop men",
                            style: {
                              height: "100%",
                              maxWidth: "100%",
                              width: "100%",
                            },
                            tbwQDnYS3: true,
                            variant: matchVariant("n3_s9er9E"),
                            width: "100%",
                          }),
                        }),
                      }),
                    }),
                  }),
              }),
            }),
            /*#__PURE__*/ _jsxs(motion.section, {
              className: "framer-1dfxrsf",
              "data-framer-name": "Featured Product",
              layout: motionLayout,
              children: [
                /*#__PURE__*/ _jsxs("div", {
                  className: "framer-4yysez",
                  "data-framer-name": "Heading",
                  children: [
                    /*#__PURE__*/ _jsx("div", {
                      className: "framer-13iuphi",
                      children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx("h4", {
                            className: "framer-styles-preset-1j4z099",
                            "data-styles-preset": "fvwhVXh4s",
                            dir: "auto",
                            style: {
                              "--framer-text-color":
                                "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                            },
                            children: "Featured",
                          }),
                        }),
                        className: "framer-m0iwto",
                        fonts: ["Inter"],
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                    }),
                    /*#__PURE__*/ _jsx(ResolveLinks, {
                      links: [
                        {
                          href: {
                            pathVariables: { nrKGcDENu: "all" },
                            unresolvedPathSlugs: {
                              nrKGcDENu: {
                                collectionId: "ZFPX8XxiR",
                                collectionItemId: "Ybq0oXQi0",
                              },
                            },
                            webPageId: "WvEH3mXtq",
                          },
                          implicitPathVariables: undefined,
                        },
                        {
                          href: {
                            pathVariables: { nrKGcDENu: "all" },
                            unresolvedPathSlugs: {
                              nrKGcDENu: {
                                collectionId: "ZFPX8XxiR",
                                collectionItemId: "Ybq0oXQi0",
                              },
                            },
                            webPageId: "WvEH3mXtq",
                          },
                          implicitPathVariables: undefined,
                        },
                        {
                          href: {
                            pathVariables: { nrKGcDENu: "all" },
                            unresolvedPathSlugs: {
                              nrKGcDENu: {
                                collectionId: "ZFPX8XxiR",
                                collectionItemId: "Ybq0oXQi0",
                              },
                            },
                            webPageId: "WvEH3mXtq",
                          },
                          implicitPathVariables: undefined,
                        },
                      ],
                      children: (resolvedLinks4) =>
                        /*#__PURE__*/ _jsx(PropertyOverrides, {
                          breakpoint: baseVariant,
                          overrides: {
                            QRYvcRjNm: {
                              y:
                                (componentViewport?.y || 0) +
                                0 +
                                5848.8 +
                                100 +
                                0 +
                                3.9,
                            },
                          },
                          children: /*#__PURE__*/ _jsx(
                            ComponentViewportProvider,
                            {
                              height: 23,
                              children: /*#__PURE__*/ _jsx(Container, {
                                className: "framer-1m3qdss-container",
                                nodeId: "niNe5KOB2",
                                scopeId: "OxIsxzOms",
                                children: /*#__PURE__*/ _jsx(
                                  PropertyOverrides,
                                  {
                                    breakpoint: baseVariant,
                                    overrides: {
                                      QRYvcRjNm: {
                                        Q5Serm7cH: resolvedLinks4[2],
                                      },
                                      tI2pZQrBZ: {
                                        Q5Serm7cH: resolvedLinks4[1],
                                      },
                                    },
                                    children: /*#__PURE__*/ _jsx(InlineLink, {
                                      bpLCIIzV1:
                                        "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                      height: "100%",
                                      id: "niNe5KOB2",
                                      IVNh0TbCL:
                                        "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                      layoutId: "niNe5KOB2",
                                      NOVGXPYPw: 16,
                                      Q5Serm7cH: resolvedLinks4[0],
                                      sjXwstpq1: "See All",
                                      width: "100%",
                                      ZnNj69UmK:
                                        "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                    }),
                                  }
                                ),
                              }),
                            }
                          ),
                        }),
                    }),
                  ],
                }),
                /*#__PURE__*/ _jsx("div", {
                  className: "framer-xvmoq2",
                  children: /*#__PURE__*/ _jsx(ChildrenCanSuspend, {
                    children: /*#__PURE__*/ _jsx(QueryData, {
                      query: query1(),
                      children: (collection1, paginationInfo1, loadMore1) => {
                        return /*#__PURE__*/ _jsx(_Fragment, {
                          children: collection1?.map(
                            (
                              {
                                AHNguEn6H: AHNguEn6Hx_rqD9ujC,
                                hNvG3yjWh: hNvG3yjWhx_rqD9ujC,
                                id: idx_rqD9ujC,
                                ixptKemFc: ixptKemFcx_rqD9ujC,
                                jQHMHfZ0G: jQHMHfZ0Gx_rqD9ujC,
                                mcwXYk3GK: mcwXYk3GKx_rqD9ujC,
                                NPclJ_YtQ: NPclJ_YtQx_rqD9ujC,
                                oWUHQkhzX: oWUHQkhzXx_rqD9ujC,
                                RMwVI8LUM: RMwVI8LUMx_rqD9ujC,
                                tZaiMnhUs: tZaiMnhUsx_rqD9ujC,
                                UKXz5hUjD: UKXz5hUjDx_rqD9ujC,
                                wqm7rDVcP: wqm7rDVcPx_rqD9ujC,
                                XnegVJs7w: XnegVJs7wx_rqD9ujC,
                              },
                              index1
                            ) => {
                              RMwVI8LUMx_rqD9ujC ??= "";
                              UKXz5hUjDx_rqD9ujC ??= "";
                              tZaiMnhUsx_rqD9ujC ??= "";
                              NPclJ_YtQx_rqD9ujC ??= "";
                              mcwXYk3GKx_rqD9ujC ??= "";
                              XnegVJs7wx_rqD9ujC ??= "";
                              return /*#__PURE__*/ _jsx(
                                LayoutGroup,
                                {
                                  id: `x_rqD9ujC-${idx_rqD9ujC}`,
                                  children: /*#__PURE__*/ _jsx(
                                    PathVariablesContext.Provider,
                                    {
                                      value: { NPclJ_YtQ: NPclJ_YtQx_rqD9ujC },
                                      children: /*#__PURE__*/ _jsx(
                                        ResolveLinks,
                                        {
                                          links: [
                                            {
                                              href: {
                                                pathVariables: {
                                                  NPclJ_YtQ: NPclJ_YtQx_rqD9ujC,
                                                },
                                                webPageId: "nw9I3LuHj",
                                              },
                                              implicitPathVariables: undefined,
                                            },
                                            {
                                              href: {
                                                pathVariables: {
                                                  NPclJ_YtQ: NPclJ_YtQx_rqD9ujC,
                                                },
                                                webPageId: "nw9I3LuHj",
                                              },
                                              implicitPathVariables: undefined,
                                            },
                                            {
                                              href: {
                                                pathVariables: {
                                                  NPclJ_YtQ: NPclJ_YtQx_rqD9ujC,
                                                },
                                                webPageId: "nw9I3LuHj",
                                              },
                                              implicitPathVariables: undefined,
                                            },
                                          ],
                                          children: (resolvedLinks5) =>
                                            /*#__PURE__*/ _jsx(
                                              PropertyOverrides,
                                              {
                                                breakpoint: baseVariant,
                                                overrides: {
                                                  QRYvcRjNm: {
                                                    width: `max(min(${
                                                      componentViewport?.width ||
                                                      "100vw"
                                                    } - 40px, 1450px), 50px)`,
                                                    y:
                                                      (componentViewport?.y ||
                                                        0) +
                                                      0 +
                                                      5848.8 +
                                                      100 +
                                                      50.8 +
                                                      0 +
                                                      0,
                                                  },
                                                  tI2pZQrBZ: {
                                                    width: `max((min(${
                                                      componentViewport?.width ||
                                                      "100vw"
                                                    } - 80px, 1450px) - 20px) / 2, 50px)`,
                                                  },
                                                },
                                                children: /*#__PURE__*/ _jsx(
                                                  ComponentViewportProvider,
                                                  {
                                                    height: 517,
                                                    width: `max((min(${
                                                      componentViewport?.width ||
                                                      "100vw"
                                                    } - 80px, 1450px) - 60px) / 4, 50px)`,
                                                    children:
                                                      /*#__PURE__*/ _jsx(
                                                        Container,
                                                        {
                                                          className:
                                                            "framer-1ilxra-container",
                                                          nodeId: "EmV2ZDx8G",
                                                          scopeId: "OxIsxzOms",
                                                          children:
                                                            /*#__PURE__*/ _jsx(
                                                              PropertyOverrides,
                                                              {
                                                                breakpoint:
                                                                  baseVariant,
                                                                overrides: {
                                                                  QRYvcRjNm: {
                                                                    BXgjxlp3M:
                                                                      resolvedLinks5[2],
                                                                  },
                                                                  tI2pZQrBZ: {
                                                                    BXgjxlp3M:
                                                                      resolvedLinks5[1],
                                                                  },
                                                                },
                                                                children:
                                                                  /*#__PURE__*/ _jsx(
                                                                    ProductCard,
                                                                    {
                                                                      BXgjxlp3M:
                                                                        resolvedLinks5[0],
                                                                      gTWMT7Vgz:
                                                                        UKXz5hUjDx_rqD9ujC,
                                                                      height:
                                                                        "100%",
                                                                      hgC8KdleM:
                                                                        toResponsiveImage(
                                                                          jQHMHfZ0Gx_rqD9ujC
                                                                        ),
                                                                      id: "EmV2ZDx8G",
                                                                      jFoxFoM4Y:
                                                                        toResponsiveImage(
                                                                          oWUHQkhzXx_rqD9ujC
                                                                        ),
                                                                      layoutId:
                                                                        "EmV2ZDx8G",
                                                                      lDpW9LY5B:
                                                                        toResponsiveImage(
                                                                          ixptKemFcx_rqD9ujC
                                                                        ),
                                                                      N0ynq_IBX:
                                                                        mcwXYk3GKx_rqD9ujC,
                                                                      R7L1H4yqU:
                                                                        RMwVI8LUMx_rqD9ujC,
                                                                      rrTw5Jd67:
                                                                        toResponsiveImage(
                                                                          AHNguEn6Hx_rqD9ujC
                                                                        ),
                                                                      style: {
                                                                        width:
                                                                          "100%",
                                                                      },
                                                                      tfxbhoAu2:
                                                                        XnegVJs7wx_rqD9ujC,
                                                                      variant:
                                                                        matchVariant(
                                                                          "b6fLwb5lh"
                                                                        ),
                                                                      VmtCwzSNA:
                                                                        tZaiMnhUsx_rqD9ujC,
                                                                      width:
                                                                        "100%",
                                                                      yy_SdmMdI:
                                                                        toResponsiveImage(
                                                                          wqm7rDVcPx_rqD9ujC
                                                                        ),
                                                                      ZRfBUL4UG:
                                                                        toResponsiveImage(
                                                                          hNvG3yjWhx_rqD9ujC
                                                                        ),
                                                                    }
                                                                  ),
                                                              }
                                                            ),
                                                        }
                                                      ),
                                                  }
                                                ),
                                              }
                                            ),
                                        }
                                      ),
                                    }
                                  ),
                                },
                                idx_rqD9ujC
                              );
                            }
                          ),
                        });
                      },
                    }),
                  }),
                }),
              ],
            }),
            /*#__PURE__*/ _jsxs(motion.section, {
              className: "framer-1d2217g",
              "data-framer-name": "Community",
              layout: motionLayout,
              children: [
                /*#__PURE__*/ _jsxs("div", {
                  className: "framer-17t8g5k",
                  "data-framer-name": "Heading",
                  children: [
                    /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx("h4", {
                          className: "framer-styles-preset-1j4z099",
                          "data-styles-preset": "fvwhVXh4s",
                          dir: "auto",
                          children: "Wear Community",
                        }),
                      }),
                      className: "framer-515tz7",
                      fonts: ["Inter"],
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                    /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx("p", {
                          className: "framer-styles-preset-1fgo89p",
                          "data-styles-preset": "ickuMUi8E",
                          dir: "auto",
                          children:
                            "Get inspired, showcase your unique Wear style, and join the #WearCommunity! Tag us @Wear to share your looks.",
                        }),
                      }),
                      className: "framer-1140wst",
                      fonts: ["Inter"],
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                  ],
                }),
                /*#__PURE__*/ _jsxs("div", {
                  className: "framer-hsohik",
                  children: [
                    /*#__PURE__*/ _jsx(ChildrenCanSuspend, {
                      children: /*#__PURE__*/ _jsx(QueryData, {
                        query: query2(),
                        children: (collection2, paginationInfo2, loadMore2) => {
                          return /*#__PURE__*/ _jsx(_Fragment, {
                            children: /*#__PURE__*/ _jsx(
                              MotionDivWithTickerFX,
                              {
                                className: "framer-1q35xdd",
                                tickerEffectAlign: "start",
                                tickerEffectDirectionModifier: "default",
                                tickerEffectDraggable: true,
                                tickerEffectEnabled: true,
                                tickerEffectGap: 20,
                                tickerEffectHoverModifier: 100,
                                tickerEffectIsDataRepeater: true,
                                tickerEffectOverflow: "hidden",
                                tickerEffectPosition: "relative",
                                tickerEffectStackDirection: "row",
                                tickerEffectVelocity: 20,
                                children: collection2?.map(
                                  (
                                    {
                                      G2Q9rrLi4: G2Q9rrLi4VNwBRIc4W,
                                      id: idVNwBRIc4W,
                                      Tye02Iiu2: Tye02Iiu2VNwBRIc4W,
                                      xXJIgAYfG: xXJIgAYfGVNwBRIc4W,
                                    },
                                    index2
                                  ) => {
                                    Tye02Iiu2VNwBRIc4W ??= "";
                                    xXJIgAYfGVNwBRIc4W ??= "";
                                    return /*#__PURE__*/ _jsx(
                                      LayoutGroup,
                                      {
                                        id: `VNwBRIc4W-${idVNwBRIc4W}`,
                                        children: /*#__PURE__*/ _jsx(
                                          PathVariablesContext.Provider,
                                          {
                                            value: {
                                              xXJIgAYfG: xXJIgAYfGVNwBRIc4W,
                                            },
                                            children: /*#__PURE__*/ _jsx(
                                              TickerItem,
                                              {
                                                children: /*#__PURE__*/ _jsx(
                                                  PropertyOverrides,
                                                  {
                                                    breakpoint: baseVariant,
                                                    overrides: {
                                                      QRYvcRjNm: {
                                                        y:
                                                          (componentViewport?.y ||
                                                            0) +
                                                          0 +
                                                          8287.6 +
                                                          100 +
                                                          206.8 +
                                                          0 +
                                                          0 +
                                                          0,
                                                      },
                                                    },
                                                    children:
                                                      /*#__PURE__*/ _jsx(
                                                        ComponentViewportProvider,
                                                        {
                                                          height: 350,
                                                          width: "232.9688px",
                                                          children:
                                                            /*#__PURE__*/ _jsx(
                                                              ContainerWithFX,
                                                              {
                                                                __framer__animate:
                                                                  {
                                                                    transition:
                                                                      stagger(
                                                                        transition2,
                                                                        index2 *
                                                                          0.1
                                                                      ),
                                                                  },
                                                                __framer__animateOnce: true,
                                                                __framer__enter:
                                                                  animation,
                                                                __framer__styleAppearEffectEnabled: true,
                                                                __framer__threshold: 0,
                                                                __perspectiveFX: false,
                                                                __targetOpacity: 1,
                                                                className:
                                                                  "framer-1er13dq-container",
                                                                "data-framer-name":
                                                                  "Card",
                                                                name: "Card",
                                                                nodeId:
                                                                  "RDef2A4qf",
                                                                rendersWithMotion: true,
                                                                scopeId:
                                                                  "OxIsxzOms",
                                                                children:
                                                                  /*#__PURE__*/ _jsx(
                                                                    CategoryCard,
                                                                    {
                                                                      cYoeIzAJ0:
                                                                        Tye02Iiu2VNwBRIc4W,
                                                                      height:
                                                                        "100%",
                                                                      id: "RDef2A4qf",
                                                                      layoutId:
                                                                        "RDef2A4qf",
                                                                      name: "Card",
                                                                      style: {
                                                                        height:
                                                                          "100%",
                                                                        width:
                                                                          "100%",
                                                                      },
                                                                      variant:
                                                                        matchVariant(
                                                                          "e3tKMX7NT"
                                                                        ),
                                                                      vFCrRc8x4:
                                                                        toResponsiveImage(
                                                                          G2Q9rrLi4VNwBRIc4W
                                                                        ),
                                                                      width:
                                                                        "100%",
                                                                    }
                                                                  ),
                                                              }
                                                            ),
                                                        }
                                                      ),
                                                  }
                                                ),
                                              }
                                            ),
                                          }
                                        ),
                                      },
                                      idVNwBRIc4W
                                    );
                                  }
                                ),
                              }
                            ),
                          });
                        },
                      }),
                    }),
                    /*#__PURE__*/ _jsx(PropertyOverrides, {
                      breakpoint: baseVariant,
                      overrides: {
                        QRYvcRjNm: {
                          height: 122,
                          width: `min(${
                            componentViewport?.width || "100vw"
                          } - 40px, 1450px)`,
                          y:
                            (componentViewport?.y || 0) +
                            0 +
                            8287.6 +
                            100 +
                            206.8 +
                            0 +
                            370,
                        },
                        tI2pZQrBZ: { width: undefined },
                      },
                      children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        width: `calc(min(${
                          componentViewport?.width || "100vw"
                        } - 80px, 1450px) * 0.24)`,
                        children: /*#__PURE__*/ _jsx(ContainerWithFX, {
                          __framer__animate: { transition: transition3 },
                          __framer__animateOnce: false,
                          __framer__enter: animation1,
                          __framer__styleAppearEffectEnabled: true,
                          __framer__threshold: 0.5,
                          __perspectiveFX: false,
                          __targetOpacity: 1,
                          className: "framer-8j8ee-container",
                          nodeId: "vu6RBRRjA",
                          rendersWithMotion: true,
                          scopeId: "OxIsxzOms",
                          children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                              QRYvcRjNm: { style: { width: "100%" } },
                              tI2pZQrBZ: { style: { height: "100%" } },
                            },
                            children: /*#__PURE__*/ _jsx(CommunityCalloutCard, {
                              emTiZWlVs:
                                "var(--token-ab1a65fa-a184-40ca-b195-1036c81a9fa4, rgb(241, 241, 241))",
                              FAZu3pPnt: "space-between",
                              height: "100%",
                              hOygjDaph: "Join The Community",
                              id: "vu6RBRRjA",
                              L_D3NECt_:
                                "Join the #WearCommunity! Tag us @Wear to share your looks.",
                              layoutId: "vu6RBRRjA",
                              style: { height: "100%", width: "100%" },
                              width: "100%",
                              YQwtS_Zzt: "https://x.com/Drag_Frame",
                            }),
                          }),
                        }),
                      }),
                    }),
                  ],
                }),
              ],
            }),
          ],
        }),
        /*#__PURE__*/ _jsx("div", { id: "overlay" }),
      ],
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-fdiDZ.framer-jdqswy, .framer-fdiDZ .framer-jdqswy { display: block; }",
  ".framer-fdiDZ.framer-ptlv6u { align-content: center; align-items: center; background-color: var(--token-a1d66695-261b-4112-b609-9b6c0fb55851, #ffffff); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
  ".framer-fdiDZ .framer-n8yxu9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 92vh; justify-content: center; max-height: 900px; overflow: hidden; padding: 0px 20px 20px 20px; position: relative; width: 100%; }",
  ".framer-fdiDZ .framer-1fo8yy8-container { flex: 1 0 0px; height: 100%; max-width: 1500px; position: relative; width: 1px; }",
  ".framer-fdiDZ .framer-w5acme { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 150px 40px 100px 40px; position: relative; width: 100%; }",
  ".framer-fdiDZ .framer-1jut7bm-container, .framer-fdiDZ .framer-1hemcsa-container { flex: none; height: auto; max-width: 1450px; position: relative; width: 100%; }",
  ".framer-fdiDZ .framer-g16qmn, .framer-fdiDZ .framer-1lsuayo, .framer-fdiDZ .framer-1dfxrsf { align-content: center; align-items: center; background-color: var(--token-a1d66695-261b-4112-b609-9b6c0fb55851, #ffffff); display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: hidden; padding: 100px 40px 100px 40px; position: relative; width: 100%; }",
  ".framer-fdiDZ .framer-op0qbh, .framer-fdiDZ .framer-4yysez { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; max-width: 1450px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-fdiDZ .framer-1ga7ah2, .framer-fdiDZ .framer-13iuphi { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
  ".framer-fdiDZ .framer-19wxz1w, .framer-fdiDZ .framer-m0iwto { --framer-link-text-color: #0099ff; --framer-link-text-decoration: underline; flex: none; height: auto; max-width: 600px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-fdiDZ .framer-ux68ei-container, .framer-fdiDZ .framer-1m3qdss-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-fdiDZ .framer-1nkquaw, .framer-fdiDZ .framer-xvmoq2 { display: grid; flex: none; gap: 40px 20px; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(4, minmax(50px, 1fr)); height: min-content; justify-content: center; max-width: 1450px; padding: 0px; position: relative; width: 100%; }",
  ".framer-fdiDZ .framer-1eml8hm-container, .framer-fdiDZ .framer-1ilxra-container { align-self: center; flex: none; height: auto; justify-self: center; position: relative; width: 100%; }",
  ".framer-fdiDZ .framer-ldexu0 { align-content: center; align-items: center; background-color: var(--token-a1d66695-261b-4112-b609-9b6c0fb55851, #ffffff); display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 100px 40px 100px 40px; position: relative; width: 100%; }",
  ".framer-fdiDZ .framer-1l1im2f-container { flex: none; height: 85vh; max-width: 1450px; position: relative; width: 100%; }",
  ".framer-fdiDZ .framer-1d2217g { align-content: center; align-items: center; background-color: var(--token-a1d66695-261b-4112-b609-9b6c0fb55851, #ffffff); display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: hidden; padding: 100px 40px 100px 40px; position: relative; width: 100%; }",
  ".framer-fdiDZ .framer-17t8g5k { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 1450px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-fdiDZ .framer-515tz7, .framer-fdiDZ .framer-1140wst { --framer-link-text-color: #0099ff; --framer-link-text-decoration: underline; --framer-paragraph-spacing: 0px; flex: none; height: auto; max-width: 600px; overflow: visible; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-fdiDZ .framer-hsohik { align-content: center; align-items: center; border-bottom-left-radius: 10px; border-bottom-right-radius: 10px; border-top-left-radius: 10px; border-top-right-radius: 10px; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 20px; height: min-content; justify-content: flex-start; max-width: 1450px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-fdiDZ .framer-1q35xdd { align-content: flex-start; align-items: flex-start; border-bottom-left-radius: 10px; border-bottom-right-radius: 10px; border-top-left-radius: 10px; border-top-right-radius: 10px; cursor: e-resize; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-fdiDZ .framer-1er13dq-container { aspect-ratio: 0.665625 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 350px); position: relative; width: 233px; }",
  ".framer-fdiDZ .framer-8j8ee-container { align-self: stretch; flex: none; height: auto; position: relative; width: 24%; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  "@media (min-width: 810px) and (max-width: 1199.98px) { .framer-fdiDZ.framer-ptlv6u { width: 810px; } .framer-fdiDZ .framer-1nkquaw, .framer-fdiDZ .framer-xvmoq2 { grid-template-columns: repeat(2, minmax(50px, 1fr)); } .framer-fdiDZ .framer-8j8ee-container { width: auto; }}",
  "@media (max-width: 809.98px) { .framer-fdiDZ.framer-ptlv6u { width: 390px; } .framer-fdiDZ .framer-n8yxu9 { padding: 0px 10px 20px 10px; } .framer-fdiDZ .framer-w5acme, .framer-fdiDZ .framer-g16qmn, .framer-fdiDZ .framer-1lsuayo, .framer-fdiDZ .framer-ldexu0, .framer-fdiDZ .framer-1dfxrsf, .framer-fdiDZ .framer-1d2217g { padding: 100px 20px 100px 20px; } .framer-fdiDZ .framer-1nkquaw, .framer-fdiDZ .framer-xvmoq2 { grid-template-columns: repeat(1, minmax(50px, 1fr)); } .framer-fdiDZ .framer-hsohik { flex-direction: column; } .framer-fdiDZ .framer-1q35xdd { flex: none; width: 100%; } .framer-fdiDZ .framer-8j8ee-container { align-self: unset; width: 100%; }}",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 6006
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"tI2pZQrBZ":{"layout":["fixed","auto"]},"QRYvcRjNm":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerAcceptsLayoutTemplate true
 * @framerScrollSections {"mM7IKKtNV":{"pattern":":mM7IKKtNV","name":"about-us"}}
 * @framerResponsiveScreen true
 * @framerLayoutTemplateFlowEffect true
 */ const FramerOxIsxzOms = withCSS(Component, css, "framer-fdiDZ");
export default FramerOxIsxzOms;
FramerOxIsxzOms.displayName = "Page";
FramerOxIsxzOms.defaultProps = { height: 6006, width: 1200 };
addFonts(
  FramerOxIsxzOms,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...HeroSectionFonts,
    ...AboutFonts,
    ...ShopCategoryContainerFonts,
    ...InlineLinkFonts,
    ...ProductCardFonts,
    ...CategoryCardFonts,
    ...CommunityCalloutCardFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
FramerOxIsxzOms.loader = {
  load: (props, context) => {
    const locale = context.locale;
    const queryCacheEntry = queryCache.get(query(), locale);
    const queryCacheEntry1 = queryCache.get(query1(), locale);
    const queryCacheEntry2 = queryCache.get(query2(), locale);
    return Promise.allSettled([
      queryCacheEntry.preload(),
      queryCacheEntry1.preload(),
      queryCacheEntry2.preload(),
      forwardLoader(HeroSection, {}, context),
      forwardLoader(About, {}, context),
      forwardLoader(ShopCategoryContainer, {}, context),
      forwardLoader(InlineLink, {}, context),
      forwardLoader(CommunityCalloutCard, {}, context),
      (async () => {
        const parentData = (await queryCacheEntry.readMaybeAsync()) ?? [];
        return Promise.allSettled(
          parentData.flatMap((item) => forwardLoader(ProductCard, {}, context))
        );
      })(),
      (async () => {
        const parentData = (await queryCacheEntry1.readMaybeAsync()) ?? [];
        return Promise.allSettled(
          parentData.flatMap((item) => forwardLoader(ProductCard, {}, context))
        );
      })(),
      (async () => {
        const parentData = (await queryCacheEntry2.readMaybeAsync()) ?? [];
        return Promise.allSettled(
          parentData.flatMap((item) => forwardLoader(CategoryCard, {}, context))
        );
      })(),
    ]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerOxIsxzOms",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "1200",
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "6006",
        framerScrollSections:
          '{"mM7IKKtNV":{"pattern":":mM7IKKtNV","name":"about-us"}}',
        framerImmutableVariables: "true",
        framerResponsiveScreen: "true",
        framerAcceptsLayoutTemplate: "true",
        framerAutoSizeImages: "true",
        framerLayoutTemplateFlowEffect: "true",
        framerContractVersion: "1",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"tI2pZQrBZ":{"layout":["fixed","auto"]},"QRYvcRjNm":{"layout":["fixed","auto"]}}}',
        framerColorSyntax: "true",
      },
    },
    queryParamNames: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
