// Generated by Framer (7c2f7bf)
import {
  jsx as _jsx,
  jsxs as _jsxs,
  Fragment as _Fragment,
} from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  Floating,
  forwardLoader,
  getFonts,
  getPropertyControls,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useOverlayState,
  useVariantState,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from "framer";
import {
  AnimatePresence,
  LayoutGroup,
  motion,
  MotionConfigContext,
} from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import FC_CatalogSearch from "https://framerusercontent.com/modules/tlSE71XX3CzjVeSC2JLA/kOlsgfY0y3dukSLwtLP4/FC_CatalogSearch.js";
import FiltersIcon from "https://framerusercontent.com/modules/oIyOAB3BTJWczLwlKnyE/JEOcoykaR2GBaSruKROu/b1BqIbzne.js";
import Color from "https://framerusercontent.com/modules/aKMccFq7Zlhzt09igunH/niCdjq5g5elMOJcK5aSP/EHd6HQbfP.js";
import Filters from "https://framerusercontent.com/modules/0Be4NrlVqfHd35gD0q6q/dGiE4lyoHLpEgGAxs6k7/ppzN1nY5n.js";
const ColorFonts = getFonts(Color);
const FC_CatalogSearchFonts = getFonts(FC_CatalogSearch);
const SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
  withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
const FiltersIconFonts = getFonts(FiltersIcon);
const FiltersFonts = getFonts(Filters);
const MotionDivWithFX = withFX(motion.div);
const FiltersControls = getPropertyControls(Filters);
const cycleOrder = ["JMK1R1ivk", "Djvac8jsu", "WYU6HAnEy"];
const serializationHash = "framer-Tu98e";
const variantClassNames = {
  Djvac8jsu: "framer-v-10fnffa",
  JMK1R1ivk: "framer-v-1bf4j8i",
  WYU6HAnEy: "framer-v-1kwvg78",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const fJs5OXAyl = undefined;
const h2n3HL6ZZ = undefined;
const dBO5XoSB_ = undefined;
const setdBO5XoSB_ = undefined;
const transition1 = {
  delay: 0,
  duration: 0.4,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const transition2 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition2,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 0.9,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
const animation2 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition2,
  x: 0,
  y: 0,
};
const animation3 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Overlay = ({
  children,
  blockDocumentScrolling,
  dismissWithEsc,
  enabled = true,
}) => {
  const [visible, setVisible] = useOverlayState({
    blockDocumentScrolling,
    dismissWithEsc: enabled && dismissWithEsc,
  });
  return children({
    hide: () => setVisible(false),
    show: () => setVisible(true),
    toggle: () => setVisible(!visible),
    visible: enabled && visible,
  });
};
const humanReadableVariantMap = {
  Closed: "JMK1R1ivk",
  Open: "Djvac8jsu",
  Phone: "WYU6HAnEy",
};
const Variants = motion.create(React.Fragment);
const humanReadableEnumMap = { Men: "A5PYaOjPI", Women: "D7ImLRc4m" };
const useStateVariable = (externalState, setExternalState) => {
  const [internalState, setInternalState] = React.useState(externalState);
  const [previousExternalState, setPreviousExternalState] =
    React.useState(externalState);
  if (setExternalState) {
    return [externalState, setExternalState];
  }
  if (externalState !== previousExternalState) {
    setInternalState(externalState);
    setPreviousExternalState(externalState);
  }
  return [internalState, setInternalState];
};
const getProps = ({ click, height, id, phhone, variant1, width, ...props }) => {
  return {
    ...props,
    dBO5XoSB_:
      humanReadableEnumMap[variant1] ??
      variant1 ??
      props.dBO5XoSB_ ??
      "A5PYaOjPI",
    fJs5OXAyl: click ?? props.fJs5OXAyl,
    h2n3HL6ZZ: phhone ?? props.h2n3HL6ZZ,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "JMK1R1ivk",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    fJs5OXAyl,
    h2n3HL6ZZ,
    dBO5XoSB_: externaldBO5XoSB_,
    ondBO5XoSB_Change: setExternaldBO5XoSB_,
    ...restProps
  } = getProps(props);
  const [dBO5XoSB_, setdBO5XoSB_] = useStateVariable(
    externaldBO5XoSB_,
    setExternaldBO5XoSB_
  );
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "JMK1R1ivk",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTap17c57mp = ({ overlay }) =>
    activeVariantCallback(async (...args) => {
      setGestureState({ isPressed: false });
      setVariant("Djvac8jsu");
      overlay.show();
    });
  const onTap1autgen = ({ overlay }) =>
    activeVariantCallback(async (...args) => {
      setGestureState({ isPressed: false });
      overlay.show();
    });
  const onMouseLeaveli4ncc = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: false });
    setVariant("JMK1R1ivk");
  });
  const DOY1KgpkOs7aycf = activeVariantCallback(async (...args) => {
    if (fJs5OXAyl) {
      const res = await fJs5OXAyl(...args);
      if (res === false) return false;
    }
  });
  const DOY1KgpkO2znxz7 = activeVariantCallback(async (...args) => {
    if (h2n3HL6ZZ) {
      const res = await h2n3HL6ZZ(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = () => {
    if (baseVariant === "WYU6HAnEy") return false;
    return true;
  };
  const ref1 = React.useRef(null);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Overlay, {
        blockDocumentScrolling: false,
        dismissWithEsc: false,
        enabled: isDisplayed(),
        children: (overlay) =>
          /*#__PURE__*/ _jsx(_Fragment, {
            children: /*#__PURE__*/ _jsx(Transition, {
              value: transition1,
              children: /*#__PURE__*/ _jsxs(motion.div, {
                ...restProps,
                ...gestureHandlers,
                className: cx(
                  scopingClassNames,
                  "framer-1bf4j8i",
                  className,
                  classNames
                ),
                "data-framer-name": "Closed",
                "data-highlight": true,
                id: `${layoutId}-1bf4j8i`,
                layoutDependency: layoutDependency,
                layoutId: "JMK1R1ivk",
                onTap: onTap17c57mp({ overlay }),
                ref: refBinding,
                style: {
                  backgroundColor:
                    "var(--token-ab1a65fa-a184-40ca-b195-1036c81a9fa4, rgb(247, 247, 247))",
                  borderBottomLeftRadius: 10,
                  borderBottomRightRadius: 10,
                  borderTopLeftRadius: 10,
                  borderTopRightRadius: 10,
                  ...style,
                },
                ...addPropertyOverrides(
                  {
                    Djvac8jsu: {
                      "data-framer-name": "Open",
                      onMouseLeave: onMouseLeaveli4ncc,
                      onTap: onTap1autgen({ overlay }),
                    },
                    WYU6HAnEy: {
                      "data-framer-name": "Phone",
                      onTap: onTap1autgen({ overlay }),
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
                children: [
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 32,
                    y:
                      (componentViewport?.y || 0) +
                      (0 + ((componentViewport?.height || 43) - 0 - 32) / 2),
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-1u6elrn-container",
                        layoutDependency: layoutDependency,
                        layoutId: "Nj_seRYKc-container",
                        nodeId: "Nj_seRYKc",
                        rendersWithMotion: true,
                        scopeId: "MxAqgr1h9",
                        children: /*#__PURE__*/ _jsx(Color, {
                          height: "100%",
                          id: "Nj_seRYKc",
                          layoutId: "Nj_seRYKc",
                          miPhN2bzL: 2,
                          variant: matchVariant("clygIHuG0"),
                          width: "100%",
                          ...addPropertyOverrides(
                            { WYU6HAnEy: { miPhN2bzL: 1 } },
                            baseVariant,
                            gestureVariant
                          ),
                        }),
                      }
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainerWithFXWithOptimizedAppearEffect,
                      {
                        __perspectiveFX: false,
                        __smartComponentFX: true,
                        __targetOpacity: 1,
                        animate: animation,
                        className: "framer-ksrbcx-container",
                        "data-framer-appear-id": "ksrbcx",
                        initial: animation1,
                        isAuthoredByUser: true,
                        isModuleExternal: true,
                        layoutDependency: layoutDependency,
                        layoutId: "nw4Uwuwq2-container",
                        nodeId: "nw4Uwuwq2",
                        optimized: true,
                        rendersWithMotion: true,
                        scopeId: "MxAqgr1h9",
                        children: /*#__PURE__*/ _jsx(FC_CatalogSearch, {
                          behavior: {
                            debounceDelay: 300,
                            page: false,
                            realTime: true,
                            slug: "search",
                          },
                          clear: {
                            background: "rgb(247, 247, 247)",
                            border: {
                              color: "rgba(0, 0, 0, 0.3)",
                              style: "solid",
                              width: 0,
                            },
                            color: "rgb(153, 153, 153)",
                            content: "Clear",
                            font: {},
                            iconColor: "rgb(153, 153, 153)",
                            iconIsCustom: false,
                            iconSize: 12,
                            iconWeight: 1.5,
                            isText: false,
                            padding: 4,
                            paddingBottom: 4,
                            paddingLeft: 4,
                            paddingPerSide: false,
                            paddingRight: 4,
                            paddingTop: 4,
                            radius: 24,
                            radiusBottomLeft: 24,
                            radiusBottomRight: 24,
                            radiusPerCorner: false,
                            radiusTopLeft: 24,
                            radiusTopRight: 24,
                            show: false,
                            transform: "None",
                          },
                          height: "100%",
                          id: "nw4Uwuwq2",
                          layoutId: "nw4Uwuwq2",
                          searchIcon: {
                            background: {
                              border: {
                                bottom: 1,
                                color: "rgb(235, 235, 235)",
                                isMixed: false,
                                left: 1,
                                right: 1,
                                style: "solid",
                                top: 1,
                                width: 1,
                              },
                              color: "rgba(0, 0, 0, 0)",
                              padding: 4,
                              paddingBottom: 4,
                              paddingLeft: 4,
                              paddingPerSide: false,
                              paddingRight: 4,
                              paddingTop: 4,
                              radius: 4,
                              radiusBottomLeft: 4,
                              radiusBottomRight: 4,
                              radiusPerCorner: false,
                              radiusTopLeft: 4,
                              radiusTopRight: 4,
                            },
                            color: "rgb(153, 153, 153)",
                            isCustom: true,
                            show: false,
                            size: 16,
                            weight: 2,
                          },
                          style: { height: "100%", width: "100%" },
                          styles: {
                            background: {
                              border: {
                                bottom: 1,
                                color: "rgba(235, 235, 235, 0)",
                                isMixed: false,
                                left: 1,
                                right: 1,
                                style: "solid",
                                top: 1,
                                width: 1,
                              },
                              color: "rgba(250, 250, 250, 0)",
                              focusBackground: "rgba(255, 255, 255, 0)",
                              focusBorder: {
                                bottom: 1,
                                color: "rgba(0, 0, 0, 0)",
                                isMixed: false,
                                left: 1,
                                right: 1,
                                style: "solid",
                                top: 1,
                                width: 1,
                              },
                              hoverBackground: "rgba(247, 247, 247, 0)",
                              hoverBorder: {
                                bottom: 1,
                                color: "rgba(0, 0, 0, 0)",
                                isMixed: false,
                                left: 1,
                                right: 1,
                                style: "solid",
                                top: 1,
                                width: 1,
                              },
                            },
                            borderRadius: 10,
                            gap: 20,
                            padding: 10,
                            paddingBottom: 10,
                            paddingLeft: 10,
                            paddingPerSide: false,
                            paddingRight: 10,
                            paddingTop: 10,
                            radiusBottomLeft: 10,
                            radiusBottomRight: 10,
                            radiusPerCorner: false,
                            radiusTopLeft: 10,
                            radiusTopRight: 10,
                          },
                          text: {
                            color: "rgb(0, 0, 0)",
                            font: {
                              fontFamily:
                                '"Inter", "Inter Placeholder", sans-serif',
                              fontSize: "13px",
                              fontStyle: "normal",
                              fontWeight: 400,
                              letterSpacing: "0em",
                              lineHeight: "1em",
                            },
                            placeholder: "Search...",
                            placeholderColor: "rgb(153, 153, 153)",
                          },
                          width: "100%",
                          ...addPropertyOverrides(
                            {
                              WYU6HAnEy: {
                                styles: {
                                  background: {
                                    border: {
                                      bottom: 1,
                                      color: "rgba(235, 235, 235, 0)",
                                      isMixed: false,
                                      left: 1,
                                      right: 1,
                                      style: "solid",
                                      top: 1,
                                      width: 1,
                                    },
                                    color: "rgba(250, 250, 250, 0)",
                                    focusBackground: "rgba(255, 255, 255, 0)",
                                    focusBorder: {
                                      bottom: 1,
                                      color: "rgba(0, 0, 0, 0)",
                                      isMixed: false,
                                      left: 1,
                                      right: 1,
                                      style: "solid",
                                      top: 1,
                                      width: 1,
                                    },
                                    hoverBackground: "rgba(247, 247, 247, 0)",
                                    hoverBorder: {
                                      bottom: 1,
                                      color: "rgba(0, 0, 0, 0)",
                                      isMixed: false,
                                      left: 1,
                                      right: 1,
                                      style: "solid",
                                      top: 1,
                                      width: 1,
                                    },
                                  },
                                  borderRadius: 10,
                                  gap: 20,
                                  padding: 10,
                                  paddingBottom: 10,
                                  paddingLeft: 10,
                                  paddingPerSide: true,
                                  paddingRight: 10,
                                  paddingTop: 10,
                                  radiusBottomLeft: 10,
                                  radiusBottomRight: 10,
                                  radiusPerCorner: false,
                                  radiusTopLeft: 10,
                                  radiusTopRight: 10,
                                },
                              },
                            },
                            baseVariant,
                            gestureVariant
                          ),
                        }),
                      }
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 30,
                    y:
                      (componentViewport?.y || 0) +
                      ((componentViewport?.height || 43) * 0.5116279069767444 -
                        15),
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-a3b3ir-container",
                        "data-framer-name": "Filters Icon",
                        layoutDependency: layoutDependency,
                        layoutId: "A5w3OCa1j-container",
                        name: "Filters Icon",
                        nodeId: "A5w3OCa1j",
                        rendersWithMotion: true,
                        scopeId: "MxAqgr1h9",
                        transformTemplate: transformTemplate1,
                        children: /*#__PURE__*/ _jsx(FiltersIcon, {
                          DOY1KgpkO: DOY1KgpkOs7aycf,
                          height: "100%",
                          id: "A5w3OCa1j",
                          layoutId: "A5w3OCa1j",
                          name: "Filters Icon",
                          width: "100%",
                          ...addPropertyOverrides(
                            { WYU6HAnEy: { DOY1KgpkO: DOY1KgpkO2znxz7 } },
                            baseVariant,
                            gestureVariant
                          ),
                        }),
                      }
                    ),
                  }),
                  isDisplayed() &&
                    /*#__PURE__*/ _jsx(AnimatePresence, {
                      children:
                        overlay.visible &&
                        /*#__PURE__*/ _jsx(Floating, {
                          alignment: "center",
                          anchorRef: refBinding,
                          className: cx(scopingClassNames, classNames),
                          collisionDetection: true,
                          collisionDetectionPadding: 20,
                          "data-framer-portal-id": `${layoutId}-1bf4j8i`,
                          offsetX: 0,
                          offsetY: 10,
                          onDismiss: overlay.hide,
                          placement: "bottom",
                          safeArea: false,
                          zIndex: 11,
                          ...addPropertyOverrides(
                            {
                              Djvac8jsu: {
                                collisionDetection: false,
                                collisionDetectionPadding: undefined,
                                safeArea: true,
                              },
                            },
                            baseVariant,
                            gestureVariant
                          ),
                          children: /*#__PURE__*/ _jsx(MotionDivWithFX, {
                            __perspectiveFX: false,
                            __smartComponentFX: true,
                            __targetOpacity: 1,
                            animate: animation,
                            className: "framer-1pitia7",
                            "data-framer-name": "Overlay",
                            exit: animation2,
                            initial: animation3,
                            layoutDependency: layoutDependency,
                            layoutId: "Hg7EaJgv8",
                            ref: ref1,
                            role: "dialog",
                            style: {
                              backgroundColor: "rgb(247, 247, 247)",
                              borderBottomLeftRadius: 10,
                              borderBottomRightRadius: 10,
                              borderTopLeftRadius: 10,
                              borderTopRightRadius: 10,
                            },
                            children: /*#__PURE__*/ _jsx(
                              ComponentViewportProvider,
                              {
                                width: "600px",
                                children: /*#__PURE__*/ _jsx(
                                  SmartComponentScopedContainer,
                                  {
                                    className: "framer-1sdewws-container",
                                    layoutDependency: layoutDependency,
                                    layoutId: "wP4LGZGm5-container",
                                    nodeId: "wP4LGZGm5",
                                    rendersWithMotion: true,
                                    scopeId: "MxAqgr1h9",
                                    children: /*#__PURE__*/ _jsx(Filters, {
                                      height: "100%",
                                      id: "wP4LGZGm5",
                                      KFRWD3w6M: dBO5XoSB_,
                                      layoutId: "wP4LGZGm5",
                                      o3WTHHTGt: "10px",
                                      onKFRWD3w6MChange: setdBO5XoSB_,
                                      style: { width: "100%" },
                                      variant: matchVariant("Dke0JJK7A"),
                                      width: "100%",
                                    }),
                                  }
                                ),
                              }
                            ),
                          }),
                        }),
                    }),
                ],
              }),
            }),
          }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-Tu98e.framer-nt8spf, .framer-Tu98e .framer-nt8spf { display: block; }",
  ".framer-Tu98e.framer-1bf4j8i { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; height: 43px; justify-content: space-between; overflow: var(--overflow-clip-fallback, clip); padding: 0px 8px 0px 6px; position: relative; width: 380px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-Tu98e .framer-1u6elrn-container { flex: none; height: auto; position: relative; width: auto; z-index: 6; }",
  ".framer-Tu98e .framer-ksrbcx-container { flex: none; height: 100%; position: relative; width: 600px; z-index: 1; }",
  ".framer-Tu98e .framer-a3b3ir-container { flex: none; height: auto; position: absolute; right: 10px; top: 51%; width: auto; z-index: 8; }",
  ".framer-Tu98e .framer-1pitia7 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 600px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-Tu98e .framer-1sdewws-container { flex: none; height: auto; position: relative; width: 100%; }",
  ".framer-Tu98e.framer-v-10fnffa.framer-1bf4j8i { width: 600px; }",
  ".framer-Tu98e.framer-v-1kwvg78.framer-1bf4j8i { width: 250px; }",
  ".framer-Tu98e.framer-v-1kwvg78 .framer-1u6elrn-container { order: 0; }",
  ".framer-Tu98e.framer-v-1kwvg78 .framer-ksrbcx-container { order: 1; }",
  ".framer-Tu98e.framer-v-1kwvg78 .framer-a3b3ir-container { order: 2; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 43
 * @framerIntrinsicWidth 380
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"Djvac8jsu":{"layout":["fixed","fixed"]},"WYU6HAnEy":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"fJs5OXAyl":"click","h2n3HL6ZZ":"phhone","dBO5XoSB_":"variant1"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerMxAqgr1h9 = withCSS(Component, css, "framer-Tu98e");
export default FramerMxAqgr1h9;
FramerMxAqgr1h9.displayName = "Search";
FramerMxAqgr1h9.defaultProps = { height: 43, width: 380 };
addPropertyControls(FramerMxAqgr1h9, {
  variant: {
    options: ["JMK1R1ivk", "Djvac8jsu", "WYU6HAnEy"],
    optionTitles: ["Closed", "Open", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  fJs5OXAyl: { title: "Click", type: ControlType.EventHandler },
  h2n3HL6ZZ: { title: "Phhone", type: ControlType.EventHandler },
  dBO5XoSB_: FiltersControls?.["KFRWD3w6M"] && {
    ...FiltersControls["KFRWD3w6M"],
    defaultValue: "A5PYaOjPI",
    description: undefined,
    hidden: undefined,
    title: "Variant",
  },
  ondBO5XoSB_Change: { changes: "dBO5XoSB_", type: ControlType.ChangeHandler },
});
addFonts(
  FramerMxAqgr1h9,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...ColorFonts,
    ...FC_CatalogSearchFonts,
    ...FiltersIconFonts,
    ...FiltersFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
FramerMxAqgr1h9.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([
      forwardLoader(Color, {}, context),
      forwardLoader(FiltersIcon, {}, context),
      forwardLoader(Filters, {}, context),
    ]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerMxAqgr1h9",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerIntrinsicWidth: "380",
        framerVariables:
          '{"fJs5OXAyl":"click","h2n3HL6ZZ":"phhone","dBO5XoSB_":"variant1"}',
        framerColorSyntax: "true",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "43",
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"Djvac8jsu":{"layout":["fixed","fixed"]},"WYU6HAnEy":{"layout":["fixed","fixed"]}}}',
        framerComponentViewportWidth: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
