// Generated by Framer (747ab96)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  getPropertyControls,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import FC_ProductPurchaseButton from "https://framerusercontent.com/modules/DfixsupJND2Hhr1xcPbk/zYiTTDRsHtf2S3Zf8E7G/FC_ProductPurchaseButton.js";
import LocalAddToCartButton from "https://framerusercontent.com/modules/qg4EgpUrpx1iiMAUCgpV/9CByzl9udjfPmhlRscoN/QadYJsDgs.js";
const LocalAddToCartButtonFonts = getFonts(LocalAddToCartButton);
const FC_ProductPurchaseButtonFonts = getFonts(FC_ProductPurchaseButton);
const LocalAddToCartButtonControls = getPropertyControls(LocalAddToCartButton);
const serializationHash = "framer-6ih1H";
const variantClassNames = { Vr0t4NKJ8: "framer-v-122noy2" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const gzPkfrIbf = undefined;
const CtxbSorek = undefined;
const KAtvUtyrK = undefined;
const hy4g4M03K = undefined;
const sz3meCcyG = undefined;
const PsI3Mly3J = undefined;
const setgzPkfrIbf = undefined;
const setsz3meCcyG = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const convertFromBoolean = (value, activeLocale) => {
  return value ? "y6qGS0hDS" : "y6qGS0hDS";
};
const numberToPixelString = (value) => {
  if (typeof value !== "number") return value;
  if (!Number.isFinite(value)) return undefined;
  return Math.max(0, value) + "px";
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableEnumMap = {
  "Space Around": "space-around",
  "Space Between": "space-between",
  "Space Evenly": "space-evenly",
  Center: "center",
  End: "flex-end",
  Start: "flex-start",
};
const useStateVariable = (externalState, setExternalState) => {
  const [internalState, setInternalState] = React.useState(externalState);
  const [previousExternalState, setPreviousExternalState] =
    React.useState(externalState);
  if (setExternalState) {
    return [externalState, setExternalState];
  }
  if (externalState !== previousExternalState) {
    setInternalState(externalState);
    setPreviousExternalState(externalState);
  }
  return [internalState, setInternalState];
};
const getProps = ({
  distribute,
  fCProductPrice,
  height,
  id,
  padding,
  productID,
  quickAdd,
  skipLoading,
  width,
  ...props
}) => {
  return {
    ...props,
    CtxbSorek: skipLoading ?? props.CtxbSorek,
    gzPkfrIbf: productID ?? props.gzPkfrIbf ?? "9914855981350",
    hy4g4M03K: padding ?? props.hy4g4M03K ?? "16px 24px 16px 24px",
    KAtvUtyrK: quickAdd ?? props.KAtvUtyrK,
    PsI3Mly3J:
      humanReadableEnumMap[distribute] ??
      distribute ??
      props.PsI3Mly3J ??
      "space-between",
    sz3meCcyG: fCProductPrice ?? props.sz3meCcyG ?? true,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    gzPkfrIbf: externalgzPkfrIbf,
    ongzPkfrIbfChange: setExternalgzPkfrIbf,
    CtxbSorek,
    KAtvUtyrK,
    hy4g4M03K,
    sz3meCcyG: externalsz3meCcyG,
    onsz3meCcyGChange: setExternalsz3meCcyG,
    PsI3Mly3J,
    ...restProps
  } = getProps(props);
  const [gzPkfrIbf, setgzPkfrIbf] = useStateVariable(
    externalgzPkfrIbf,
    setExternalgzPkfrIbf
  );
  const [sz3meCcyG, setsz3meCcyG] = useStateVariable(
    externalsz3meCcyG,
    setExternalsz3meCcyG
  );
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "Vr0t4NKJ8",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-122noy2",
            className,
            classNames
          ),
          "data-framer-name": "Default",
          layoutDependency: layoutDependency,
          layoutId: "Vr0t4NKJ8",
          ref: refBinding,
          style: { ...style },
          children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
              className: "framer-1nybgun-container",
              isAuthoredByUser: true,
              isModuleExternal: true,
              layoutDependency: layoutDependency,
              layoutId: "QLXqLB4BU-container",
              nodeId: "QLXqLB4BU",
              rendersWithMotion: true,
              scopeId: "mKpITaYPo",
              children: /*#__PURE__*/ _jsx(FC_ProductPurchaseButton, {
                available: [
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-rtrvcp",
                    "data-framer-name": "Available",
                    layoutDependency: layoutDependency,
                    layoutId: "n2Z3jwfU3",
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 56,
                      width: "400px",
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainer,
                        {
                          className: "framer-2yojai-container",
                          inComponentSlot: true,
                          layoutDependency: layoutDependency,
                          layoutId: "gbGxMufjE-container",
                          nodeId: "gbGxMufjE",
                          rendersWithMotion: true,
                          scopeId: "mKpITaYPo",
                          children: /*#__PURE__*/ _jsx(LocalAddToCartButton, {
                            cmsD3sS5M: numberToPixelString(hy4g4M03K),
                            elgRTGdr9: gzPkfrIbf,
                            height: "100%",
                            id: "gbGxMufjE",
                            layoutId: "gbGxMufjE",
                            onelgRTGdr9Change: setgzPkfrIbf,
                            onUk2AIFMgoChange: setsz3meCcyG,
                            style: { height: "100%", width: "100%" },
                            Uk2AIFMgo: sz3meCcyG,
                            variant: matchVariant(
                              convertFromBoolean(KAtvUtyrK, activeLocale)
                            ),
                            width: "100%",
                            yS66DEJm4: PsI3Mly3J,
                          }),
                        }
                      ),
                    }),
                  }),
                ],
                BuyNowATC: false,
                focus: {
                  color: "rgba(255, 255, 255, 0)",
                  padding: 2,
                  radius: 8,
                  width: 0,
                },
                height: "100%",
                id: "QLXqLB4BU",
                layoutId: "QLXqLB4BU",
                LoadingState: [
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-12zxtw6",
                    "data-framer-name": "Loading",
                    layoutDependency: layoutDependency,
                    layoutId: "peuyaTubN",
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 56,
                      width: "400px",
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainer,
                        {
                          className: "framer-r40z9c-container",
                          inComponentSlot: true,
                          layoutDependency: layoutDependency,
                          layoutId: "SOOx8mtj1-container",
                          nodeId: "SOOx8mtj1",
                          rendersWithMotion: true,
                          scopeId: "mKpITaYPo",
                          children: /*#__PURE__*/ _jsx(LocalAddToCartButton, {
                            cmsD3sS5M: "16px 24px 16px 24px",
                            elgRTGdr9: gzPkfrIbf,
                            height: "100%",
                            id: "SOOx8mtj1",
                            layoutId: "SOOx8mtj1",
                            onelgRTGdr9Change: setgzPkfrIbf,
                            style: { height: "100%", width: "100%" },
                            Uk2AIFMgo: true,
                            variant: matchVariant("t0nmmsydE"),
                            width: "100%",
                            yS66DEJm4: "space-between",
                          }),
                        }
                      ),
                    }),
                  }),
                ],
                maxQuantity: [],
                openCart: true,
                OutOfStock: [
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-1b7kes1",
                    "data-framer-name": "Out of Stock",
                    layoutDependency: layoutDependency,
                    layoutId: "CAWi2SS0A",
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 56,
                      width: "400px",
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainer,
                        {
                          className: "framer-eankls-container",
                          inComponentSlot: true,
                          layoutDependency: layoutDependency,
                          layoutId: "ia1HIF5uR-container",
                          nodeId: "ia1HIF5uR",
                          rendersWithMotion: true,
                          scopeId: "mKpITaYPo",
                          children: /*#__PURE__*/ _jsx(LocalAddToCartButton, {
                            cmsD3sS5M: "16px 24px 16px 24px",
                            elgRTGdr9: gzPkfrIbf,
                            height: "100%",
                            id: "ia1HIF5uR",
                            layoutId: "ia1HIF5uR",
                            onelgRTGdr9Change: setgzPkfrIbf,
                            style: { height: "100%", width: "100%" },
                            Uk2AIFMgo: true,
                            variant: matchVariant("Er2IJZSRf"),
                            width: "100%",
                            yS66DEJm4: "space-between",
                          }),
                        }
                      ),
                    }),
                  }),
                ],
                SelectVariant: [
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-1d3qs66",
                    "data-framer-name": "Select Variant",
                    layoutDependency: layoutDependency,
                    layoutId: "E6fGsqaso",
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 56,
                      width: "400px",
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainer,
                        {
                          className: "framer-m3jocx-container",
                          inComponentSlot: true,
                          layoutDependency: layoutDependency,
                          layoutId: "sH9KYPTAQ-container",
                          nodeId: "sH9KYPTAQ",
                          rendersWithMotion: true,
                          scopeId: "mKpITaYPo",
                          children: /*#__PURE__*/ _jsx(LocalAddToCartButton, {
                            cmsD3sS5M: "16px 24px 16px 24px",
                            elgRTGdr9: gzPkfrIbf,
                            height: "100%",
                            id: "sH9KYPTAQ",
                            layoutId: "sH9KYPTAQ",
                            onelgRTGdr9Change: setgzPkfrIbf,
                            style: { height: "100%", width: "100%" },
                            Uk2AIFMgo: true,
                            variant: matchVariant("FAfWZpnsd"),
                            width: "100%",
                            yS66DEJm4: "space-between",
                          }),
                        }
                      ),
                    }),
                  }),
                ],
                shopifyProductID: gzPkfrIbf,
                shopifyProductVariantId: "",
                skipLoading: CtxbSorek,
                style: { height: "100%", width: "100%" },
                width: "100%",
              }),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-6ih1H.framer-l9fw12, .framer-6ih1H .framer-l9fw12 { display: block; }",
  ".framer-6ih1H.framer-122noy2 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 56px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 400px; }",
  ".framer-6ih1H .framer-1nybgun-container, .framer-6ih1H .framer-r40z9c-container, .framer-6ih1H .framer-2yojai-container, .framer-6ih1H .framer-m3jocx-container, .framer-6ih1H .framer-eankls-container { flex: 1 0 0px; height: 100%; position: relative; width: 1px; }",
  ".framer-6ih1H .framer-12zxtw6, .framer-6ih1H .framer-rtrvcp, .framer-6ih1H .framer-1d3qs66, .framer-6ih1H .framer-1b7kes1 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 56px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 400px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 56
 * @framerIntrinsicWidth 400
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"gzPkfrIbf":"productID","CtxbSorek":"skipLoading","KAtvUtyrK":"quickAdd","hy4g4M03K":"padding","sz3meCcyG":"fCProductPrice","PsI3Mly3J":"distribute"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramermKpITaYPo = withCSS(Component, css, "framer-6ih1H");
export default FramermKpITaYPo;
FramermKpITaYPo.displayName = "FCAddToCartButton";
FramermKpITaYPo.defaultProps = { height: 56, width: 400 };
addPropertyControls(FramermKpITaYPo, {
  gzPkfrIbf: {
    defaultValue: "9914855981350",
    title: "Product ID",
    type: ControlType.String,
  },
  ongzPkfrIbfChange: { changes: "gzPkfrIbf", type: ControlType.ChangeHandler },
  CtxbSorek: {
    defaultValue: false,
    title: "Skip Loading",
    type: ControlType.Boolean,
  },
  onCtxbSorekChange: { changes: "CtxbSorek", type: ControlType.ChangeHandler },
  KAtvUtyrK: {
    defaultValue: false,
    title: "Quick Add",
    type: ControlType.Boolean,
  },
  onKAtvUtyrKChange: { changes: "KAtvUtyrK", type: ControlType.ChangeHandler },
  hy4g4M03K: {
    defaultValue: "16px 24px 16px 24px",
    title: "Padding",
    type: ControlType.Padding,
  },
  sz3meCcyG: {
    defaultValue: true,
    title: "FC Product Price",
    type: ControlType.Boolean,
  },
  onsz3meCcyGChange: { changes: "sz3meCcyG", type: ControlType.ChangeHandler },
  PsI3Mly3J: LocalAddToCartButtonControls?.["yS66DEJm4"] && {
    ...LocalAddToCartButtonControls["yS66DEJm4"],
    defaultValue: "space-between",
    description: undefined,
    hidden: undefined,
    title: "Distribute",
  },
  onPsI3Mly3JChange: { changes: "PsI3Mly3J", type: ControlType.ChangeHandler },
});
addFonts(
  FramermKpITaYPo,
  [
    { explicitInter: true, fonts: [] },
    ...LocalAddToCartButtonFonts,
    ...FC_ProductPurchaseButtonFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
FramermKpITaYPo.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([
      forwardLoader(LocalAddToCartButton, {}, context),
    ]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramermKpITaYPo",
      slots: [],
      annotations: {
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
        framerColorSyntax: "true",
        framerContractVersion: "1",
        framerVariables:
          '{"gzPkfrIbf":"productID","CtxbSorek":"skipLoading","KAtvUtyrK":"quickAdd","hy4g4M03K":"padding","sz3meCcyG":"fCProductPrice","PsI3Mly3J":"distribute"}',
        framerIntrinsicWidth: "400",
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "56",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}',
        framerAutoSizeImages: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
