// Generated by Framer (747ab96)
import {
  jsx as _jsx,
  jsxs as _jsxs,
  Fragment as _Fragment,
} from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ChildrenCanSuspend,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  PathVariablesContext,
  ResolveLinks,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useQueryData,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Slideshow from "https://framerusercontent.com/modules/zvkTOpMSuRzRhLzZZIwG/7GuSIJ2Jm6VU0TIDHoiR/SlideShow.js";
import LiquidGlass from "https://framerusercontent.com/modules/nWF9VlLpiUQ40CNNnERS/C8AeagCGr9kQJpSgRqt5/LiquidGlass.js";
import FramerCommerce from "https://framerusercontent.com/modules/NIDRWPDT7EU8B75S563e/tLKcnMpG87E5mncNQNM6/Gk472MYtJ.js";
import ProductCardMini from "https://framerusercontent.com/modules/yDEdOW45d5j14TwVZN9h/XLR8zemNgnTKw4pyf6Dc/S2IBx96wZ.js";
const ProductCardMiniFonts = getFonts(ProductCardMini);
const SlideshowFonts = getFonts(Slideshow);
const LiquidGlassFonts = getFonts(LiquidGlass);
const serializationHash = "framer-7D8Be";
const variantClassNames = { iN2xDKx6h: "framer-v-qd67kd" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const RMwVI8LUMwen5ES8ym = undefined;
const tZaiMnhUswen5ES8ym = undefined;
const AHNguEn6Hwen5ES8ym = undefined;
const UKXz5hUjDwen5ES8ym = undefined;
const VQ05ydvuVwen5ES8ym = undefined;
const NPclJ_YtQwen5ES8ym = undefined;
const idwen5ES8ym = undefined;
const yjSQJXcWe = undefined;
const RMwVI8LUMXEpz7nHKM = undefined;
const tZaiMnhUsXEpz7nHKM = undefined;
const AHNguEn6HXEpz7nHKM = undefined;
const UKXz5hUjDXEpz7nHKM = undefined;
const VQ05ydvuVXEpz7nHKM = undefined;
const NPclJ_YtQXEpz7nHKM = undefined;
const idXEpz7nHKM = undefined;
const RMwVI8LUMYRWYlG_38 = undefined;
const tZaiMnhUsYRWYlG_38 = undefined;
const AHNguEn6HYRWYlG_38 = undefined;
const UKXz5hUjDYRWYlG_38 = undefined;
const VQ05ydvuVYRWYlG_38 = undefined;
const NPclJ_YtQYRWYlG_38 = undefined;
const idYRWYlG_38 = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const equals = (a, b) => {
  return typeof a === "string" && typeof b === "string"
    ? a.toLowerCase() === b.toLowerCase()
    : a === b;
};
const convertFromBoolean = (value, activeLocale, { NPclJ_YtQwen5ES8ym }) => {
  return value
    ? {
        pathVariables: { NPclJ_YtQ: NPclJ_YtQwen5ES8ym },
        webPageId: "nw9I3LuHj",
      }
    : {
        pathVariables: { NPclJ_YtQ: NPclJ_YtQwen5ES8ym },
        webPageId: "hhdNRaMaX",
      };
};
const query = (prequery, { yjSQJXcWe }) =>
  prequery({
    from: { alias: "wen5ES8ym", data: FramerCommerce, type: "Collection" },
    limit: { type: "LiteralValue", value: 1 },
    orderBy: [
      {
        collection: "wen5ES8ym",
        direction: "desc",
        name: "tZaiMnhUs",
        type: "Identifier",
      },
    ],
    select: [
      { collection: "wen5ES8ym", name: "RMwVI8LUM", type: "Identifier" },
      { collection: "wen5ES8ym", name: "tZaiMnhUs", type: "Identifier" },
      { collection: "wen5ES8ym", name: "AHNguEn6H", type: "Identifier" },
      { collection: "wen5ES8ym", name: "UKXz5hUjD", type: "Identifier" },
      { collection: "wen5ES8ym", name: "VQ05ydvuV", type: "Identifier" },
      { collection: "wen5ES8ym", name: "NPclJ_YtQ", type: "Identifier" },
      { collection: "wen5ES8ym", name: "id", type: "Identifier" },
    ],
    where: {
      left: { collection: "wen5ES8ym", name: "VQ05ydvuV", type: "Identifier" },
      operator: "==",
      right: { type: "LiteralValue", value: yjSQJXcWe },
      type: "BinaryOperation",
    },
  });
const query1 = (yjSQJXcWe) => ({
  from: { alias: "wen5ES8ym", data: FramerCommerce, type: "Collection" },
  limit: { type: "LiteralValue", value: 1 },
  orderBy: [
    {
      collection: "wen5ES8ym",
      direction: "desc",
      name: "tZaiMnhUs",
      type: "Identifier",
    },
  ],
  select: [
    { collection: "wen5ES8ym", name: "RMwVI8LUM", type: "Identifier" },
    { collection: "wen5ES8ym", name: "tZaiMnhUs", type: "Identifier" },
    { collection: "wen5ES8ym", name: "AHNguEn6H", type: "Identifier" },
    { collection: "wen5ES8ym", name: "UKXz5hUjD", type: "Identifier" },
    { collection: "wen5ES8ym", name: "VQ05ydvuV", type: "Identifier" },
    { collection: "wen5ES8ym", name: "NPclJ_YtQ", type: "Identifier" },
    { collection: "wen5ES8ym", name: "id", type: "Identifier" },
  ],
  where: {
    left: { collection: "wen5ES8ym", name: "VQ05ydvuV", type: "Identifier" },
    operator: "==",
    right: { type: "LiteralValue", value: yjSQJXcWe },
    type: "BinaryOperation",
  },
});
const QueryData = ({ query, pageSize, children }) => {
  const data = useQueryData(query);
  return children(data);
};
const convertFromBoolean1 = (value, activeLocale, { NPclJ_YtQXEpz7nHKM }) => {
  return value
    ? {
        pathVariables: { NPclJ_YtQ: NPclJ_YtQXEpz7nHKM },
        webPageId: "nw9I3LuHj",
      }
    : {
        pathVariables: { NPclJ_YtQ: NPclJ_YtQXEpz7nHKM },
        webPageId: "hhdNRaMaX",
      };
};
const query2 = (prequery, { yjSQJXcWe }) =>
  prequery({
    from: { alias: "XEpz7nHKM", data: FramerCommerce, type: "Collection" },
    limit: { type: "LiteralValue", value: 1 },
    orderBy: [
      {
        collection: "XEpz7nHKM",
        direction: "desc",
        name: "RMwVI8LUM",
        type: "Identifier",
      },
    ],
    select: [
      { collection: "XEpz7nHKM", name: "RMwVI8LUM", type: "Identifier" },
      { collection: "XEpz7nHKM", name: "tZaiMnhUs", type: "Identifier" },
      { collection: "XEpz7nHKM", name: "AHNguEn6H", type: "Identifier" },
      { collection: "XEpz7nHKM", name: "UKXz5hUjD", type: "Identifier" },
      { collection: "XEpz7nHKM", name: "VQ05ydvuV", type: "Identifier" },
      { collection: "XEpz7nHKM", name: "NPclJ_YtQ", type: "Identifier" },
      { collection: "XEpz7nHKM", name: "id", type: "Identifier" },
    ],
    where: {
      left: { collection: "XEpz7nHKM", name: "VQ05ydvuV", type: "Identifier" },
      operator: "==",
      right: { type: "LiteralValue", value: yjSQJXcWe },
      type: "BinaryOperation",
    },
  });
const query3 = (yjSQJXcWe) => ({
  from: { alias: "XEpz7nHKM", data: FramerCommerce, type: "Collection" },
  limit: { type: "LiteralValue", value: 1 },
  orderBy: [
    {
      collection: "XEpz7nHKM",
      direction: "desc",
      name: "RMwVI8LUM",
      type: "Identifier",
    },
  ],
  select: [
    { collection: "XEpz7nHKM", name: "RMwVI8LUM", type: "Identifier" },
    { collection: "XEpz7nHKM", name: "tZaiMnhUs", type: "Identifier" },
    { collection: "XEpz7nHKM", name: "AHNguEn6H", type: "Identifier" },
    { collection: "XEpz7nHKM", name: "UKXz5hUjD", type: "Identifier" },
    { collection: "XEpz7nHKM", name: "VQ05ydvuV", type: "Identifier" },
    { collection: "XEpz7nHKM", name: "NPclJ_YtQ", type: "Identifier" },
    { collection: "XEpz7nHKM", name: "id", type: "Identifier" },
  ],
  where: {
    left: { collection: "XEpz7nHKM", name: "VQ05ydvuV", type: "Identifier" },
    operator: "==",
    right: { type: "LiteralValue", value: yjSQJXcWe },
    type: "BinaryOperation",
  },
});
const convertFromBoolean2 = (value, activeLocale, { NPclJ_YtQYRWYlG_38 }) => {
  return value
    ? {
        pathVariables: { NPclJ_YtQ: NPclJ_YtQYRWYlG_38 },
        webPageId: "nw9I3LuHj",
      }
    : {
        pathVariables: { NPclJ_YtQ: NPclJ_YtQYRWYlG_38 },
        webPageId: "hhdNRaMaX",
      };
};
const query4 = (prequery, { yjSQJXcWe }) =>
  prequery({
    from: { alias: "YRWYlG_38", data: FramerCommerce, type: "Collection" },
    limit: { type: "LiteralValue", value: 1 },
    orderBy: [
      { collection: "YRWYlG_38", name: "tZaiMnhUs", type: "Identifier" },
    ],
    select: [
      { collection: "YRWYlG_38", name: "RMwVI8LUM", type: "Identifier" },
      { collection: "YRWYlG_38", name: "tZaiMnhUs", type: "Identifier" },
      { collection: "YRWYlG_38", name: "AHNguEn6H", type: "Identifier" },
      { collection: "YRWYlG_38", name: "UKXz5hUjD", type: "Identifier" },
      { collection: "YRWYlG_38", name: "VQ05ydvuV", type: "Identifier" },
      { collection: "YRWYlG_38", name: "NPclJ_YtQ", type: "Identifier" },
      { collection: "YRWYlG_38", name: "id", type: "Identifier" },
    ],
    where: {
      left: { collection: "YRWYlG_38", name: "VQ05ydvuV", type: "Identifier" },
      operator: "==",
      right: { type: "LiteralValue", value: yjSQJXcWe },
      type: "BinaryOperation",
    },
  });
const query5 = (yjSQJXcWe) => ({
  from: { alias: "YRWYlG_38", data: FramerCommerce, type: "Collection" },
  limit: { type: "LiteralValue", value: 1 },
  orderBy: [{ collection: "YRWYlG_38", name: "tZaiMnhUs", type: "Identifier" }],
  select: [
    { collection: "YRWYlG_38", name: "RMwVI8LUM", type: "Identifier" },
    { collection: "YRWYlG_38", name: "tZaiMnhUs", type: "Identifier" },
    { collection: "YRWYlG_38", name: "AHNguEn6H", type: "Identifier" },
    { collection: "YRWYlG_38", name: "UKXz5hUjD", type: "Identifier" },
    { collection: "YRWYlG_38", name: "VQ05ydvuV", type: "Identifier" },
    { collection: "YRWYlG_38", name: "NPclJ_YtQ", type: "Identifier" },
    { collection: "YRWYlG_38", name: "id", type: "Identifier" },
  ],
  where: {
    left: { collection: "YRWYlG_38", name: "VQ05ydvuV", type: "Identifier" },
    operator: "==",
    right: { type: "LiteralValue", value: yjSQJXcWe },
    type: "BinaryOperation",
  },
});
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ filter, height, id, width, ...props }) => {
  return { ...props, yjSQJXcWe: filter ?? props.yjSQJXcWe ?? "Men" };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, yjSQJXcWe, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "iN2xDKx6h",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-qd67kd",
            className,
            classNames
          ),
          "data-border": true,
          "data-framer-name": "Variant 1",
          layoutDependency: layoutDependency,
          layoutId: "iN2xDKx6h",
          ref: refBinding,
          style: {
            "--border-bottom-width": "1px",
            "--border-color": "rgba(255, 255, 255, 0.3)",
            "--border-left-width": "1px",
            "--border-right-width": "1px",
            "--border-style": "solid",
            "--border-top-width": "1px",
            backdropFilter: "blur(10px)",
            backgroundColor: "rgba(255, 255, 255, 0.2)",
            borderBottomLeftRadius: 12,
            borderBottomRightRadius: 12,
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            boxShadow: "inset 1px 3px 1px 0px rgba(255, 255, 255, 0.2)",
            WebkitBackdropFilter: "blur(10px)",
            ...style,
          },
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-7sfw71-container",
                isAuthoredByUser: true,
                isModuleExternal: true,
                layoutDependency: layoutDependency,
                layoutId: "fPGYXLTC2-container",
                nodeId: "fPGYXLTC2",
                rendersWithMotion: true,
                scopeId: "s7fCBlzGM",
                children: /*#__PURE__*/ _jsx(Slideshow, {
                  alignment: "center",
                  arrowOptions: {
                    arrowFill: "rgba(0, 0, 0, 0.2)",
                    arrowGap: 10,
                    arrowPadding: 20,
                    arrowPaddingBottom: 0,
                    arrowPaddingLeft: 0,
                    arrowPaddingRight: 0,
                    arrowPaddingTop: 0,
                    arrowPosition: "auto",
                    arrowRadius: 40,
                    arrowShouldFadeIn: false,
                    arrowShouldSpace: true,
                    arrowSize: 40,
                    showMouseControls: false,
                  },
                  autoPlayControl: true,
                  borderRadius: 0,
                  direction: "top",
                  dragControl: false,
                  effectsOptions: {
                    effectsHover: true,
                    effectsOpacity: 1,
                    effectsPerspective: 1200,
                    effectsRotate: 0,
                    effectsScale: 1,
                    playOffscreen: false,
                  },
                  fadeOptions: {
                    fadeAlpha: 0,
                    fadeContent: false,
                    fadeInset: 0,
                    fadeWidth: 25,
                    overflow: false,
                  },
                  gap: 0,
                  height: "100%",
                  id: "fPGYXLTC2",
                  intervalControl: 4,
                  itemAmount: 1,
                  layoutId: "fPGYXLTC2",
                  padding: 0,
                  paddingBottom: 0,
                  paddingLeft: 0,
                  paddingPerSide: false,
                  paddingRight: 0,
                  paddingTop: 0,
                  progressOptions: {
                    dotsActiveOpacity: 1,
                    dotsBackground: "rgba(0, 0, 0, 0.2)",
                    dotsBlur: 0,
                    dotsFill: "rgb(255, 255, 255)",
                    dotsGap: 10,
                    dotsInset: 10,
                    dotSize: 10,
                    dotsOpacity: 0.5,
                    dotsPadding: 10,
                    dotsRadius: 50,
                    showProgressDots: false,
                  },
                  slots: [
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-ch8sps",
                      layoutDependency: layoutDependency,
                      layoutId: "wen5ES8ym",
                      children: /*#__PURE__*/ _jsx(ChildrenCanSuspend, {
                        children: /*#__PURE__*/ _jsx(QueryData, {
                          query: query1(yjSQJXcWe),
                          children: (collection, paginationInfo, loadMore) => {
                            return /*#__PURE__*/ _jsx(_Fragment, {
                              children: collection?.map(
                                (
                                  {
                                    AHNguEn6H: AHNguEn6Hwen5ES8ym,
                                    id: idwen5ES8ym,
                                    NPclJ_YtQ: NPclJ_YtQwen5ES8ym,
                                    RMwVI8LUM: RMwVI8LUMwen5ES8ym,
                                    tZaiMnhUs: tZaiMnhUswen5ES8ym,
                                    UKXz5hUjD: UKXz5hUjDwen5ES8ym,
                                    VQ05ydvuV: VQ05ydvuVwen5ES8ym,
                                  },
                                  index
                                ) => {
                                  RMwVI8LUMwen5ES8ym ??= "";
                                  tZaiMnhUswen5ES8ym ??= "";
                                  UKXz5hUjDwen5ES8ym ??= "";
                                  VQ05ydvuVwen5ES8ym ??= "";
                                  NPclJ_YtQwen5ES8ym ??= "";
                                  return /*#__PURE__*/ _jsx(
                                    LayoutGroup,
                                    {
                                      id: `wen5ES8ym-${idwen5ES8ym}`,
                                      children: /*#__PURE__*/ _jsx(
                                        PathVariablesContext.Provider,
                                        {
                                          value: {
                                            NPclJ_YtQ: NPclJ_YtQwen5ES8ym,
                                          },
                                          children: /*#__PURE__*/ _jsx(
                                            ResolveLinks,
                                            {
                                              links: [
                                                {
                                                  href: convertFromBoolean(
                                                    equals(
                                                      VQ05ydvuVwen5ES8ym,
                                                      "men"
                                                    ),
                                                    activeLocale,
                                                    { NPclJ_YtQwen5ES8ym }
                                                  ),
                                                  implicitPathVariables:
                                                    undefined,
                                                },
                                              ],
                                              children: (resolvedLinks) =>
                                                /*#__PURE__*/ _jsx(
                                                  ComponentViewportProvider,
                                                  {
                                                    height: 86,
                                                    width: "352px",
                                                    children:
                                                      /*#__PURE__*/ _jsx(
                                                        SmartComponentScopedContainer,
                                                        {
                                                          className:
                                                            "framer-sve2a7-container",
                                                          inComponentSlot: true,
                                                          layoutDependency:
                                                            layoutDependency,
                                                          layoutId:
                                                            "TjegM5LOB-container",
                                                          nodeId: "TjegM5LOB",
                                                          rendersWithMotion: true,
                                                          scopeId: "s7fCBlzGM",
                                                          children:
                                                            /*#__PURE__*/ _jsx(
                                                              ProductCardMini,
                                                              {
                                                                height: "100%",
                                                                hUiG43MWH:
                                                                  UKXz5hUjDwen5ES8ym,
                                                                id: "TjegM5LOB",
                                                                imMJrf0iF:
                                                                  RMwVI8LUMwen5ES8ym,
                                                                Ku3hhIByx:
                                                                  tZaiMnhUswen5ES8ym,
                                                                layoutId:
                                                                  "TjegM5LOB",
                                                                MCamkPOH3:
                                                                  resolvedLinks[0],
                                                                SmdWZSpRL:
                                                                  toResponsiveImage(
                                                                    AHNguEn6Hwen5ES8ym
                                                                  ),
                                                                style: {
                                                                  width: "100%",
                                                                },
                                                                width: "100%",
                                                              }
                                                            ),
                                                        }
                                                      ),
                                                  }
                                                ),
                                            }
                                          ),
                                        }
                                      ),
                                    },
                                    idwen5ES8ym
                                  );
                                }
                              ),
                            });
                          },
                        }),
                      }),
                    }),
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1qe8wib",
                      layoutDependency: layoutDependency,
                      layoutId: "XEpz7nHKM",
                      children: /*#__PURE__*/ _jsx(ChildrenCanSuspend, {
                        children: /*#__PURE__*/ _jsx(QueryData, {
                          query: query3(yjSQJXcWe),
                          children: (
                            collection1,
                            paginationInfo1,
                            loadMore1
                          ) => {
                            return /*#__PURE__*/ _jsx(_Fragment, {
                              children: collection1?.map(
                                (
                                  {
                                    AHNguEn6H: AHNguEn6HXEpz7nHKM,
                                    id: idXEpz7nHKM,
                                    NPclJ_YtQ: NPclJ_YtQXEpz7nHKM,
                                    RMwVI8LUM: RMwVI8LUMXEpz7nHKM,
                                    tZaiMnhUs: tZaiMnhUsXEpz7nHKM,
                                    UKXz5hUjD: UKXz5hUjDXEpz7nHKM,
                                    VQ05ydvuV: VQ05ydvuVXEpz7nHKM,
                                  },
                                  index1
                                ) => {
                                  RMwVI8LUMXEpz7nHKM ??= "";
                                  tZaiMnhUsXEpz7nHKM ??= "";
                                  UKXz5hUjDXEpz7nHKM ??= "";
                                  VQ05ydvuVXEpz7nHKM ??= "";
                                  NPclJ_YtQXEpz7nHKM ??= "";
                                  return /*#__PURE__*/ _jsx(
                                    LayoutGroup,
                                    {
                                      id: `XEpz7nHKM-${idXEpz7nHKM}`,
                                      children: /*#__PURE__*/ _jsx(
                                        PathVariablesContext.Provider,
                                        {
                                          value: {
                                            NPclJ_YtQ: NPclJ_YtQXEpz7nHKM,
                                          },
                                          children: /*#__PURE__*/ _jsx(
                                            ResolveLinks,
                                            {
                                              links: [
                                                {
                                                  href: convertFromBoolean1(
                                                    equals(
                                                      VQ05ydvuVXEpz7nHKM,
                                                      "Men"
                                                    ),
                                                    activeLocale,
                                                    { NPclJ_YtQXEpz7nHKM }
                                                  ),
                                                  implicitPathVariables:
                                                    undefined,
                                                },
                                              ],
                                              children: (resolvedLinks1) =>
                                                /*#__PURE__*/ _jsx(
                                                  ComponentViewportProvider,
                                                  {
                                                    height: 86,
                                                    width: "365px",
                                                    children:
                                                      /*#__PURE__*/ _jsx(
                                                        SmartComponentScopedContainer,
                                                        {
                                                          className:
                                                            "framer-zu6e2m-container",
                                                          inComponentSlot: true,
                                                          layoutDependency:
                                                            layoutDependency,
                                                          layoutId:
                                                            "Kw8bsrSww-container",
                                                          nodeId: "Kw8bsrSww",
                                                          rendersWithMotion: true,
                                                          scopeId: "s7fCBlzGM",
                                                          children:
                                                            /*#__PURE__*/ _jsx(
                                                              ProductCardMini,
                                                              {
                                                                height: "100%",
                                                                hUiG43MWH:
                                                                  UKXz5hUjDXEpz7nHKM,
                                                                id: "Kw8bsrSww",
                                                                imMJrf0iF:
                                                                  RMwVI8LUMXEpz7nHKM,
                                                                Ku3hhIByx:
                                                                  tZaiMnhUsXEpz7nHKM,
                                                                layoutId:
                                                                  "Kw8bsrSww",
                                                                MCamkPOH3:
                                                                  resolvedLinks1[0],
                                                                SmdWZSpRL:
                                                                  toResponsiveImage(
                                                                    AHNguEn6HXEpz7nHKM
                                                                  ),
                                                                style: {
                                                                  width: "100%",
                                                                },
                                                                width: "100%",
                                                              }
                                                            ),
                                                        }
                                                      ),
                                                  }
                                                ),
                                            }
                                          ),
                                        }
                                      ),
                                    },
                                    idXEpz7nHKM
                                  );
                                }
                              ),
                            });
                          },
                        }),
                      }),
                    }),
                    /*#__PURE__*/ _jsx(motion.div, {
                      className: "framer-1k0z85q",
                      layoutDependency: layoutDependency,
                      layoutId: "YRWYlG_38",
                      children: /*#__PURE__*/ _jsx(ChildrenCanSuspend, {
                        children: /*#__PURE__*/ _jsx(QueryData, {
                          query: query5(yjSQJXcWe),
                          children: (
                            collection2,
                            paginationInfo2,
                            loadMore2
                          ) => {
                            return /*#__PURE__*/ _jsx(_Fragment, {
                              children: collection2?.map(
                                (
                                  {
                                    AHNguEn6H: AHNguEn6HYRWYlG_38,
                                    id: idYRWYlG_38,
                                    NPclJ_YtQ: NPclJ_YtQYRWYlG_38,
                                    RMwVI8LUM: RMwVI8LUMYRWYlG_38,
                                    tZaiMnhUs: tZaiMnhUsYRWYlG_38,
                                    UKXz5hUjD: UKXz5hUjDYRWYlG_38,
                                    VQ05ydvuV: VQ05ydvuVYRWYlG_38,
                                  },
                                  index2
                                ) => {
                                  RMwVI8LUMYRWYlG_38 ??= "";
                                  tZaiMnhUsYRWYlG_38 ??= "";
                                  UKXz5hUjDYRWYlG_38 ??= "";
                                  VQ05ydvuVYRWYlG_38 ??= "";
                                  NPclJ_YtQYRWYlG_38 ??= "";
                                  return /*#__PURE__*/ _jsx(
                                    LayoutGroup,
                                    {
                                      id: `YRWYlG_38-${idYRWYlG_38}`,
                                      children: /*#__PURE__*/ _jsx(
                                        PathVariablesContext.Provider,
                                        {
                                          value: {
                                            NPclJ_YtQ: NPclJ_YtQYRWYlG_38,
                                          },
                                          children: /*#__PURE__*/ _jsx(
                                            ResolveLinks,
                                            {
                                              links: [
                                                {
                                                  href: convertFromBoolean2(
                                                    equals(
                                                      VQ05ydvuVYRWYlG_38,
                                                      "Men"
                                                    ),
                                                    activeLocale,
                                                    { NPclJ_YtQYRWYlG_38 }
                                                  ),
                                                  implicitPathVariables:
                                                    undefined,
                                                },
                                              ],
                                              children: (resolvedLinks2) =>
                                                /*#__PURE__*/ _jsx(
                                                  ComponentViewportProvider,
                                                  {
                                                    height: 86,
                                                    width: "365px",
                                                    children:
                                                      /*#__PURE__*/ _jsx(
                                                        SmartComponentScopedContainer,
                                                        {
                                                          className:
                                                            "framer-17q2ucy-container",
                                                          inComponentSlot: true,
                                                          layoutDependency:
                                                            layoutDependency,
                                                          layoutId:
                                                            "jp5AB4xAX-container",
                                                          nodeId: "jp5AB4xAX",
                                                          rendersWithMotion: true,
                                                          scopeId: "s7fCBlzGM",
                                                          children:
                                                            /*#__PURE__*/ _jsx(
                                                              ProductCardMini,
                                                              {
                                                                height: "100%",
                                                                hUiG43MWH:
                                                                  UKXz5hUjDYRWYlG_38,
                                                                id: "jp5AB4xAX",
                                                                imMJrf0iF:
                                                                  RMwVI8LUMYRWYlG_38,
                                                                Ku3hhIByx:
                                                                  tZaiMnhUsYRWYlG_38,
                                                                layoutId:
                                                                  "jp5AB4xAX",
                                                                MCamkPOH3:
                                                                  resolvedLinks2[0],
                                                                SmdWZSpRL:
                                                                  toResponsiveImage(
                                                                    AHNguEn6HYRWYlG_38
                                                                  ),
                                                                style: {
                                                                  width: "100%",
                                                                },
                                                                width: "100%",
                                                              }
                                                            ),
                                                        }
                                                      ),
                                                  }
                                                ),
                                            }
                                          ),
                                        }
                                      ),
                                    },
                                    idYRWYlG_38
                                  );
                                }
                              ),
                            });
                          },
                        }),
                      }),
                    }),
                  ],
                  startFrom: 0,
                  style: { height: "100%", width: "100%" },
                  transitionControl: {
                    delay: 0,
                    duration: 0.6,
                    ease: [0.44, 0, 0.56, 1],
                    type: "tween",
                  },
                  width: "100%",
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-1qtam8r-container",
                "data-code-component-plugin-id": "84d4c1",
                isAuthoredByUser: true,
                layoutDependency: layoutDependency,
                layoutId: "yxv8vrgCC-container",
                nodeId: "yxv8vrgCC",
                rendersWithMotion: true,
                scopeId: "s7fCBlzGM",
                children: /*#__PURE__*/ _jsx(LiquidGlass, {
                  backgroundColor: "rgba(255, 255, 255, 0.1)",
                  blur: 40,
                  blurDirection: "out",
                  borderRadius: 12,
                  glassType: "frosted",
                  gradientAngle: 305,
                  gradientColor1: "rgba(54, 54, 54, 0.29)",
                  gradientColor2: "rgba(148, 122, 95, 0)",
                  gradientIntensity: 1,
                  height: "100%",
                  highlightColor: "rgba(82, 75, 68, 0.25)",
                  highlightIntensity: 0.03,
                  highlightRadius: 65,
                  highlightX: 2,
                  highlightY: 68,
                  id: "yxv8vrgCC",
                  layoutId: "yxv8vrgCC",
                  maxBlur: 40,
                  minBlur: 40,
                  style: { height: "100%", width: "100%" },
                  width: "100%",
                }),
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-7D8Be.framer-14n7bbh, .framer-7D8Be .framer-14n7bbh { display: block; }",
  ".framer-7D8Be.framer-qd67kd { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 325px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-7D8Be .framer-7sfw71-container { flex: 1 0 0px; height: 86px; position: relative; width: 1px; z-index: 1; }",
  ".framer-7D8Be .framer-ch8sps { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 352px; }",
  ".framer-7D8Be .framer-sve2a7-container, .framer-7D8Be .framer-zu6e2m-container, .framer-7D8Be .framer-17q2ucy-container { flex: none; height: auto; position: relative; width: 100%; }",
  ".framer-7D8Be .framer-1qe8wib, .framer-7D8Be .framer-1k0z85q { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 365px; }",
  ".framer-7D8Be .framer-1qtam8r-container { flex: none; height: 100%; left: calc(49.86301369863016% - 100% / 2); position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 0; }",
  '.framer-7D8Be[data-border="true"]::after, .framer-7D8Be [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 86
 * @framerIntrinsicWidth 325
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerVariables {"yjSQJXcWe":"filter"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framers7fCBlzGM = withCSS(Component, css, "framer-7D8Be");
export default Framers7fCBlzGM;
Framers7fCBlzGM.displayName = "ProductCardMiniSlider";
Framers7fCBlzGM.defaultProps = { height: 86, width: 325 };
addPropertyControls(Framers7fCBlzGM, {
  yjSQJXcWe: {
    defaultValue: "Men",
    placeholder: "",
    title: "Filter",
    type: ControlType.String,
  },
  onyjSQJXcWeChange: { changes: "yjSQJXcWe", type: ControlType.ChangeHandler },
});
addFonts(
  Framers7fCBlzGM,
  [
    { explicitInter: true, fonts: [] },
    ...ProductCardMiniFonts,
    ...SlideshowFonts,
    ...LiquidGlassFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Framers7fCBlzGM",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}',
        framerIntrinsicWidth: "325",
        framerColorSyntax: "true",
        framerVariables: '{"yjSQJXcWe":"filter"}',
        framerIntrinsicHeight: "86",
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
        framerContractVersion: "1",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
