// Generated by Framer (ff92f61)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  Link,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import AnimatedLink from "https://framerusercontent.com/modules/Qi0q2YsNOGxJXIz1UbeX/iK08p3KT4iKxnfia827l/AnimatedLink.js";
const AnimatedLinkFonts = getFonts(AnimatedLink);
const serializationHash = "framer-gI4PM";
const variantClassNames = { QI6SvSWWI: "framer-v-4n1xst" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const GBSmr65I7 = undefined;
const hMrXWD09x = undefined;
const Q5Serm7cH = undefined;
const sjXwstpq1 = undefined;
const bpLCIIzV1 = undefined;
const IVNh0TbCL = undefined;
const ZnNj69UmK = undefined;
const NOVGXPYPw = undefined;
const transition1 = {
  delay: 0,
  duration: 0.4,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
  click,
  fontSize,
  height,
  hover,
  hoverTextColor,
  id,
  link,
  textColor,
  title,
  underlineHoverColor,
  width,
  ...props
}) => {
  return {
    ...props,
    bpLCIIzV1: textColor ?? props.bpLCIIzV1 ?? "rgb(0, 0, 0)",
    GBSmr65I7: click ?? props.GBSmr65I7,
    hMrXWD09x: hover ?? props.hMrXWD09x,
    IVNh0TbCL: hoverTextColor ?? props.IVNh0TbCL ?? "rgb(0, 0, 0)",
    NOVGXPYPw: fontSize ?? props.NOVGXPYPw ?? 16,
    Q5Serm7cH: link ?? props.Q5Serm7cH,
    sjXwstpq1: title ?? props.sjXwstpq1 ?? "Shop",
    ZnNj69UmK: underlineHoverColor ?? props.ZnNj69UmK ?? "rgb(0, 0, 0)",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    GBSmr65I7,
    hMrXWD09x,
    Q5Serm7cH,
    sjXwstpq1,
    bpLCIIzV1,
    IVNh0TbCL,
    ZnNj69UmK,
    NOVGXPYPw,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "QI6SvSWWI",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTap1ohk2np = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (GBSmr65I7) {
      const res = await GBSmr65I7(...args);
      if (res === false) return false;
    }
  });
  const onMouseEnterbpgnkm = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: true });
    if (hMrXWD09x) {
      const res = await hMrXWD09x(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: Q5Serm7cH,
          motionChild: true,
          nodeId: "QI6SvSWWI",
          openInNewTab: false,
          scopeId: "pRbvwIdk9",
          smoothScroll: true,
          children: /*#__PURE__*/ _jsx(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-4n1xst",
              className,
              classNames
            )} framer-bj6wco`,
            "data-framer-name": "Default",
            "data-highlight": true,
            layoutDependency: layoutDependency,
            layoutId: "QI6SvSWWI",
            onMouseEnter: onMouseEnterbpgnkm,
            onTap: onTap1ohk2np,
            ref: refBinding,
            style: { ...style },
            children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                className: "framer-4s7xz5-container",
                "data-code-component-plugin-id": "84d4c1",
                isAuthoredByUser: true,
                layoutDependency: layoutDependency,
                layoutId: "wVG3lcmEh-container",
                nodeId: "wVG3lcmEh",
                rendersWithMotion: true,
                scopeId: "pRbvwIdk9",
                children: /*#__PURE__*/ _jsx(AnimatedLink, {
                  animationDuration: 0.3,
                  animationType: "center-out",
                  font: {
                    fontFamily: '"Inter", "Inter Placeholder", sans-serif',
                    fontStyle: "normal",
                    fontWeight: 400,
                    letterSpacing: "-0.01em",
                    lineHeight: "1.4em",
                  },
                  fontSize: NOVGXPYPw,
                  height: "100%",
                  hoverColor: IVNh0TbCL,
                  id: "wVG3lcmEh",
                  layoutId: "wVG3lcmEh",
                  text: sjXwstpq1,
                  textColor: bpLCIIzV1,
                  underlineColor: ZnNj69UmK,
                  underlineThickness: 1,
                  width: "100%",
                }),
              }),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-gI4PM.framer-bj6wco, .framer-gI4PM .framer-bj6wco { display: block; }",
  ".framer-gI4PM.framer-4n1xst { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 1px 0px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-gI4PM .framer-4s7xz5-container { flex: none; height: auto; position: relative; width: auto; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 23
 * @framerIntrinsicWidth 38
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"GBSmr65I7":"click","hMrXWD09x":"hover","Q5Serm7cH":"link","sjXwstpq1":"title","bpLCIIzV1":"textColor","IVNh0TbCL":"hoverTextColor","ZnNj69UmK":"underlineHoverColor","NOVGXPYPw":"fontSize"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerpRbvwIdk9 = withCSS(Component, css, "framer-gI4PM");
export default FramerpRbvwIdk9;
FramerpRbvwIdk9.displayName = "InlineLink";
FramerpRbvwIdk9.defaultProps = { height: 23, width: 38 };
addPropertyControls(FramerpRbvwIdk9, {
  GBSmr65I7: { title: "Click", type: ControlType.EventHandler },
  hMrXWD09x: { title: "Hover", type: ControlType.EventHandler },
  Q5Serm7cH: { title: "Link", type: ControlType.Link },
  sjXwstpq1: {
    defaultValue: "Shop",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  bpLCIIzV1: {
    defaultValue: "rgb(0, 0, 0)",
    title: "Text Color",
    type: ControlType.Color,
  },
  IVNh0TbCL: {
    defaultValue: "rgb(0, 0, 0)",
    title: "Hover Text Color",
    type: ControlType.Color,
  },
  ZnNj69UmK: {
    defaultValue: "rgb(0, 0, 0)",
    title: "Underline Hover Color",
    type: ControlType.Color,
  },
  NOVGXPYPw: {
    defaultValue: 16,
    displayStepper: true,
    max: 200,
    min: 8,
    step: 1,
    title: "Font Size",
    type: ControlType.Number,
  },
});
addFonts(
  FramerpRbvwIdk9,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...AnimatedLinkFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerpRbvwIdk9",
      slots: [],
      annotations: {
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
        framerVariables:
          '{"GBSmr65I7":"click","hMrXWD09x":"hover","Q5Serm7cH":"link","sjXwstpq1":"title","bpLCIIzV1":"textColor","IVNh0TbCL":"hoverTextColor","ZnNj69UmK":"underlineHoverColor","NOVGXPYPw":"fontSize"}',
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}',
        framerAutoSizeImages: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "23",
        framerContractVersion: "1",
        framerIntrinsicWidth: "38",
        framerImmutableVariables: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./pRbvwIdk9.map
