// Generated by Framer (24019b9)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image as Image1,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/ZEqUUiPE1cgtsBEzMwvi/m3VPTskR21Kug0DHz4Dy/faEOfJ4io.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/8CJ8LItKMLRyIk8VsKp1/3aVqdzqkcg1rGtOuBOrm/iaBy7WzBo.js";
import PrimaryButton from "https://framerusercontent.com/modules/x8bCQo9aIXzZc8Vz49DS/OVTiSyzfWu6GPkEVfWYV/jQTxYTNjI.js";
import ProductCardMiniSlider from "https://framerusercontent.com/modules/C5xcC2930F3K1n2weI9Q/o2nYvOoxlYvoE2sRmJQf/s7fCBlzGM.js";
const RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
  withFX(RichText)
);
const PrimaryButtonFonts = getFonts(PrimaryButton);
const SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
  withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
const ProductCardMiniSliderFonts = getFonts(ProductCardMiniSlider);
const cycleOrder = ["n3_s9er9E", "LXWMKDaWo", "FCg7tKWB8"];
const serializationHash = "framer-orzpi";
const variantClassNames = {
  FCg7tKWB8: "framer-v-1er1o12",
  LXWMKDaWo: "framer-v-1926v6r",
  n3_s9er9E: "framer-v-4piz0l",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const aV5leFCgU = undefined;
const DSpIx2khZ = undefined;
const goZSwjip6 = undefined;
const chsYNoXa1 = undefined;
const rahElhIZb = undefined;
const oYVtmVQc7 = undefined;
const tbwQDnYS3 = undefined;
const CL3qbw_yA = undefined;
const setrahElhIZb = undefined;
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const transition1 = { duration: 0, type: "tween" };
const transition2 = {
  delay: 0,
  duration: 0.6,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition2,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 131,
};
const transition3 = {
  delay: 0.1,
  duration: 0.6,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const animation2 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition3,
  x: 0,
  y: 0,
};
const transition4 = {
  delay: 0.2,
  duration: 0.6,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const animation3 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition4,
  x: 0,
  y: 0,
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const animation4 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 102,
};
const enumToDisplayName = (value, _locale) => {
  switch (value) {
    case "esOdew2Ux":
      return "Men";
    case "fj9lMg6YE":
      return "Women";
    default:
      return "";
  }
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  Default: "n3_s9er9E",
  Phone: "FCg7tKWB8",
  Tablet: "LXWMKDaWo",
};
const Variants = motion.create(React.Fragment);
const humanReadableEnumMap = { Men: "esOdew2Ux", Women: "fj9lMg6YE" };
const useStateVariable = (externalState, setExternalState) => {
  const [internalState, setInternalState] = React.useState(externalState);
  const [previousExternalState, setPreviousExternalState] =
    React.useState(externalState);
  if (setExternalState) {
    return [externalState, setExternalState];
  }
  if (externalState !== previousExternalState) {
    setInternalState(externalState);
    setPreviousExternalState(externalState);
  }
  return [internalState, setInternalState];
};
const getProps = ({
  buttonLink,
  buttonTitle,
  buttonVisible,
  filter,
  height,
  id,
  image,
  sliderVisible,
  subTitle,
  title,
  width,
  ...props
}) => {
  return {
    ...props,
    aV5leFCgU: image ??
      props.aV5leFCgU ?? {
        alt: "Model Image",
        pixelHeight: 768,
        pixelWidth: 1408,
        positionX: "43.9%",
        positionY: "8.1%",
        src: "https://framerusercontent.com/images/6BJRh1u8zGcjDGmCWh4o9Yz3g.png?width=1408&height=768",
        srcSet:
          "https://framerusercontent.com/images/6BJRh1u8zGcjDGmCWh4o9Yz3g.png?scale-down-to=512&width=1408&height=768 512w,https://framerusercontent.com/images/6BJRh1u8zGcjDGmCWh4o9Yz3g.png?scale-down-to=1024&width=1408&height=768 1024w,https://framerusercontent.com/images/6BJRh1u8zGcjDGmCWh4o9Yz3g.png?width=1408&height=768 1408w",
      },
    chsYNoXa1: buttonVisible ?? props.chsYNoXa1 ?? true,
    CL3qbw_yA:
      humanReadableEnumMap[filter] ?? filter ?? props.CL3qbw_yA ?? "esOdew2Ux",
    DSpIx2khZ: subTitle ?? props.DSpIx2khZ ?? "Wear Better for Less",
    goZSwjip6:
      title ?? props.goZSwjip6 ?? "Wear with elegance built for the bold",
    oYVtmVQc7: buttonLink ?? props.oYVtmVQc7,
    rahElhIZb: buttonTitle ?? props.rahElhIZb ?? "Shop Now",
    tbwQDnYS3: sliderVisible ?? props.tbwQDnYS3 ?? true,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "n3_s9er9E",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    CL3qbw_yA,
    aV5leFCgU,
    DSpIx2khZ,
    goZSwjip6,
    tbwQDnYS3,
    chsYNoXa1,
    rahElhIZb: externalrahElhIZb,
    onrahElhIZbChange: setExternalrahElhIZb,
    oYVtmVQc7,
    ...restProps
  } = getProps(props);
  const [rahElhIZb, setrahElhIZb] = useStateVariable(
    externalrahElhIZb,
    setExternalrahElhIZb
  );
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "n3_s9er9E",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const isDisplayed = (value) => {
    if (baseVariant === "FCg7tKWB8") return true;
    return value;
  };
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Image1, {
          ...restProps,
          ...gestureHandlers,
          background: {
            alt: "Model Image",
            fit: "fill",
            loading: getLoadingLazyAtYPosition(componentViewport?.y || 0),
            sizes: componentViewport?.width || "100vw",
            ...toResponsiveImage(aV5leFCgU),
          },
          className: cx(
            scopingClassNames,
            "framer-4piz0l",
            className,
            classNames
          ),
          "data-framer-name": "Default",
          layoutDependency: layoutDependency,
          layoutId: "n3_s9er9E",
          ref: refBinding,
          style: {
            borderBottomLeftRadius: 10,
            borderBottomRightRadius: 10,
            borderTopLeftRadius: 10,
            borderTopRightRadius: 10,
            ...style,
          },
          ...addPropertyOverrides(
            {
              FCg7tKWB8: { "data-framer-name": "Phone" },
              LXWMKDaWo: { "data-framer-name": "Tablet" },
            },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-11m5oq0",
            "data-framer-name": "Overlay",
            layoutDependency: layoutDependency,
            layoutId: "ik6M6BmYQ",
            style: {
              background:
                "linear-gradient(68deg, rgba(0, 0, 0, 0.2) 0%, rgba(0, 0, 0, 0) 100%)",
            },
            children: [
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-d7i33z",
                "data-framer-name": "Title + Button",
                layoutDependency: layoutDependency,
                layoutId: "Ax50N0mlj",
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-1gwltmh",
                    "data-framer-name": "Title",
                    layoutDependency: layoutDependency,
                    layoutId: "Fxkx4S0lK",
                    children: [
                      /*#__PURE__*/ _jsx(
                        RichTextWithFXWithOptimizedAppearEffect,
                        {
                          __fromCanvasComponent: true,
                          __perspectiveFX: false,
                          __smartComponentFX: true,
                          __targetOpacity: 1,
                          animate: animation,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.h6, {
                              className: "framer-styles-preset-sl1tq2",
                              "data-styles-preset": "faEOfJ4io",
                              dir: "auto",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-1w1cjl5, rgb(255, 255, 255))",
                              },
                              children: "Wear Better for Less",
                            }),
                          }),
                          className: "framer-1kmtk00",
                          "data-framer-appear-id": "1kmtk00",
                          fonts: ["Inter"],
                          initial: animation1,
                          layoutDependency: layoutDependency,
                          layoutId: "FaOsetga9",
                          optimized: true,
                          style: {
                            "--extracted-1w1cjl5": "rgb(255, 255, 255)",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                            "--framer-paragraph-spacing": "0px",
                          },
                          text: DSpIx2khZ,
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }
                      ),
                      /*#__PURE__*/ _jsx(
                        RichTextWithFXWithOptimizedAppearEffect,
                        {
                          __fromCanvasComponent: true,
                          __perspectiveFX: false,
                          __smartComponentFX: true,
                          __targetOpacity: 1,
                          animate: animation2,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.h1, {
                              className: "framer-styles-preset-nm80lz",
                              "data-styles-preset": "iaBy7WzBo",
                              dir: "auto",
                              style: {
                                "--framer-text-alignment": "left",
                                "--framer-text-color":
                                  "var(--extracted-gdpscs, rgb(255, 255, 255))",
                              },
                              children: "Wear with elegance built for the bold",
                            }),
                          }),
                          className: "framer-16yn7dk",
                          "data-framer-appear-id": "16yn7dk",
                          fonts: ["Inter"],
                          initial: animation1,
                          layoutDependency: layoutDependency,
                          layoutId: "QzlrXAoLx",
                          optimized: true,
                          style: {
                            "--extracted-gdpscs": "rgb(255, 255, 255)",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline",
                          },
                          text: goZSwjip6,
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }
                      ),
                    ],
                  }),
                  isDisplayed(chsYNoXa1 !== false) &&
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 43,
                      y:
                        (componentViewport?.y || 0) +
                        (0 +
                          ((componentViewport?.height || 710) -
                            0 -
                            ((componentViewport?.height || 710) - 0) * 1) /
                            2) +
                        20 +
                        0 +
                        143.1,
                      ...addPropertyOverrides(
                        {
                          FCg7tKWB8: {
                            y:
                              (componentViewport?.y || 0) +
                              0 +
                              (((componentViewport?.height || 710) -
                                0 -
                                (((componentViewport?.height || 710) - 0) * 1 +
                                  0)) /
                                2 +
                                0 +
                                0) +
                              10 +
                              (((componentViewport?.height || 710) - 0) * 1 -
                                20 -
                                154.6 +
                                0 +
                                0) +
                              0 +
                              111.6,
                          },
                          LXWMKDaWo: {
                            y:
                              (componentViewport?.y || 0) +
                              0 +
                              (((componentViewport?.height || 710) -
                                0 -
                                (((componentViewport?.height || 710) - 0) * 1 +
                                  0)) /
                                2 +
                                0 +
                                0) +
                              20 +
                              (((componentViewport?.height || 710) - 0) * 1 -
                                40 -
                                154.6 +
                                0 +
                                0) +
                              0 +
                              143.1,
                          },
                        },
                        baseVariant,
                        gestureVariant
                      ),
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainerWithFXWithOptimizedAppearEffect,
                        {
                          __perspectiveFX: false,
                          __smartComponentFX: true,
                          __targetOpacity: 1,
                          animate: animation3,
                          className: "framer-6fi2mt-container",
                          "data-framer-appear-id": "6fi2mt",
                          initial: animation1,
                          layoutDependency: layoutDependency,
                          layoutId: "EBdxDY02s-container",
                          nodeId: "EBdxDY02s",
                          optimized: true,
                          rendersWithMotion: true,
                          scopeId: "TIZD3Dmua",
                          children: /*#__PURE__*/ _jsx(PrimaryButton, {
                            ED8rYcY4A: "8px 25px 8px 25px",
                            height: "100%",
                            id: "EBdxDY02s",
                            layoutId: "EBdxDY02s",
                            MS7m3RNT1: rahElhIZb,
                            onMS7m3RNT1Change: setrahElhIZb,
                            OpEYI3at1: oYVtmVQc7,
                            variant: matchVariant("IDz6BjKFH"),
                            width: "100%",
                            Wq3Ff40qh:
                              "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                          }),
                        }
                      ),
                    }),
                ],
              }),
              tbwQDnYS3 !== false &&
                /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                  height: 86,
                  width: "365px",
                  y:
                    (componentViewport?.y || 0) +
                    (0 +
                      ((componentViewport?.height || 710) -
                        0 -
                        ((componentViewport?.height || 710) - 0) * 1) /
                        2) +
                    20,
                  ...addPropertyOverrides(
                    {
                      FCg7tKWB8: {
                        width: `calc(${
                          componentViewport?.width || "100vw"
                        } - 20px)`,
                        y:
                          (componentViewport?.y || 0) +
                          0 +
                          (((componentViewport?.height || 710) -
                            0 -
                            (((componentViewport?.height || 710) - 0) * 1 +
                              0)) /
                            2 +
                            0 +
                            0) +
                          10 +
                          (((componentViewport?.height || 710) - 0) * 1 -
                            20 -
                            154.6 +
                            154.6 +
                            20),
                      },
                      LXWMKDaWo: {
                        width: `calc(${
                          componentViewport?.width || "100vw"
                        } - 40px)`,
                        y:
                          (componentViewport?.y || 0) +
                          0 +
                          (((componentViewport?.height || 710) -
                            0 -
                            (((componentViewport?.height || 710) - 0) * 1 +
                              0)) /
                            2 +
                            0 +
                            0) +
                          20 +
                          (((componentViewport?.height || 710) - 0) * 1 -
                            40 -
                            154.6 +
                            154.6 +
                            20),
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                  children: /*#__PURE__*/ _jsx(
                    SmartComponentScopedContainerWithFXWithOptimizedAppearEffect,
                    {
                      __perspectiveFX: false,
                      __smartComponentFX: true,
                      __targetOpacity: 1,
                      animate: animation,
                      className: "framer-z5p7y5-container",
                      "data-framer-appear-id": "z5p7y5",
                      initial: animation4,
                      layoutDependency: layoutDependency,
                      layoutId: "Ag52YZN_O-container",
                      nodeId: "Ag52YZN_O",
                      optimized: true,
                      rendersWithMotion: true,
                      scopeId: "TIZD3Dmua",
                      children: /*#__PURE__*/ _jsx(ProductCardMiniSlider, {
                        height: "100%",
                        id: "Ag52YZN_O",
                        layoutId: "Ag52YZN_O",
                        style: { width: "100%" },
                        width: "100%",
                        yjSQJXcWe: enumToDisplayName(CL3qbw_yA, activeLocale),
                      }),
                    }
                  ),
                }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-orzpi.framer-nvx21f, .framer-orzpi .framer-nvx21f { display: block; }",
  ".framer-orzpi.framer-4piz0l { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 710px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1431px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-orzpi .framer-11m5oq0 { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; height: 100%; justify-content: space-between; overflow: hidden; padding: 20px; position: relative; width: 100%; z-index: 0; }",
  ".framer-orzpi .framer-d7i33z { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-orzpi .framer-1gwltmh { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
  ".framer-orzpi .framer-1kmtk00 { flex: none; height: auto; max-width: 600px; overflow: visible; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-orzpi .framer-16yn7dk { flex: none; height: auto; max-width: 700px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-orzpi .framer-6fi2mt-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-orzpi .framer-z5p7y5-container { flex: none; height: auto; position: relative; width: 365px; }",
  ".framer-orzpi.framer-v-1926v6r.framer-4piz0l { align-content: flex-start; align-items: flex-start; flex-direction: column; width: 829px; }",
  ".framer-orzpi.framer-v-1926v6r .framer-11m5oq0 { flex-direction: column; gap: 20px 20px; justify-content: flex-end; }",
  ".framer-orzpi.framer-v-1926v6r .framer-d7i33z, .framer-orzpi.framer-v-1er1o12 .framer-d7i33z { flex: none; width: 100%; }",
  ".framer-orzpi.framer-v-1926v6r .framer-z5p7y5-container, .framer-orzpi.framer-v-1er1o12 .framer-z5p7y5-container { width: 100%; }",
  ".framer-orzpi.framer-v-1er1o12.framer-4piz0l { align-content: flex-start; align-items: flex-start; flex-direction: column; width: 407px; }",
  ".framer-orzpi.framer-v-1er1o12 .framer-11m5oq0 { flex-direction: column; gap: 20px 20px; justify-content: flex-end; padding: 10px; }",
  ".framer-orzpi.framer-v-1er1o12 .framer-16yn7dk { max-width: 600px; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 710
 * @framerIntrinsicWidth 1431
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"LXWMKDaWo":{"layout":["fixed","fixed"]},"FCg7tKWB8":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"CL3qbw_yA":"filter","aV5leFCgU":"image","DSpIx2khZ":"subTitle","goZSwjip6":"title","tbwQDnYS3":"sliderVisible","chsYNoXa1":"buttonVisible","rahElhIZb":"buttonTitle","oYVtmVQc7":"buttonLink"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerTIZD3Dmua = withCSS(Component, css, "framer-orzpi");
export default FramerTIZD3Dmua;
FramerTIZD3Dmua.displayName = "HeroSection";
FramerTIZD3Dmua.defaultProps = { height: 710, width: 1431 };
addPropertyControls(FramerTIZD3Dmua, {
  variant: {
    options: ["n3_s9er9E", "LXWMKDaWo", "FCg7tKWB8"],
    optionTitles: ["Default", "Tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  CL3qbw_yA: {
    defaultValue: "esOdew2Ux",
    options: ["esOdew2Ux", "fj9lMg6YE"],
    optionTitles: ["Men", "Women"],
    title: "Filter",
    type: ControlType.Enum,
  },
  onCL3qbw_yAChange: { changes: "CL3qbw_yA", type: ControlType.ChangeHandler },
  aV5leFCgU: {
    __defaultAssetReference:
      "data:framer/asset-reference,6BJRh1u8zGcjDGmCWh4o9Yz3g.png?originalFilename=image.png&preferredSize=auto",
    __vekterDefault: {
      alt: "Model Image",
      assetReference:
        "data:framer/asset-reference,6BJRh1u8zGcjDGmCWh4o9Yz3g.png?originalFilename=image.png&preferredSize=auto",
      positionX: "43.9%",
      positionY: "8.1%",
    },
    title: "Image",
    type: ControlType.ResponsiveImage,
  },
  DSpIx2khZ: {
    defaultValue: "Wear Better for Less",
    displayTextArea: false,
    title: "Sub Title",
    type: ControlType.String,
  },
  onDSpIx2khZChange: { changes: "DSpIx2khZ", type: ControlType.ChangeHandler },
  goZSwjip6: {
    defaultValue: "Wear with elegance built for the bold",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  ongoZSwjip6Change: { changes: "goZSwjip6", type: ControlType.ChangeHandler },
  tbwQDnYS3: {
    defaultValue: true,
    title: "Slider Visible",
    type: ControlType.Boolean,
  },
  ontbwQDnYS3Change: { changes: "tbwQDnYS3", type: ControlType.ChangeHandler },
  chsYNoXa1: {
    defaultValue: true,
    title: "Button Visible",
    type: ControlType.Boolean,
  },
  onchsYNoXa1Change: { changes: "chsYNoXa1", type: ControlType.ChangeHandler },
  rahElhIZb: {
    defaultValue: "Shop Now",
    displayTextArea: false,
    title: "Button Title",
    type: ControlType.String,
  },
  onrahElhIZbChange: { changes: "rahElhIZb", type: ControlType.ChangeHandler },
  oYVtmVQc7: { title: "Button Link", type: ControlType.Link },
});
addFonts(
  FramerTIZD3Dmua,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...PrimaryButtonFonts,
    ...ProductCardMiniSliderFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
FramerTIZD3Dmua.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([
      forwardLoader(PrimaryButton, {}, context),
      forwardLoader(ProductCardMiniSlider, {}, context),
    ]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerTIZD3Dmua",
      slots: [],
      annotations: {
        framerAutoSizeImages: "true",
        framerVariables:
          '{"CL3qbw_yA":"filter","aV5leFCgU":"image","DSpIx2khZ":"subTitle","goZSwjip6":"title","tbwQDnYS3":"sliderVisible","chsYNoXa1":"buttonVisible","rahElhIZb":"buttonTitle","oYVtmVQc7":"buttonLink"}',
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "710",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"LXWMKDaWo":{"layout":["fixed","fixed"]},"FCg7tKWB8":{"layout":["fixed","fixed"]}}}',
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerIntrinsicWidth: "1431",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
