// Generated by Framer (747ab96)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import FC_ProductPrice from "https://framerusercontent.com/modules/N07JJZfuMtyHijtiRRgH/E4KLlxWtRCBXncxm1cnX/FC_ProductPrice.js";
import FC_ProductPriceCompare from "https://framerusercontent.com/modules/ZipJAXrtSkBsdbTSry5q/KCNDDioMjkqBn9yvxlVd/FC_ProductPriceCompare.js";
import FCQuickAddButton from "https://framerusercontent.com/modules/pdrSzkhBfLYImv2Y3WAN/HpXKDkeR5d5Q8JNW8XIl/v2Pk5uVYW.js";
const RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
  withFX(RichText)
);
const FC_ProductPriceFonts = getFonts(FC_ProductPrice);
const SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
  withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
const FC_ProductPriceCompareFonts = getFonts(FC_ProductPriceCompare);
const FCQuickAddButtonFonts = getFonts(FCQuickAddButton);
const enabledGestures = { PRBnpeWOa: { hover: true } };
const serializationHash = "framer-FVWYG";
const variantClassNames = { PRBnpeWOa: "framer-v-1yy75j1" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const MCamkPOH3 = undefined;
const SmdWZSpRL = undefined;
const imMJrf0iF = undefined;
const hUiG43MWH = undefined;
const Ku3hhIByx = undefined;
const transition1 = {
  delay: 0,
  duration: 0.4,
  ease: [0.44, 0, 0.56, 1],
  type: "tween",
};
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const transition2 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition2,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
  height,
  id,
  image,
  link,
  price,
  productID,
  title,
  width,
  ...props
}) => {
  return {
    ...props,
    hUiG43MWH: productID ?? props.hUiG43MWH,
    imMJrf0iF: title ?? props.imMJrf0iF ?? "Custom Product",
    Ku3hhIByx: price ?? props.Ku3hhIByx ?? "20.00",
    MCamkPOH3: link ?? props.MCamkPOH3,
    SmdWZSpRL: image ?? props.SmdWZSpRL,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    imMJrf0iF,
    Ku3hhIByx,
    SmdWZSpRL,
    hUiG43MWH,
    MCamkPOH3,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "PRBnpeWOa",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: MCamkPOH3,
          motionChild: true,
          nodeId: "PRBnpeWOa",
          openInNewTab: false,
          scopeId: "S2IBx96wZ",
          smoothScroll: true,
          children: /*#__PURE__*/ _jsxs(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-1yy75j1",
              className,
              classNames
            )} framer-f4k2w5`,
            "data-framer-name": "Variant 1",
            layoutDependency: layoutDependency,
            layoutId: "PRBnpeWOa",
            ref: refBinding,
            style: {
              borderBottomLeftRadius: 12,
              borderBottomRightRadius: 12,
              borderTopLeftRadius: 12,
              borderTopRightRadius: 12,
              ...style,
            },
            ...addPropertyOverrides(
              { "PRBnpeWOa-hover": { "data-framer-name": undefined } },
              baseVariant,
              gestureVariant
            ),
            children: [
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-2qep0i",
                "data-framer-name": "Image",
                layoutDependency: layoutDependency,
                layoutId: "weSjNWbHT",
                style: {
                  borderBottomLeftRadius: 8,
                  borderBottomRightRadius: 8,
                  borderTopLeftRadius: 8,
                  borderTopRightRadius: 8,
                },
                children: /*#__PURE__*/ _jsx(Image, {
                  background: {
                    alt: "",
                    fit: "fill",
                    loading: getLoadingLazyAtYPosition(
                      (componentViewport?.y || 0) + 8 + 0
                    ),
                    sizes: "70px",
                    ...toResponsiveImage(SmdWZSpRL),
                    ...{ positionX: "center", positionY: "top" },
                  },
                  className: "framer-196oems",
                  "data-border": true,
                  layoutDependency: layoutDependency,
                  layoutId: "qh34o1cgD",
                  style: {
                    "--border-bottom-width": "1px",
                    "--border-color": "rgba(34, 34, 34, 0.05)",
                    "--border-left-width": "1px",
                    "--border-right-width": "1px",
                    "--border-style": "solid",
                    "--border-top-width": "1px",
                    borderBottomLeftRadius: 8,
                    borderBottomRightRadius: 8,
                    borderTopLeftRadius: 8,
                    borderTopRightRadius: 8,
                  },
                  ...addPropertyOverrides(
                    {
                      "PRBnpeWOa-hover": {
                        background: {
                          alt: "",
                          fit: "fill",
                          loading: getLoadingLazyAtYPosition(
                            (componentViewport?.y || 0) + 8 + 70 - 72
                          ),
                          sizes: "75px",
                          ...toResponsiveImage(SmdWZSpRL),
                          ...{ positionX: "center", positionY: "top" },
                        },
                      },
                    },
                    baseVariant,
                    gestureVariant
                  ),
                }),
              }),
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-1b8ou7e",
                "data-framer-name": "Info",
                layoutDependency: layoutDependency,
                layoutId: "y4yDabUl3",
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-2bjvie",
                    "data-framer-name": "Title + Price",
                    layoutDependency: layoutDependency,
                    layoutId: "jJkUCVCnX",
                    children: [
                      /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-8rqz0p",
                        "data-framer-name": "Title",
                        layoutDependency: layoutDependency,
                        layoutId: "HcacUmbXj",
                        children: /*#__PURE__*/ _jsx(
                          RichTextWithFXWithOptimizedAppearEffect,
                          {
                            __fromCanvasComponent: true,
                            __perspectiveFX: false,
                            __smartComponentFX: true,
                            __targetOpacity: 1,
                            animate: animation,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                              children: /*#__PURE__*/ _jsx(motion.p, {
                                dir: "auto",
                                style: {
                                  "--font-selector": "SW50ZXItRXh0cmFCb2xk",
                                  "--framer-font-size": "14px",
                                  "--framer-font-weight": "800",
                                  "--framer-letter-spacing": "0px",
                                  "--framer-text-color":
                                    "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                                  "--framer-text-transform": "capitalize",
                                },
                                children: "Custom Product",
                              }),
                            }),
                            className: "framer-cpt9d9",
                            "data-framer-appear-id": "cpt9d9",
                            fonts: ["Inter-ExtraBold"],
                            initial: animation1,
                            layoutDependency: layoutDependency,
                            layoutId: "KSFsweVo6",
                            optimized: true,
                            style: {
                              "--extracted-r6o4lv": "rgb(255, 255, 255)",
                              "--framer-link-text-color": "rgb(0, 153, 255)",
                              "--framer-link-text-decoration": "underline",
                            },
                            text: imMJrf0iF,
                            variants: {
                              "PRBnpeWOa-hover": {
                                "--extracted-r6o4lv": "rgb(245, 245, 245)",
                              },
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides(
                              {
                                "PRBnpeWOa-hover": {
                                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                      dir: "auto",
                                      style: {
                                        "--font-selector":
                                          "SW50ZXItRXh0cmFCb2xk",
                                        "--framer-font-size": "14px",
                                        "--framer-font-weight": "800",
                                        "--framer-letter-spacing": "0px",
                                        "--framer-text-color":
                                          "var(--extracted-r6o4lv, rgb(245, 245, 245))",
                                        "--framer-text-transform": "capitalize",
                                      },
                                      children: "Custom Product",
                                    }),
                                  }),
                                },
                              },
                              baseVariant,
                              gestureVariant
                            ),
                          }
                        ),
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-hr77xc",
                        "data-framer-name": "Price",
                        layoutDependency: layoutDependency,
                        layoutId: "UUuxlPyll",
                        children: [
                          /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            children: /*#__PURE__*/ _jsx(
                              SmartComponentScopedContainerWithFXWithOptimizedAppearEffect,
                              {
                                __perspectiveFX: false,
                                __smartComponentFX: true,
                                __targetOpacity: 1,
                                animate: animation,
                                className: "framer-1q6b37z-container",
                                "data-framer-appear-id": "1q6b37z",
                                initial: animation1,
                                isAuthoredByUser: true,
                                isModuleExternal: true,
                                layoutDependency: layoutDependency,
                                layoutId: "uApjvfxQl-container",
                                nodeId: "uApjvfxQl",
                                optimized: true,
                                rendersWithMotion: true,
                                scopeId: "S2IBx96wZ",
                                children: /*#__PURE__*/ _jsx(FC_ProductPrice, {
                                  canvasPrice: Ku3hhIByx,
                                  displayPrice: "minimum price",
                                  format: {
                                    currencyCode: "USD",
                                    showCurrency: true,
                                    showDecimals: "Always show",
                                    showSymbol: true,
                                  },
                                  fromText: "from",
                                  height: "100%",
                                  id: "uApjvfxQl",
                                  layoutId: "uApjvfxQl",
                                  regularColor: "rgb(255, 255, 255)",
                                  regularFont: {
                                    fontFamily:
                                      '"Inter", "Inter Placeholder", sans-serif',
                                    fontSize: "13px",
                                    fontStyle: "normal",
                                    fontWeight: 800,
                                    letterSpacing: "0em",
                                    lineHeight: "1em",
                                  },
                                  saleColor: "rgb(255, 255, 255)",
                                  saleFont: {
                                    fontFamily:
                                      '"Inter", "Inter Placeholder", sans-serif',
                                    fontSize: "13px",
                                    fontStyle: "normal",
                                    fontWeight: 800,
                                    letterSpacing: "0em",
                                    lineHeight: "1em",
                                  },
                                  shopifyProductID: hUiG43MWH,
                                  width: "100%",
                                }),
                              }
                            ),
                          }),
                          /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            children: /*#__PURE__*/ _jsx(
                              SmartComponentScopedContainer,
                              {
                                className: "framer-13u9jpr-container",
                                isAuthoredByUser: true,
                                isModuleExternal: true,
                                layoutDependency: layoutDependency,
                                layoutId: "ARmVN07ht-container",
                                nodeId: "ARmVN07ht",
                                rendersWithMotion: true,
                                scopeId: "S2IBx96wZ",
                                children: /*#__PURE__*/ _jsx(
                                  FC_ProductPriceCompare,
                                  {
                                    canvasPrice: Ku3hhIByx,
                                    color: "rgb(237, 237, 237)",
                                    compareAtPrefix: "",
                                    font: {
                                      fontFamily:
                                        '"Inter", "Inter Placeholder", sans-serif',
                                      fontSize: "13px",
                                      fontStyle: "normal",
                                      fontWeight: 800,
                                      letterSpacing: "0em",
                                      lineHeight: "1em",
                                    },
                                    format: {
                                      currencyCode: "USD",
                                      showCurrency: true,
                                      showDecimals: "Always show",
                                      showSymbol: true,
                                    },
                                    height: "100%",
                                    id: "ARmVN07ht",
                                    layoutId: "ARmVN07ht",
                                    shopifyProductID: hUiG43MWH,
                                    strikethrough: true,
                                    strikethroughColor: "rgb(222, 222, 222)",
                                    strikethroughSize: 1,
                                    width: "100%",
                                  }
                                ),
                              }
                            ),
                          }),
                        ],
                      }),
                    ],
                  }),
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-16iucrw",
                    "data-framer-name": "Add Button",
                    layoutDependency: layoutDependency,
                    layoutId: "GX141QIMQ",
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      height: 25,
                      y:
                        (componentViewport?.y || 0) +
                        8 +
                        0 +
                        (((componentViewport?.height || 200) - 16) * 1 -
                          0 -
                          25) +
                        0,
                      children: /*#__PURE__*/ _jsx(
                        SmartComponentScopedContainerWithFXWithOptimizedAppearEffect,
                        {
                          __perspectiveFX: false,
                          __smartComponentFX: true,
                          __targetOpacity: 1,
                          animate: animation,
                          className: "framer-ci4cv1-container",
                          "data-framer-appear-id": "ci4cv1",
                          initial: animation1,
                          layoutDependency: layoutDependency,
                          layoutId: "RsRsZbQir-container",
                          nodeId: "RsRsZbQir",
                          optimized: true,
                          rendersWithMotion: true,
                          scopeId: "S2IBx96wZ",
                          children: /*#__PURE__*/ _jsx(FCQuickAddButton, {
                            height: "100%",
                            id: "RsRsZbQir",
                            layoutId: "RsRsZbQir",
                            width: "100%",
                            ZegMwyVes: hUiG43MWH,
                          }),
                        }
                      ),
                    }),
                  }),
                ],
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-FVWYG.framer-f4k2w5, .framer-FVWYG .framer-f4k2w5 { display: block; }",
  ".framer-FVWYG.framer-1yy75j1 { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 8px; position: relative; text-decoration: none; width: 307px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-FVWYG .framer-2qep0i { flex: none; height: 70px; overflow: hidden; position: relative; width: 70px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-FVWYG .framer-196oems { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 70px); left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); }",
  ".framer-FVWYG .framer-1b8ou7e { align-content: flex-end; align-items: flex-end; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: auto; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
  ".framer-FVWYG .framer-2bjvie { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: 100%; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-FVWYG .framer-8rqz0p { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-FVWYG .framer-cpt9d9 { flex: none; height: auto; max-width: 80%; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-FVWYG .framer-hr77xc { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-FVWYG .framer-1q6b37z-container, .framer-FVWYG .framer-13u9jpr-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-FVWYG .framer-16iucrw { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-FVWYG .framer-ci4cv1-container { flex: none; height: auto; position: relative; width: auto; z-index: 10; }",
  ".framer-FVWYG.framer-v-1yy75j1.hover .framer-196oems { bottom: -3px; height: var(--framer-aspect-ratio-supported, 75px); left: -2px; right: -3px; top: unset; }",
  '.framer-FVWYG[data-border="true"]::after, .framer-FVWYG [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 86
 * @framerIntrinsicWidth 307
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"n2qZqWqdv":{"layout":["fixed","auto"]}}}
 * @framerVariables {"imMJrf0iF":"title","Ku3hhIByx":"price","SmdWZSpRL":"image","hUiG43MWH":"productID","MCamkPOH3":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerS2IBx96wZ = withCSS(Component, css, "framer-FVWYG");
export default FramerS2IBx96wZ;
FramerS2IBx96wZ.displayName = "ProductCardMini";
FramerS2IBx96wZ.defaultProps = { height: 86, width: 307 };
addPropertyControls(FramerS2IBx96wZ, {
  imMJrf0iF: {
    defaultValue: "Custom Product",
    title: "Title",
    type: ControlType.String,
  },
  onimMJrf0iFChange: { changes: "imMJrf0iF", type: ControlType.ChangeHandler },
  Ku3hhIByx: {
    defaultValue: "20.00",
    title: "Price",
    type: ControlType.String,
  },
  onKu3hhIByxChange: { changes: "Ku3hhIByx", type: ControlType.ChangeHandler },
  SmdWZSpRL: { title: "Image", type: ControlType.ResponsiveImage },
  hUiG43MWH: {
    defaultValue: "",
    title: "Product ID",
    type: ControlType.String,
  },
  onhUiG43MWHChange: { changes: "hUiG43MWH", type: ControlType.ChangeHandler },
  MCamkPOH3: { title: "Link", type: ControlType.Link },
});
addFonts(
  FramerS2IBx96wZ,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/PONfPc6h4EPYwJliXQBmjVx7QxI.woff2",
          weight: "800",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/zsnJN7Z1wdzUvepJniD3rbvJIyU.woff2",
          weight: "800",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/UrzZBOy7RyJEWAZGduzOeHiHuY.woff2",
          weight: "800",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/996sR9SfSDuYELz8oHhDOcErkY.woff2",
          weight: "800",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/ftN1HpyPVJEoEb4q36SOrNdLXU.woff2",
          weight: "800",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/Mput0MSwESKlJ6TMz9MPDXhgrk.woff2",
          weight: "800",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/JAur4lGGSGRGyrFi59JSIKqVgU.woff2",
          weight: "800",
        },
      ],
    },
    ...FC_ProductPriceFonts,
    ...FC_ProductPriceCompareFonts,
    ...FCQuickAddButtonFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
FramerS2IBx96wZ.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([forwardLoader(FCQuickAddButton, {}, context)]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerS2IBx96wZ",
      slots: [],
      annotations: {
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
        framerColorSyntax: "true",
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"n2qZqWqdv":{"layout":["fixed","auto"]}}}',
        framerContractVersion: "1",
        framerIntrinsicWidth: "307",
        framerVariables:
          '{"imMJrf0iF":"title","Ku3hhIByx":"price","SmdWZSpRL":"image","hUiG43MWH":"productID","MCamkPOH3":"link"}',
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "86",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./S2IBx96wZ.map
