// Generated by Framer (0138aee)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  Instance,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Grids from "https://framerusercontent.com/modules/zkVRyeyZwNlCGk78KjFI/eAiawMLCVRNvce8sbO9w/QzYLBcgRC.js";
const enabledGestures = { WTjSZ3JYN: { hover: true } };
const cycleOrder = ["WTjSZ3JYN", "nKVzv1qzk"];
const serializationHash = "framer-XxZ1k";
const variantClassNames = {
  nKVzv1qzk: "framer-v-11q5tfw",
  WTjSZ3JYN: "framer-v-1yvb4yz",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const big7KzZ_0 = undefined;
const oxvver5eb = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Default: "WTjSZ3JYN", Phone: "nKVzv1qzk" };
const getProps = ({ click, height, icon, id, width, ...props }) => {
  return {
    ...props,
    big7KzZ_0: click ?? props.big7KzZ_0,
    oxvver5eb: icon ?? props.oxvver5eb ?? Grids,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "WTjSZ3JYN",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    big7KzZ_0,
    oxvver5eb,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "WTjSZ3JYN",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapb5j47l = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (big7KzZ_0) {
      const res = await big7KzZ_0(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1yvb4yz",
            className,
            classNames
          ),
          "data-border": true,
          "data-framer-name": "Default",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "WTjSZ3JYN",
          onTap: onTapb5j47l,
          ref: refBinding,
          style: {
            "--border-bottom-width": "1px",
            "--border-color": "rgba(34, 34, 34, 0.02)",
            "--border-left-width": "1px",
            "--border-right-width": "1px",
            "--border-style": "solid",
            "--border-top-width": "1px",
            backgroundColor: "rgb(250, 250, 250)",
            borderBottomLeftRadius: 8,
            borderBottomRightRadius: 8,
            borderTopLeftRadius: 8,
            borderTopRightRadius: 8,
            ...style,
          },
          variants: {
            "WTjSZ3JYN-hover": { backgroundColor: "rgb(245, 245, 245)" },
          },
          ...addPropertyOverrides(
            {
              "WTjSZ3JYN-hover": { "data-framer-name": undefined },
              nKVzv1qzk: { "data-framer-name": "Phone" },
            },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsx(Instance, {
            animated: true,
            className: "framer-1qrnz6v",
            Component: oxvver5eb,
            layoutDependency: layoutDependency,
            layoutId: "GxCvwkHe6",
            style: {
              "--19p0sve": 1.5,
              "--1o50bq4": "rgba(0, 0, 0, 0)",
              "--1ueuxnb": "rgb(0, 0, 0)",
            },
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-XxZ1k.framer-fqa82g, .framer-XxZ1k .framer-fqa82g { display: block; }",
  ".framer-XxZ1k.framer-1yvb4yz { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 34px; justify-content: center; overflow: visible; padding: 9px; position: relative; width: 34px; }",
  ".framer-XxZ1k .framer-1qrnz6v { flex: none; height: var(--framer-aspect-ratio-supported, 20px); position: relative; width: 20px; }",
  ".framer-XxZ1k.framer-v-11q5tfw.framer-1yvb4yz { height: 28px; width: 28px; }",
  ".framer-XxZ1k.framer-v-11q5tfw .framer-1qrnz6v { height: var(--framer-aspect-ratio-supported, 16px); width: 16px; }",
  '.framer-XxZ1k[data-border="true"]::after, .framer-XxZ1k [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 34
 * @framerIntrinsicWidth 34
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"nKVzv1qzk":{"layout":["fixed","fixed"]},"h28ri1dGt":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"big7KzZ_0":"click","oxvver5eb":"icon"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerVectorSets ["4pmxSVQBLYE9vfheas6H"]
 */ const FramerzjCOmdjqb = withCSS(Component, css, "framer-XxZ1k");
export default FramerzjCOmdjqb;
FramerzjCOmdjqb.displayName = "LayoutToggle";
FramerzjCOmdjqb.defaultProps = { height: 34, width: 34 };
addPropertyControls(FramerzjCOmdjqb, {
  variant: {
    options: ["WTjSZ3JYN", "nKVzv1qzk"],
    optionTitles: ["Default", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  big7KzZ_0: { title: "Click", type: ControlType.EventHandler },
  oxvver5eb: {
    defaultValue: {
      identifier: "local-module:vector/QzYLBcgRC:default",
      moduleId: "zkVRyeyZwNlCGk78KjFI",
    },
    setModuleId: "4pmxSVQBLYE9vfheas6H",
    title: "Icon",
    type: ControlType.VectorSetItem,
  },
});
addFonts(FramerzjCOmdjqb, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerzjCOmdjqb",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "34",
        framerVectorSets: '["4pmxSVQBLYE9vfheas6H"]',
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"nKVzv1qzk":{"layout":["fixed","fixed"]},"h28ri1dGt":{"layout":["fixed","fixed"]}}}',
        framerImmutableVariables: "true",
        framerAutoSizeImages: "true",
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerIntrinsicWidth: "34",
        framerVariables: '{"big7KzZ_0":"click","oxvver5eb":"icon"}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
