export const currencyMaps = {
  AED: "د.إ",
  AFN: "Af",
  ALL: "L",
  AMD: "֏",
  ANG: "ƒ",
  AOA: "Kz",
  ARS: "$",
  AUD: "$",
  AWG: "ƒ",
  AZN: "₼",
  BAM: "KM",
  BBD: "$",
  BDT: "৳",
  BGN: "лв",
  BHD: "د.ب",
  BIF: "FBu",
  BMD: "$",
  BND: "$",
  BOB: "Bs.",
  BRL: "R$",
  BSD: "$",
  BTN: "Nu.",
  BWP: "P",
  BYN: "Br",
  BZD: "BZ$",
  CAD: "$",
  CDF: "FC",
  CHF: "Fr",
  CLP: "$",
  CNY: "\xa5",
  COP: "$",
  CRC: "₡",
  CVE: "$",
  CZK: "Kč",
  DJF: "Fdj",
  DKK: "kr",
  DOP: "RD$",
  DZD: "د.ج",
  EGP: "\xa3",
  ERN: "Nfk",
  ETB: "Br",
  EUR: "€",
  FJD: "$",
  FKP: "\xa3",
  GBP: "\xa3",
  GEL: "₾",
  GHS: "₵",
  GIP: "\xa3",
  GMD: "D",
  GNF: "FG",
  GTQ: "Q",
  GYD: "$",
  HKD: "$",
  HNL: "L",
  HRK: "kn",
  HTG: "G",
  HUF: "Ft",
  IDR: "Rp",
  ILS: "₪",
  INR: "₹",
  IQD: "ع.د",
  IRR: "﷼",
  ISK: "kr",
  JEP: "\xa3",
  JMD: "J$",
  JOD: "د.ا",
  JPY: "\xa5",
  KES: "KSh",
  KGS: "сом",
  KHR: "៛",
  KID: "$",
  KMF: "CF",
  KRW: "₩",
  KWD: "د.ك",
  KYD: "$",
  KZT: "₸",
  LAK: "₭",
  LBP: "\xa3",
  LKR: "රු",
  LRD: "$",
  LSL: "L",
  LTL: "Lt",
  LVL: "Ls",
  LYD: "ل.د",
  MAD: "د.م.",
  MDL: "MDL",
  MGA: "Ar",
  MKD: "ден",
  MMK: "Ks",
  MNT: "₮",
  MOP: "MOP$",
  MRU: "UM",
  MUR: "₨",
  MVR: "ރ",
  MWK: "MK",
  MXN: "$",
  MYR: "RM",
  MZN: "MT",
  NAD: "$",
  NGN: "₦",
  NIO: "C$",
  NOK: "kr",
  NPR: "रू",
  NZD: "$",
  OMR: "ر.ع.",
  PAB: "B/.",
  PEN: "S/.",
  PGK: "K",
  PHP: "₱",
  PKR: "₨",
  PLN: "zł",
  PYG: "₲",
  QAR: "ر.ق",
  RON: "lei",
  RSD: "Дин.",
  RUB: "₽",
  RWF: "FRw",
  SAR: "ر.س",
  SBD: "$",
  SCR: "₨",
  SDG: "ج.س.",
  SEK: "kr",
  SGD: "$",
  SHP: "\xa3",
  SLL: "Le",
  SOS: "Sh",
  SRD: "$",
  SSP: "\xa3",
  STN: "Db",
  SYP: "\xa3",
  SZL: "E",
  THB: "฿",
  TJS: "ЅМ",
  TMT: "T",
  TND: "د.ت",
  TOP: "T$",
  TRY: "₺",
  TTD: "TT$",
  TWD: "NT$",
  TZS: "TSh",
  UAH: "₴",
  UGX: "USh",
  USD: "$",
  UYU: "$",
  UZS: "so'm",
  VED: "Bs.S.",
  VES: "Bs.",
  VND: "₫",
  VUV: "VT",
  WST: "T",
  XAF: "FCFA",
  XCD: "$",
  XOF: "CFA",
  XPF: "₣",
  XXX: "",
  YER: "﷼",
  ZAR: "R",
  ZMW: "ZK",
  BYR: "Br",
  STD: "Db",
  VEF: "Bs.",
}; // Explicit list of currencies where the symbol is the same as the code
// or where browsers commonly display the code instead of a distinct symbol
export const knownCurrenciesWithCodeAsSymbol = [
  "CHF",
  "PLN",
  "SEK",
  "NOK",
  "DKK",
  "CZK",
  "HUF",
  "RON",
  "HRK",
  "BGN",
  "ISK",
  "MDL",
  "BYN",
  "KZT",
  "AMD",
  "UZS",
  "TJS",
  "KGS",
  "MNT",
  "GEL",
  "AFN",
  "MRU",
  "RWF",
  "XAF",
  "XOF",
  "XPF",
];
export const __FramerMetadata__ = {
  exports: {
    currencyMaps: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    knownCurrenciesWithCodeAsSymbol: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./currencyMaps.map
