// Generated by Framer (6ca5d98)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addPropertyControls,
  ControlType,
  cx,
  motion,
  useSVGTemplate,
  withCSS,
} from "framer";
import * as React from "react";
import { forwardRef } from "react";
const mask = "var(--framer-icon-mask)";
const Base = /*#__PURE__*/ forwardRef(function (props, ref) {
  return /*#__PURE__*/ _jsx("svg", {
    ...props,
    ref: ref,
    children: props.children,
  });
});
const MotionSVG = motion.create(Base);
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(MotionSVG, {
        ...rest,
        layoutId: layoutId,
        ref: ref,
        children: children,
      })
    : /*#__PURE__*/ _jsx("svg", { ...rest, ref: ref, children: children });
});
const svg =
  '<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 9 C 0 4.029 3.358 0 7.5 0 C 11.642 0 15 4.029 15 9 C 15 13.971 11.642 18 7.5 18 C 3.358 18 0 13.971 0 9 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="18px" id="gDmvhnhIu" transform="translate(4.5 3)" width="15px"/><path d="M 14.25 4.28 C 13.299 1.808 11.303 0 7.5 0 C 1.5 0 0 4.5 0 9 C 0 13.5 1.5 18 7.5 18 C 12 18 14.25 15 14.25 12.75 C 14.25 6.75 4.5 6.75 4.5 11.25 C 4.5 15 11.25 15 11.25 9 C 11.25 3.75 6 3.75 4.5 6" fill="transparent" height="18px" id="fnLV5UJmT" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(4.5 3)" width="14.25px"/></svg>';
const getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
  return {
    ...props,
    ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
    lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
    qxTvv_EBh: alpha ?? props.qxTvv_EBh,
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const {
    style,
    className,
    layoutId,
    variant,
    ezTt3ayMo,
    lschgej4H,
    qxTvv_EBh,
    ...restProps
  } = getProps(props);
  const href = useSVGTemplate("3242964309", svg);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    className: cx("framer-8iX4M", className),
    layoutId: layoutId,
    ref: ref,
    role: "presentation",
    style: {
      "--1m6trwb": qxTvv_EBh,
      "--21h8s6": ezTt3ayMo,
      "--pgex8v": lschgej4H,
      ...style,
    },
    viewBox: "0 0 24 24",
    children: /*#__PURE__*/ _jsx("use", { href: href }),
  });
});
const css = [
  `.framer-8iX4M { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"ezTt3ayMo":"color","lschgej4H":"width1","qxTvv_EBh":"alpha"}
 * @framerImmutableVariables true
 * @framerVector {"name":"Threads Logo","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}
 * @framerDisableUnlink true
 */ const Icon = withCSS(Component, css, "framer-8iX4M");
Icon.displayName = "Threads Logo";
export default Icon;
addPropertyControls(Icon, {
  ezTt3ayMo: {
    defaultValue: "rgb(0, 0, 0)",
    hidden: false,
    title: "Color",
    type: ControlType.Color,
  },
  lschgej4H: {
    defaultValue: 1.5,
    displayStepper: true,
    hidden: false,
    max: 6,
    min: 0,
    step: 0.5,
    title: "Width",
    type: ControlType.Number,
  },
  qxTvv_EBh: {
    defaultValue: 0,
    displayStepper: true,
    hidden: false,
    max: 1,
    min: 0,
    step: 0.1,
    title: "Alpha",
    type: ControlType.Number,
  },
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerVariables:
          '{"ezTt3ayMo":"color","lschgej4H":"width1","qxTvv_EBh":"alpha"}',
        framerVector:
          '{"name":"Threads Logo","color":{"type":"variable","value":"21h8s6"},"set":{"localId":"vectorSet/NGVKdicsm","id":"NGVKdicsm","moduleId":"omX0gWFPqDwhaiWwf6ab"}}',
        framerSupportedLayoutHeight: "any-prefer-fixed",
        framerDisableUnlink: "true",
        framerImmutableVariables: "true",
        framerSupportedLayoutWidth: "any-prefer-fixed",
        framerIntrinsicHeight: "24",
        framerContractVersion: "1",
        framerIntrinsicWidth: "24",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
