// Generated by Framer (f4aa214)
import {
  jsx as _jsx,
  jsxs as _jsxs,
  Fragment as _Fragment,
} from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ChildrenCanSuspend,
  ComponentViewportProvider,
  ControlType,
  cx,
  forwardLoader,
  getFonts,
  getFontsFromSharedStyle,
  Link,
  PathVariablesContext,
  queryCache,
  ResolveLinks,
  RichText,
  SmartComponentScopedContainer,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useQueryData,
  useRouter,
  useVariantState,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import FC_GlobalMarketActive from "https://framerusercontent.com/modules/IRNPUGQe13VXFTk5iND0/x0S1itd9K7qngwU8KE4b/FC_GlobalMarketActive.js";
import FavoriteState from "https://framerusercontent.com/modules/VYG1O0mDB31Iq7AMtNX2/8hIzNmWBY1uJXNNu5stz/FavoriteState.js";
import Categories from "https://framerusercontent.com/modules/Y3RbBCDE2ddoQx43Ly7A/hbhiwig2TFp4fa2PCNFN/ZFPX8XxiR.js";
import * as sharedStyle from "https://framerusercontent.com/modules/WDiDGKhAkTPrfefpnwhL/nbDKAutS6DXDfkr9fhlQ/As3AmUndW.js";
import InlineLink from "https://framerusercontent.com/modules/M9VmBwq8VB4cCMeKVq7i/UkjWfFvd6xL5tCL0T9au/pRbvwIdk9.js";
const InlineLinkFonts = getFonts(InlineLink);
const FavoriteStateFonts = getFonts(FavoriteState);
const FC_GlobalMarketActiveFonts = getFonts(FC_GlobalMarketActive);
const MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
  withFX(motion.div)
);
const cycleOrder = ["EL50pMwQ_", "I8tprn_y7"];
const serializationHash = "framer-4P3w6";
const variantClassNames = {
  EL50pMwQ_: "framer-v-1ukond5",
  I8tprn_y7: "framer-v-3xs2ii",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const WCfVjfId9 = undefined;
const WYxq8X3Zx = undefined;
const nrKGcDENuzymsa6DcU = undefined;
const FP3hEwQ6mzymsa6DcU = undefined;
const idzymsa6DcU = undefined;
const transition1 = {
  damping: 40,
  delay: 0.3,
  mass: 1,
  stiffness: 200,
  type: "spring",
};
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 10,
};
const transition2 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const query = (prequery) =>
  prequery({
    from: { alias: "zymsa6DcU", data: Categories, type: "Collection" },
    limit: { type: "LiteralValue", value: 10 },
    select: [
      { collection: "zymsa6DcU", name: "nrKGcDENu", type: "Identifier" },
      { collection: "zymsa6DcU", name: "FP3hEwQ6m", type: "Identifier" },
      { collection: "zymsa6DcU", name: "id", type: "Identifier" },
    ],
  });
const query1 = () => ({
  from: { alias: "zymsa6DcU", data: Categories, type: "Collection" },
  limit: { type: "LiteralValue", value: 10 },
  select: [
    { collection: "zymsa6DcU", name: "nrKGcDENu", type: "Identifier" },
    { collection: "zymsa6DcU", name: "FP3hEwQ6m", type: "Identifier" },
    { collection: "zymsa6DcU", name: "id", type: "Identifier" },
  ],
});
const QueryData = ({ query, pageSize, children }) => {
  const data = useQueryData(query);
  return children(data);
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = { Men: "EL50pMwQ_", Women: "I8tprn_y7" };
const Variants = motion.create(React.Fragment);
const getProps = ({ click, favorites, height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "EL50pMwQ_",
    WCfVjfId9: click ?? props.WCfVjfId9,
    WYxq8X3Zx: favorites ?? props.WYxq8X3Zx,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    WCfVjfId9,
    WYxq8X3Zx,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "EL50pMwQ_",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const GBSmr65I73p6nx9 = activeVariantCallback(async (...args) => {
    if (WCfVjfId9) {
      const res = await WCfVjfId9(...args);
      if (res === false) return false;
    }
  });
  const onTap1unmhyk = activeVariantCallback(async (...args) => {
    if (WYxq8X3Zx) {
      const res = await WYxq8X3Zx(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const router = useRouter();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition2,
        children: /*#__PURE__*/ _jsxs(
          MotionDivWithFXWithOptimizedAppearEffect,
          {
            ...restProps,
            ...gestureHandlers,
            __framer__presenceAnimate: animation,
            __framer__presenceInitial: animation1,
            __perspectiveFX: false,
            __smartComponentFX: true,
            __targetOpacity: 1,
            className: cx(
              scopingClassNames,
              "framer-1ukond5",
              className,
              classNames
            ),
            "data-framer-appear-id": "1ukond5",
            "data-framer-name": "Men",
            layoutDependency: layoutDependency,
            layoutId: "EL50pMwQ_",
            optimized: true,
            ref: refBinding,
            style: { ...style },
            ...addPropertyOverrides(
              { I8tprn_y7: { "data-framer-name": "Women" } },
              baseVariant,
              gestureVariant
            ),
            children: [
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-6ee1bi",
                "data-framer-name": "Links",
                layoutDependency: layoutDependency,
                layoutId: "yrtbaUsXg",
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-9dkf8k",
                    "data-framer-name": "Shop",
                    layoutDependency: layoutDependency,
                    layoutId: "LyeYlGdxE",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1ogwna3",
                            "data-styles-preset": "As3AmUndW",
                            dir: "auto",
                            style: {
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, rgba(0, 0, 0, 0.32))",
                            },
                            children: "Shop",
                          }),
                        }),
                        className: "framer-ail97j",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "PMNHfu7D5",
                        style: {
                          "--extracted-r6o4lv": "rgba(0, 0, 0, 0.32)",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1w2zbgn",
                        layoutDependency: layoutDependency,
                        layoutId: "z2eH1uFeH",
                        children: [
                          /*#__PURE__*/ _jsx(ResolveLinks, {
                            links: [
                              {
                                href: { webPageId: "CNxtwd8vu" },
                                implicitPathVariables: undefined,
                              },
                              {
                                href: { webPageId: "CNxtwd8vu" },
                                implicitPathVariables: undefined,
                              },
                            ],
                            children: (resolvedLinks) =>
                              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                height: 23,
                                y:
                                  (componentViewport?.y || 0) +
                                  20 +
                                  (0 +
                                    0 +
                                    (((componentViewport?.height || 584) -
                                      20 -
                                      761.4) /
                                      1) *
                                      0) +
                                  0 +
                                  0 +
                                  0 +
                                  33.8 +
                                  0 +
                                  0,
                                children: /*#__PURE__*/ _jsx(
                                  SmartComponentScopedContainer,
                                  {
                                    className: "framer-14hq2gw-container",
                                    layoutDependency: layoutDependency,
                                    layoutId: "mCAXai0sP-container",
                                    nodeId: "mCAXai0sP",
                                    rendersWithMotion: true,
                                    scopeId: "CK5j_oBmO",
                                    children: /*#__PURE__*/ _jsx(InlineLink, {
                                      bpLCIIzV1:
                                        "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                      GBSmr65I7: GBSmr65I73p6nx9,
                                      height: "100%",
                                      id: "mCAXai0sP",
                                      IVNh0TbCL:
                                        "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                      layoutId: "mCAXai0sP",
                                      NOVGXPYPw: 16,
                                      Q5Serm7cH: resolvedLinks[0],
                                      sjXwstpq1: "Men",
                                      width: "100%",
                                      ZnNj69UmK:
                                        "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                      ...addPropertyOverrides(
                                        {
                                          I8tprn_y7: {
                                            Q5Serm7cH: resolvedLinks[1],
                                          },
                                        },
                                        baseVariant,
                                        gestureVariant
                                      ),
                                    }),
                                  }
                                ),
                              }),
                          }),
                          /*#__PURE__*/ _jsx(ResolveLinks, {
                            links: [
                              {
                                href: { webPageId: "ihpyuJvKq" },
                                implicitPathVariables: undefined,
                              },
                              {
                                href: { webPageId: "ihpyuJvKq" },
                                implicitPathVariables: undefined,
                              },
                            ],
                            children: (resolvedLinks1) =>
                              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                height: 23,
                                y:
                                  (componentViewport?.y || 0) +
                                  20 +
                                  (0 +
                                    0 +
                                    (((componentViewport?.height || 584) -
                                      20 -
                                      761.4) /
                                      1) *
                                      0) +
                                  0 +
                                  0 +
                                  0 +
                                  33.8 +
                                  0 +
                                  33,
                                children: /*#__PURE__*/ _jsx(
                                  SmartComponentScopedContainer,
                                  {
                                    className: "framer-ggjp6u-container",
                                    layoutDependency: layoutDependency,
                                    layoutId: "zgjX3pIGt-container",
                                    nodeId: "zgjX3pIGt",
                                    rendersWithMotion: true,
                                    scopeId: "CK5j_oBmO",
                                    children: /*#__PURE__*/ _jsx(InlineLink, {
                                      bpLCIIzV1:
                                        "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                      GBSmr65I7: GBSmr65I73p6nx9,
                                      height: "100%",
                                      id: "zgjX3pIGt",
                                      IVNh0TbCL:
                                        "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                      layoutId: "zgjX3pIGt",
                                      NOVGXPYPw: 16,
                                      Q5Serm7cH: resolvedLinks1[0],
                                      sjXwstpq1: "Women",
                                      width: "100%",
                                      ZnNj69UmK:
                                        "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                      ...addPropertyOverrides(
                                        {
                                          I8tprn_y7: {
                                            Q5Serm7cH: resolvedLinks1[1],
                                          },
                                        },
                                        baseVariant,
                                        gestureVariant
                                      ),
                                    }),
                                  }
                                ),
                              }),
                          }),
                        ],
                      }),
                    ],
                  }),
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-17c2zcp",
                    "data-framer-name": "Collections",
                    layoutDependency: layoutDependency,
                    layoutId: "ex0Gcyz0A",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1ogwna3",
                            "data-styles-preset": "As3AmUndW",
                            dir: "auto",
                            style: {
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, rgba(0, 0, 0, 0.32))",
                            },
                            children: "Categories",
                          }),
                        }),
                        className: "framer-x8l0o0",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "lMLVCcbdc",
                        style: {
                          "--extracted-r6o4lv": "rgba(0, 0, 0, 0.32)",
                          "--framer-link-text-color": "rgb(0, 153, 255)",
                          "--framer-link-text-decoration": "underline",
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1hwkcwk",
                        layoutDependency: layoutDependency,
                        layoutId: "DSosg5mvi",
                        children: /*#__PURE__*/ _jsx(motion.div, {
                          className: "framer-1co7je7",
                          layoutDependency: layoutDependency,
                          layoutId: "zymsa6DcU",
                          children: /*#__PURE__*/ _jsx(ChildrenCanSuspend, {
                            children: /*#__PURE__*/ _jsx(QueryData, {
                              query: query1(),
                              children: (
                                collection,
                                paginationInfo,
                                loadMore
                              ) => {
                                return /*#__PURE__*/ _jsx(_Fragment, {
                                  children: collection?.map(
                                    (
                                      {
                                        FP3hEwQ6m: FP3hEwQ6mzymsa6DcU,
                                        id: idzymsa6DcU,
                                        nrKGcDENu: nrKGcDENuzymsa6DcU,
                                      },
                                      index
                                    ) => {
                                      nrKGcDENuzymsa6DcU ??= "";
                                      FP3hEwQ6mzymsa6DcU ??= "";
                                      return /*#__PURE__*/ _jsx(
                                        LayoutGroup,
                                        {
                                          id: `zymsa6DcU-${idzymsa6DcU}`,
                                          children: /*#__PURE__*/ _jsx(
                                            PathVariablesContext.Provider,
                                            {
                                              value: {
                                                nrKGcDENu: nrKGcDENuzymsa6DcU,
                                              },
                                              children: /*#__PURE__*/ _jsx(
                                                Link,
                                                {
                                                  href: {
                                                    pathVariables: {
                                                      nrKGcDENu:
                                                        nrKGcDENuzymsa6DcU,
                                                    },
                                                    webPageId: "WvEH3mXtq",
                                                  },
                                                  motionChild: true,
                                                  nodeId: "vSsS763bq",
                                                  scopeId: "CK5j_oBmO",
                                                  ...addPropertyOverrides(
                                                    {
                                                      I8tprn_y7: {
                                                        href: {
                                                          pathVariables: {
                                                            nrKGcDENu:
                                                              nrKGcDENuzymsa6DcU,
                                                          },
                                                          webPageId:
                                                            "PvmaXeeJb",
                                                        },
                                                        openInNewTab: false,
                                                      },
                                                    },
                                                    baseVariant,
                                                    gestureVariant
                                                  ),
                                                  children: /*#__PURE__*/ _jsx(
                                                    motion.a,
                                                    {
                                                      className:
                                                        "framer-y24ccx framer-122t4ck",
                                                      layoutDependency:
                                                        layoutDependency,
                                                      layoutId: "vSsS763bq",
                                                      children:
                                                        /*#__PURE__*/ _jsx(
                                                          ComponentViewportProvider,
                                                          {
                                                            height: 23,
                                                            y:
                                                              (componentViewport?.y ||
                                                                0) +
                                                              20 +
                                                              (0 +
                                                                0 +
                                                                (((componentViewport?.height ||
                                                                  584) -
                                                                  20 -
                                                                  761.4) /
                                                                  1) *
                                                                  0) +
                                                              0 +
                                                              129.8 +
                                                              0 +
                                                              33.8 +
                                                              0 +
                                                              0 +
                                                              0 +
                                                              165 +
                                                              0,
                                                            children:
                                                              /*#__PURE__*/ _jsx(
                                                                SmartComponentScopedContainer,
                                                                {
                                                                  className:
                                                                    "framer-h1xjfr-container",
                                                                  layoutDependency:
                                                                    layoutDependency,
                                                                  layoutId:
                                                                    "uqgTmQ28c-container",
                                                                  nodeId:
                                                                    "uqgTmQ28c",
                                                                  rendersWithMotion: true,
                                                                  scopeId:
                                                                    "CK5j_oBmO",
                                                                  children:
                                                                    /*#__PURE__*/ _jsx(
                                                                      InlineLink,
                                                                      {
                                                                        bpLCIIzV1:
                                                                          "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                                                        GBSmr65I7:
                                                                          GBSmr65I73p6nx9,
                                                                        height:
                                                                          "100%",
                                                                        id: "uqgTmQ28c",
                                                                        IVNh0TbCL:
                                                                          "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                                                        layoutId:
                                                                          "uqgTmQ28c",
                                                                        NOVGXPYPw: 16,
                                                                        sjXwstpq1:
                                                                          FP3hEwQ6mzymsa6DcU,
                                                                        width:
                                                                          "100%",
                                                                        ZnNj69UmK:
                                                                          "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                                                      }
                                                                    ),
                                                                }
                                                              ),
                                                          }
                                                        ),
                                                    }
                                                  ),
                                                }
                                              ),
                                            }
                                          ),
                                        },
                                        idzymsa6DcU
                                      );
                                    }
                                  ),
                                });
                              },
                            }),
                          }),
                        }),
                      }),
                    ],
                  }),
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-6d028m",
                    "data-framer-name": "account",
                    layoutDependency: layoutDependency,
                    layoutId: "sH5jCiSY2",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1ogwna3",
                            "data-styles-preset": "As3AmUndW",
                            dir: "auto",
                            style: {
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, rgba(0, 0, 0, 0.32))",
                            },
                            children: "Account",
                          }),
                        }),
                        className: "framer-he9k0i",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "oOrFADa2l",
                        style: {
                          "--extracted-r6o4lv": "rgba(0, 0, 0, 0.32)",
                          "--framer-paragraph-spacing": "0px",
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-mxf3mo",
                        "data-framer-name": "items",
                        layoutDependency: layoutDependency,
                        layoutId: "qkeRCiZN4",
                        children: [
                          /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 23,
                            y:
                              (componentViewport?.y || 0) +
                              20 +
                              (0 +
                                0 +
                                (((componentViewport?.height || 584) -
                                  20 -
                                  761.4) /
                                  1) *
                                  0) +
                              0 +
                              391.6 +
                              0 +
                              33.8 +
                              0 +
                              0,
                            children: /*#__PURE__*/ _jsx(
                              SmartComponentScopedContainer,
                              {
                                className: "framer-abmqpc-container",
                                layoutDependency: layoutDependency,
                                layoutId: "nDPvUsBJN-container",
                                nodeId: "nDPvUsBJN",
                                rendersWithMotion: true,
                                scopeId: "CK5j_oBmO",
                                children: /*#__PURE__*/ _jsx(InlineLink, {
                                  bpLCIIzV1:
                                    "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                  GBSmr65I7: GBSmr65I73p6nx9,
                                  height: "100%",
                                  id: "nDPvUsBJN",
                                  IVNh0TbCL:
                                    "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                  layoutId: "nDPvUsBJN",
                                  NOVGXPYPw: 16,
                                  sjXwstpq1: "My Account",
                                  width: "100%",
                                  ZnNj69UmK:
                                    "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                }),
                              }
                            ),
                          }),
                          /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-1k88w7u",
                            "data-highlight": true,
                            layoutDependency: layoutDependency,
                            layoutId: "uk82lVHvR",
                            onTap: onTap1unmhyk,
                            children: [
                              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                height: 23,
                                y:
                                  (componentViewport?.y || 0) +
                                  20 +
                                  (0 +
                                    0 +
                                    (((componentViewport?.height || 584) -
                                      20 -
                                      761.4) /
                                      1) *
                                      0) +
                                  0 +
                                  391.6 +
                                  0 +
                                  33.8 +
                                  0 +
                                  33 +
                                  0,
                                children: /*#__PURE__*/ _jsx(
                                  SmartComponentScopedContainer,
                                  {
                                    className: "framer-gr4ydb-container",
                                    layoutDependency: layoutDependency,
                                    layoutId: "BRTD4FQF9-container",
                                    nodeId: "BRTD4FQF9",
                                    rendersWithMotion: true,
                                    scopeId: "CK5j_oBmO",
                                    children: /*#__PURE__*/ _jsx(InlineLink, {
                                      bpLCIIzV1:
                                        "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                      GBSmr65I7: GBSmr65I73p6nx9,
                                      height: "100%",
                                      id: "BRTD4FQF9",
                                      IVNh0TbCL:
                                        "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                      layoutId: "BRTD4FQF9",
                                      NOVGXPYPw: 16,
                                      sjXwstpq1: "Favorites",
                                      width: "100%",
                                      ZnNj69UmK:
                                        "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                                    }),
                                  }
                                ),
                              }),
                              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                children: /*#__PURE__*/ _jsx(
                                  SmartComponentScopedContainer,
                                  {
                                    className: "framer-mmef24-container",
                                    "data-code-component-plugin-id": "84d4c1",
                                    isAuthoredByUser: true,
                                    layoutDependency: layoutDependency,
                                    layoutId: "PneIhAooE-container",
                                    nodeId: "PneIhAooE",
                                    rendersWithMotion: true,
                                    scopeId: "CK5j_oBmO",
                                    children: /*#__PURE__*/ _jsx(
                                      FavoriteState,
                                      {
                                        activeChildren: [],
                                        alignment: "center",
                                        borderRadius: 20,
                                        boxShadow: "",
                                        direction: "horizontal",
                                        fillColor:
                                          "var(--token-1c5e3028-cf81-4827-947b-4b310a111190, rgb(219, 44, 58))",
                                        gap: 10,
                                        height: "100%",
                                        id: "PneIhAooE",
                                        layoutId: "PneIhAooE",
                                        mode: "display",
                                        padding: "0px",
                                        storageKey: "favorite-triggers",
                                        style: {
                                          height: "100%",
                                          width: "100%",
                                        },
                                        triggerId: "default",
                                        width: "100%",
                                      }
                                    ),
                                  }
                                ),
                              }),
                            ],
                          }),
                        ],
                      }),
                    ],
                  }),
                ],
              }),
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-1kjjul0",
                "data-framer-name": "Bottom",
                layoutDependency: layoutDependency,
                layoutId: "qtbRCVU_F",
                children: [
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-olt3b7",
                    "data-border": true,
                    "data-framer-name": "Line",
                    layoutDependency: layoutDependency,
                    layoutId: "EYZUEbXlZ",
                    style: {
                      "--border-bottom-width": "0px",
                      "--border-color":
                        "var(--token-ab1a65fa-a184-40ca-b195-1036c81a9fa4, rgb(247, 247, 247))",
                      "--border-left-width": "0px",
                      "--border-right-width": "0px",
                      "--border-style": "solid",
                      "--border-top-width": "0.5px",
                    },
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-wo3kv6-container",
                        isAuthoredByUser: true,
                        isModuleExternal: true,
                        layoutDependency: layoutDependency,
                        layoutId: "mvw3nq6pO-container",
                        nodeId: "mvw3nq6pO",
                        rendersWithMotion: true,
                        scopeId: "CK5j_oBmO",
                        children: /*#__PURE__*/ _jsx(FC_GlobalMarketActive, {
                          color:
                            "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                          font: {},
                          format: "{{CN}} / {{CC}} / {{CUS}} / {{CUC}}",
                          height: "100%",
                          id: "mvw3nq6pO",
                          layoutId: "mvw3nq6pO",
                          previewCountry: "US",
                          previewCurrency: "USD",
                          textTransform: "None",
                          width: "100%",
                        }),
                      }
                    ),
                  }),
                ],
              }),
            ],
          }
        ),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-4P3w6.framer-122t4ck, .framer-4P3w6 .framer-122t4ck { display: block; }",
  ".framer-4P3w6.framer-1ukond5 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; height: 584px; justify-content: space-between; overflow: var(--overflow-clip-fallback, clip); padding: 20px 20px 0px 20px; position: relative; width: 309px; }",
  ".framer-4P3w6 .framer-6ee1bi { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 40px 0px; position: relative; width: 100%; }",
  ".framer-4P3w6 .framer-9dkf8k, .framer-4P3w6 .framer-1w2zbgn, .framer-4P3w6 .framer-17c2zcp, .framer-4P3w6 .framer-1hwkcwk, .framer-4P3w6 .framer-6d028m, .framer-4P3w6 .framer-mxf3mo { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-4P3w6 .framer-ail97j, .framer-4P3w6 .framer-x8l0o0 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-4P3w6 .framer-14hq2gw-container, .framer-4P3w6 .framer-ggjp6u-container, .framer-4P3w6 .framer-h1xjfr-container, .framer-4P3w6 .framer-abmqpc-container, .framer-4P3w6 .framer-gr4ydb-container, .framer-4P3w6 .framer-wo3kv6-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-4P3w6 .framer-1co7je7 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: 0px; position: relative; width: min-content; }",
  ".framer-4P3w6 .framer-y24ccx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-4P3w6 .framer-he9k0i { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; z-index: 1; }",
  ".framer-4P3w6 .framer-1k88w7u { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-4P3w6 .framer-mmef24-container { flex: none; height: 8px; position: relative; width: 8px; z-index: 1; }",
  ".framer-4P3w6 .framer-1kjjul0 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 20px 0px 20px 0px; position: relative; width: 100%; z-index: 1; }",
  ".framer-4P3w6 .framer-olt3b7 { flex: none; height: 1px; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; position: absolute; top: 0px; width: 100%; z-index: 1; }",
  ...sharedStyle.css,
  '.framer-4P3w6[data-border="true"]::after, .framer-4P3w6 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 584
 * @framerIntrinsicWidth 309
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"I8tprn_y7":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"WCfVjfId9":"click","WYxq8X3Zx":"favorites"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerCK5j_oBmO = withCSS(Component, css, "framer-4P3w6");
export default FramerCK5j_oBmO;
FramerCK5j_oBmO.displayName = "PhoneNav";
FramerCK5j_oBmO.defaultProps = { height: 584, width: 309 };
addPropertyControls(FramerCK5j_oBmO, {
  variant: {
    options: ["EL50pMwQ_", "I8tprn_y7"],
    optionTitles: ["Men", "Women"],
    title: "Variant",
    type: ControlType.Enum,
  },
  WCfVjfId9: { title: "Click", type: ControlType.EventHandler },
  WYxq8X3Zx: { title: "Favorites", type: ControlType.EventHandler },
});
addFonts(
  FramerCK5j_oBmO,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...InlineLinkFonts,
    ...FavoriteStateFonts,
    ...FC_GlobalMarketActiveFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
FramerCK5j_oBmO.loader = {
  load: (props, context) => {
    const locale = context.locale;
    const queryCacheEntry = queryCache.get(query1(), locale);
    return Promise.allSettled([
      queryCacheEntry.preload(),
      forwardLoader(InlineLink, {}, context),
      (async () => {
        const parentData = (await queryCacheEntry.readMaybeAsync()) ?? [];
        return Promise.allSettled(
          parentData.flatMap((item) => forwardLoader(InlineLink, {}, context))
        );
      })(),
    ]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerCK5j_oBmO",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "309",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"I8tprn_y7":{"layout":["fixed","fixed"]}}}',
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "584",
        framerAutoSizeImages: "true",
        framerColorSyntax: "true",
        framerContractVersion: "1",
        framerComponentViewportWidth: "true",
        framerVariables: '{"WCfVjfId9":"click","WYxq8X3Zx":"favorites"}',
        framerDisplayContentsDiv: "false",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./CK5j_oBmO.map
