// Generated by Framer (747ab96)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addPropertyControls,
  ControlType,
  cx,
  motion,
  useSVGTemplate,
  withCSS,
} from "framer";
import * as React from "react";
import { forwardRef } from "react";
const h8kC9jrrV = undefined;
const o7u3jogiS = undefined;
const dwH03SpeX = undefined;
const mask = "var(--framer-icon-mask)";
const Base = /*#__PURE__*/ forwardRef(function (props, ref) {
  return /*#__PURE__*/ _jsx("svg", {
    ...props,
    ref: ref,
    children: props.children,
  });
});
const MotionSVG = motion.create(Base);
const SVG = /*#__PURE__*/ forwardRef((props, ref) => {
  const { animated, layoutId, children, ...rest } = props;
  return animated
    ? /*#__PURE__*/ _jsx(MotionSVG, {
        ...rest,
        layoutId: layoutId,
        ref: ref,
        children: children,
      })
    : /*#__PURE__*/ _jsx("svg", { ...rest, ref: ref, children: children });
});
const svg =
  '<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><g d="M 18 9 C 18 13.971 13.971 18 9 18 C 4.029 18 0 13.971 0 9 C 0 4.029 4.029 0 9 0 C 13.971 0 18 4.029 18 9 Z M 12.5 7.5 C 12.5 9.699 10.691 11 9 11 C 7.309 11 5.5 9.612 5.5 7.5 C 5.5 5.388 7.152 4 9 4 C 10.848 4 12.5 5.301 12.5 7.5 Z M 3.15 15.3 L 3.654 14.418 C 4.455 13.015 6.327 11 9 11 C 11.673 11 13.544 13.016 14.345 14.418 L 14.849 15.3" fill="transparent" height="18px" id="DJ5wucjrb" transform="translate(3 3)" width="18px"><path d="M 18 9 C 18 13.971 13.971 18 9 18 C 4.029 18 0 13.971 0 9 C 0 4.029 4.029 0 9 0 C 13.971 0 18 4.029 18 9 Z" fill="var(--1o50bq4, rgba(0, 0, 0, 0))" height="18px" id="QgxtFj3rS" stroke-dasharray="" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-width="var(--19p0sve, 1.5)" stroke="var(--1ueuxnb, var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0)))" width="18px"/><path d="M 7 3.5 C 7 5.699 5.191 7 3.5 7 C 1.809 7 0 5.612 0 3.5 C 0 1.388 1.652 0 3.5 0 C 5.348 0 7 1.301 7 3.5 Z" fill="var(--1o50bq4, rgba(0, 0, 0, 0))" height="7.000000476837535px" id="F9qtn6SFp" stroke-dasharray="" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-width="var(--19p0sve, 1.5)" stroke="var(--1ueuxnb, var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0)))" transform="translate(5.5 4)" width="7px"/><path d="M 0 4.3 L 0.504 3.418 C 1.305 2.015 3.177 0 5.85 0 C 8.523 0 10.394 2.016 11.195 3.418 L 11.699 4.3" fill="var(--1o50bq4, rgba(0, 0, 0, 0))" height="4.300000585772761px" id="Dxb7ZrzsR" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--19p0sve, 1.5)" stroke="var(--1ueuxnb, var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0)))" transform="translate(3.15 11)" width="11.69910004207389px"/></g></svg>';
const getProps = ({ color, fill, height, id, width, width1, ...props }) => {
  return {
    ...props,
    dwH03SpeX:
      color ??
      props.dwH03SpeX ??
      "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
    h8kC9jrrV: fill ?? props.h8kC9jrrV ?? "rgba(0, 0, 0, 0)",
    o7u3jogiS: width1 ?? props.o7u3jogiS ?? 1.5,
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const {
    style,
    className,
    layoutId,
    variant,
    dwH03SpeX,
    h8kC9jrrV,
    o7u3jogiS,
    ...restProps
  } = getProps(props);
  const href = useSVGTemplate("2263052851", svg);
  return /*#__PURE__*/ _jsx(SVG, {
    ...restProps,
    className: cx("framer-YfUT5", className),
    layoutId: layoutId,
    ref: ref,
    role: "presentation",
    style: {
      "--19p0sve": o7u3jogiS,
      "--1o50bq4": h8kC9jrrV,
      "--1ueuxnb": dwH03SpeX,
      ...style,
    },
    viewBox: "0 0 24 24",
    children: /*#__PURE__*/ _jsx("use", { href: href }),
  });
});
const css = [
  `.framer-YfUT5 { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicWidth 24
 * @framerIntrinsicHeight 24
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 * @framerVariables {"dwH03SpeX":"color","h8kC9jrrV":"fill","o7u3jogiS":"width1"}
 * @framerImmutableVariables true
 * @framerVector {"name":"User-circle","set":{"localId":"vectorSet/XcHWe4vE5","id":"XcHWe4vE5","moduleId":"4pmxSVQBLYE9vfheas6H"}}
 */ const Icon = withCSS(Component, css, "framer-YfUT5");
Icon.displayName = "User-circle";
export default Icon;
addPropertyControls(Icon, {
  dwH03SpeX: {
    defaultValue:
      'var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0)) /* {"name":"Black"} */',
    hidden: false,
    title: "Color",
    type: ControlType.Color,
  },
  h8kC9jrrV: {
    defaultValue: "rgba(0, 0, 0, 0)",
    hidden: false,
    title: "Fill",
    type: ControlType.Color,
  },
  o7u3jogiS: {
    defaultValue: 1.5,
    hidden: false,
    min: 0,
    title: "Width",
    type: ControlType.Number,
  },
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Icon",
      slots: [],
      annotations: {
        framerVector:
          '{"name":"User-circle","set":{"localId":"vectorSet/XcHWe4vE5","id":"XcHWe4vE5","moduleId":"4pmxSVQBLYE9vfheas6H"}}',
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerSupportedLayoutWidth: "any-prefer-fixed",
        framerVariables:
          '{"dwH03SpeX":"color","h8kC9jrrV":"fill","o7u3jogiS":"width1"}',
        framerIntrinsicHeight: "24",
        framerSupportedLayoutHeight: "any-prefer-fixed",
        framerIntrinsicWidth: "24",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
