// Generated by Framer (b47b624)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFonts,
  Link,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import UserCircle from "https://framerusercontent.com/modules/U3A40vsbrIkW5RCzTeZb/SU7Xnn5bRB85sI21Hjz9/qqfpy6ijM.js";
const UserCircleFonts = getFonts(UserCircle);
const cycleOrder = ["XwkSHQPTT", "Qf7SE1Lvj"];
const serializationHash = "framer-opSMo";
const variantClassNames = {
  Qf7SE1Lvj: "framer-v-1vnpxcq",
  XwkSHQPTT: "framer-v-1rx6fmn",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = { Default: "Qf7SE1Lvj", Vairent2: "XwkSHQPTT" };
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "XwkSHQPTT",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "XwkSHQPTT",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: "https://shopify.com/67917185093/account",
          motionChild: true,
          nodeId: "XwkSHQPTT",
          openInNewTab: false,
          scopeId: "rNwagb7Z1",
          ...addPropertyOverrides(
            {
              Qf7SE1Lvj: {
                href: "https://shopfiy-eight.vercel.app/api/auth/shopify/login",
              },
            },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.a, {
            ...restProps,
            ...gestureHandlers,
            "aria-label": "User account",
            className: `${cx(
              scopingClassNames,
              "framer-1rx6fmn",
              className,
              classNames
            )} framer-7cr5r0`,
            "data-framer-name": "Vairent2",
            layoutDependency: layoutDependency,
            layoutId: "XwkSHQPTT",
            ref: refBinding,
            style: { ...style },
            ...addPropertyOverrides(
              { Qf7SE1Lvj: { "data-framer-name": "Default" } },
              baseVariant,
              gestureVariant
            ),
            children: [
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-dvtul1",
                layoutDependency: layoutDependency,
                layoutId: "rKu71MKqv",
                style: {
                  backgroundColor:
                    "var(--token-17761d99-d475-492f-930b-b7968ad54731, rgb(227, 215, 197))",
                  borderBottomLeftRadius: 20,
                  borderBottomRightRadius: 20,
                  borderTopLeftRadius: 20,
                  borderTopRightRadius: 20,
                  boxShadow: "0px 0px 0px 1.5px rgb(255, 255, 255)",
                  opacity: 1,
                },
                variants: { Qf7SE1Lvj: { opacity: 0 } },
              }),
              /*#__PURE__*/ _jsx(UserCircle, {
                animated: true,
                className: "framer-1sy509w",
                layoutDependency: layoutDependency,
                layoutId: "lhxwYLtsX",
                style: {
                  "--19p0sve": 1.5,
                  "--1o50bq4": "rgba(0, 0, 0, 0)",
                  "--1ueuxnb":
                    "var(--token-1189f16c-e454-4a61-8167-c15df9bec650, rgb(0, 0, 0))",
                },
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-opSMo.framer-7cr5r0, .framer-opSMo .framer-7cr5r0 { display: block; }",
  ".framer-opSMo.framer-1rx6fmn { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-opSMo .framer-dvtul1 { flex: none; height: 7px; overflow: visible; position: absolute; right: 1px; top: 1px; width: 7px; z-index: 1; }",
  ".framer-opSMo .framer-1sy509w { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 24
 * @framerIntrinsicWidth 24
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"Qf7SE1Lvj":{"layout":["auto","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerrNwagb7Z1 = withCSS(Component, css, "framer-opSMo");
export default FramerrNwagb7Z1;
FramerrNwagb7Z1.displayName = "Profile";
FramerrNwagb7Z1.defaultProps = { height: 24, width: 24 };
addPropertyControls(FramerrNwagb7Z1, {
  variant: {
    options: ["XwkSHQPTT", "Qf7SE1Lvj"],
    optionTitles: ["Vairent2", "Default"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  FramerrNwagb7Z1,
  [{ explicitInter: true, fonts: [] }, ...UserCircleFonts],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerrNwagb7Z1",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "24",
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerAutoSizeImages: "true",
        framerIntrinsicHeight: "24",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"Qf7SE1Lvj":{"layout":["auto","auto"]}}}',
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./rNwagb7Z1.map
