// Generated by Framer (f4aa214)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  ComponentViewportProvider,
  Container,
  cx,
  forwardLoader,
  GeneratedComponentContext,
  getFonts,
  getWhereExpressionFromPathVariables,
  NotFoundError,
  PropertyOverrides,
  queryCache,
  useComponentViewport,
  useCurrentPathVariables,
  useCustomCursors,
  useHydratedBreakpointVariants,
  useIsOnFramerCanvas,
  useLocaleInfo,
  useMetadata,
  useQueryData,
  withCSS,
  withFlowFX,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import ProductCatalog from "#framer/local/canvasComponent/DjE60noyY/DjE60noyY.js";
import Categories from "#framer/local/collection/ZFPX8XxiR/ZFPX8XxiR.js";
import metadataProvider from "#framer/local/webPageMetadata/WvEH3mXtq/WvEH3mXtq.js";
const ProductCatalogFonts = getFonts(ProductCatalog);
const MotionDivWithFlowFX = withFlowFX(motion.div);
const breakpoints = {
  JIqlO960a: "(min-width: 1200px)",
  OsrHo6qv4: "(min-width: 810px) and (max-width: 1199.98px)",
  WpY_bQjvp: "(max-width: 809.98px)",
};
const isBrowser = () => typeof document !== "undefined";
export const queryParamNames = [];
const serializationHash = "framer-XISiX";
const variantClassNames = {
  JIqlO960a: "framer-v-178izko",
  OsrHo6qv4: "framer-v-c8s2cv",
  WpY_bQjvp: "framer-v-13mpyda",
};
const wwAumLPqS = undefined;
const FP3hEwQ6m = undefined;
const transition1 = { bounce: 0.2, delay: 0, duration: 0.3, type: "spring" };
const getRootLayoutProp = (
  hasLayoutTemplate,
  hasInheritedFlowEffect,
  fallback
) => {
  if (!hasLayoutTemplate) return fallback;
  return hasInheritedFlowEffect ? "position" : fallback;
};
const convertFromEnum = (value, activeLocale) => {
  switch (value) {
    case "EzgkdgWB3":
      return "All";
    case "Yw4ZMHWXG":
      return "Collection";
    case "nqn11u835":
      return "Product Type";
    case "XAICVqci9":
      return "Product Tag";
    default:
      return "All";
  }
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const humanReadableVariantMap = {
  Desktop: "JIqlO960a",
  Phone: "WpY_bQjvp",
  Tablet: "OsrHo6qv4",
};
const HTMLStyle = ({ value }) => {
  const onCanvas = useIsOnFramerCanvas();
  if (onCanvas) return null;
  return /*#__PURE__*/ _jsx("style", {
    dangerouslySetInnerHTML: { __html: value },
    "data-framer-html-style": "",
  });
};
const detailQuery = (where) => ({
  from: { alias: "WvEH3mXtq", data: Categories, type: "Collection" },
  select: [
    { collection: "WvEH3mXtq", name: "FP3hEwQ6m", type: "Identifier" },
    { collection: "WvEH3mXtq", name: "wwAumLPqS", type: "Identifier" },
  ],
  where,
});
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "JIqlO960a",
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const currentPathVariables = useCurrentPathVariables();
  const [currentRouteData] = useQueryData(
    detailQuery(
      getWhereExpressionFromPathVariables(currentPathVariables, "WvEH3mXtq")
    )
  );
  const getFromCurrentRouteData = (key) => {
    if (!currentRouteData)
      throw new NotFoundError(
        `No data matches path variables: ${JSON.stringify(
          currentPathVariables
        )}`
      );
    return currentRouteData[key];
  };
  const {
    style,
    className,
    layoutId,
    variant,
    FP3hEwQ6m = getFromCurrentRouteData("FP3hEwQ6m") ?? "",
    wwAumLPqS = getFromCurrentRouteData("wwAumLPqS"),
    ...restProps
  } = getProps(props);
  const metadata = React.useMemo(
    () => metadataProvider({ FP3hEwQ6m }, activeLocale),
    [FP3hEwQ6m, activeLocale]
  );
  useMetadata(metadata);
  const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(
    variant,
    breakpoints,
    false
  );
  const gestureVariant = undefined;
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const hasLayoutTemplate = React.useContext(
    GeneratedComponentContext
  )?.isLayoutTemplate;
  const hasInheritedFlowEffect = Boolean(
    React.useContext(MotionConfigContext)?.transition?.layout
  );
  const motionLayout = getRootLayoutProp(
    hasLayoutTemplate,
    hasInheritedFlowEffect,
    "position"
  );
  useCustomCursors({});
  return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
    value: {
      activeVariantId: baseVariant,
      humanReadableVariantMap,
      primaryVariantId: "JIqlO960a",
      variantClassNames,
    },
    children: /*#__PURE__*/ _jsxs(LayoutGroup, {
      id: layoutId ?? defaultLayoutId,
      children: [
        /*#__PURE__*/ _jsx(HTMLStyle, {
          value:
            "html body { background: var(--token-a1d66695-261b-4112-b609-9b6c0fb55851, rgb(255, 255, 255)); }",
        }),
        /*#__PURE__*/ _jsx(MotionDivWithFlowFX, {
          ...restProps,
          className: cx(scopingClassNames, "framer-178izko", className),
          flowEffectEnabled: true,
          flowEffectTransition: transition1,
          isNestedFlowEffect: false,
          ref: refBinding,
          style: { ...style },
          children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
            height: 1150,
            width: `calc(${componentViewport?.width || "100vw"} - 40px)`,
            y: (componentViewport?.y || 0) + 140 + 0,
            children: /*#__PURE__*/ _jsx(Container, {
              className: "framer-8blhsp-container",
              "data-framer-name": "Products",
              layout: motionLayout,
              name: "Products",
              nodeId: "DvTLQvedw",
              rendersWithMotion: true,
              scopeId: "WvEH3mXtq",
              children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                breakpoint: baseVariant,
                overrides: {
                  OsrHo6qv4: { variant: matchVariant("XwabFEGsl") },
                  WpY_bQjvp: { variant: matchVariant("UjAt8sNbq") },
                },
                children: /*#__PURE__*/ _jsx(ProductCatalog, {
                  bC4HKe_BQ: convertFromEnum(wwAumLPqS, activeLocale),
                  Bm8WsDKX5: FP3hEwQ6m,
                  DK7MK3w_2: true,
                  height: "100%",
                  id: "DvTLQvedw",
                  jiHI7nrcA: FP3hEwQ6m,
                  layoutId: "DvTLQvedw",
                  m1vC6hoIB: "default",
                  name: "Products",
                  rpLfDNOp4: "XDkBoO5hU",
                  style: { maxWidth: "100%", width: "100%" },
                  variant: matchVariant("SV8sCDdeJ"),
                  width: "100%",
                  Xqb0WThtf: "Men",
                }),
              }),
            }),
          }),
        }),
        /*#__PURE__*/ _jsx("div", { id: "overlay" }),
      ],
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-XISiX.framer-1uts19p, .framer-XISiX .framer-1uts19p { display: block; }",
  ".framer-XISiX.framer-178izko { align-content: center; align-items: center; background-color: var(--token-a1d66695-261b-4112-b609-9b6c0fb55851, #ffffff); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 160px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 140px 20px 140px 20px; position: relative; width: 1200px; }",
  ".framer-XISiX .framer-8blhsp-container { flex: none; height: auto; max-width: 100%; position: relative; width: 100%; }",
  "@media (min-width: 810px) and (max-width: 1199.98px) { .framer-XISiX.framer-178izko { width: 810px; }}",
  "@media (max-width: 809.98px) { .framer-XISiX.framer-178izko { width: 390px; }}",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1966
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"OsrHo6qv4":{"layout":["fixed","auto"]},"WpY_bQjvp":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerAcceptsLayoutTemplate true
 * @framerScrollSections false
 * @framerResponsiveScreen true
 * @framerLayoutTemplateFlowEffect true
 */ const FramerWvEH3mXtq = withCSS(Component, css, "framer-XISiX");
export default FramerWvEH3mXtq;
FramerWvEH3mXtq.displayName = "Categories";
FramerWvEH3mXtq.defaultProps = { height: 1966, width: 1200 };
addFonts(
  FramerWvEH3mXtq,
  [{ explicitInter: true, fonts: [] }, ...ProductCatalogFonts],
  { supportsExplicitInterCodegen: true }
);
FramerWvEH3mXtq.loader = {
  load: (props, context) => {
    const locale = context.locale;
    return Promise.allSettled([
      queryCache
        .get(
          detailQuery(
            getWhereExpressionFromPathVariables(
              context.pathVariables,
              "WvEH3mXtq"
            )
          ),
          locale
        )
        .preload(),
      forwardLoader(ProductCatalog, {}, context),
    ]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    queryParamNames: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerWvEH3mXtq",
      slots: [],
      annotations: {
        framerAutoSizeImages: "true",
        framerLayoutTemplateFlowEffect: "true",
        framerDisplayContentsDiv: "false",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"OsrHo6qv4":{"layout":["fixed","auto"]},"WpY_bQjvp":{"layout":["fixed","auto"]}}}',
        framerAcceptsLayoutTemplate: "true",
        framerContractVersion: "1",
        framerScrollSections: "false",
        framerComponentViewportWidth: "true",
        framerIntrinsicWidth: "1200",
        framerColorSyntax: "true",
        framerResponsiveScreen: "true",
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "1966",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
